### ISSUE TITLE
bugs in sample()

### ISSUE THREAD

**Issue by rpruim** [ProjectMOSAIC/mosaic#168]
The following bug report is from Ben Hansen (U Mich):

Dear Dr. Pruim,

I'm a big fan of the mosaic package, which I've been using to good effect in the classroom for a year or so now.  I'm writing now to report what I believe to be a glitch in your sample.data.frame method.  (Thanks for the terrific service of offering a data frame method for this function!)  Or actually two of them:
 1. (minor) It doesn't seem to accept a "groups" argument in quite the intended way:
```r
> head(resample(Galton, groups=sex))
Error in eval(expr, envir, enclos) : object 'sex' not found
> head(resample(Galton, groups=~sex))
Error in if (as.character(ans[[1L]])[1L] == "~") { : 
  missing value where TRUE/FALSE needed
> head(resample(Galton, groups=Galton$sex))
    family father mother sex height nkids
140     38   71.0     66   M   69.0     6
162     44   71.5     65   M   67.7     2
279     70   70.0     65   M   65.0     5
860    196   65.5     63   M   71.0     4
```

 2. When it does accept the groups argument, it appears not to resample separately within the groups:
```r
> table(resample(Galton, groups=Galton$sex)$sex)

  F   M 
416 482 
> table(resample(Galton, groups=Galton$sex)$sex)

  F   M 
404 494 
```

Were it resampling separately by group, then I'd expect to see the same numbers of each group in the resample as were in the original sample.

**Comment by rpruim** [comment]
This appears to have been repaired quite some time ago:
```r
tally( ~ sex, data = resample(Galton, groups=sex))
## 
##   F   M 
## 433 465 
tally( ~ sex, data = Galton)
## 
##   F   M 
## 433 465 
```

**Comment by nicholasjhorton** [comment]
This would be useful as an example to include somewhere (resampling in the RJournal paper?  resampling vignette?)
> On Oct 7, 2015, at 3:25 PM, Randall Pruim <notifications@github.com> wrote:
> 
> This appears to have been repaired quite some time ago:
> 
> tally( ~ sex, data = resample(Galton, groups=sex
> ))
> 
> ## 
> ##   F   M 
> ## 433 465 
> 
> tally( 
> ~ sex, data = Galton
> )
> 
> ## 
> ##   F   M 
> ## 433 465 
> —
> Reply to this email directly or view it on GitHub.
> 

Nicholas Horton 
Professor of Statistics
Department of Mathematics and Statistics, Amherst College
Box 2239, 31 Quadrangle Dr
Amherst, MA 01002-5000
https://www.amherst.edu/people/facstaff/nhorton

**Comment by rpruim** [comment]
See http://www.calvin.edu/~rpruim/talks/LessVolume/2015-06-24-AKL/LessVolume-2015-06-24.html#68
