### ISSUE TITLE
should favstats support (~ x1 + x2, data=ds)?

### ISSUE THREAD

**Issue by nicholasjhorton** [ProjectMOSAIC/mosaic#184]
Ben Baumer writes: Here's another one:

> favstats(~satv, data=SAT)
 min    Q1 median    Q3 max     mean       sd  n missing
 484 501.5    526 564.5 602 534.3922 33.87452 51       0
> favstats(~satv + satm, data=SAT)
 min    Q1 median    Q3 max     mean       sd  n missing
 484 501.5    526 564.5 602 534.3922 33.87452 51       0

These two things shouldn't return the same result. It should either be an error, or even better it should return this:

> favstats(~satv + satm, data=SAT)
var min    Q1 median    Q3 max     mean       sd  n missing
satv 484 501.5    526 564.5 602 534.3922 33.87452 51       0
satm 474 510    527 559 613 536.7255 33.67081 51       0

More generally, if I want favstats for all of the numeric vectors in a data frame, I should be able to get them all in a way that makes comparison easy. So "favstats(~., data=SAT)" should work.

**Comment by rpruim** [comment]
This has been lying dormant a long time.  Any new thoughts?  Do we want
```{r}
foo( ~ a + b, data= )
```
to be different from 
```{r}
foo( ~ a, data= )
```
plus a warning message?  Perhaps we might want it to be essentially
```{r}
rbind(
  foo( ~ a, data = ),
  foo( ~b, data = )
)
```
as Ben originally suggested.  If it isn't too hard to implement, I'm leaning in that direction.

**Comment by nicholasjhorton** [comment]
I may have originally suggested this (and I'm not sure that it's necessary).  My main concern is that:

favstats(~ a + b)

has a very different meaning than

tally(~ a + b)

Nick

**Comment by nicholasjhorton** [comment]
I'd propose that we drop this (I'm not enthusiastic about the ~ a + b syntax).
