### ISSUE TITLE
improvements to plotDist() windowing

### ISSUE THREAD

**Issue by rpruim** [ProjectMOSAIC/mosaic#188]
Currently plotDist() selects points for generating the plot based on ppoints().  This is nice because it allows plotDist() to use information about the distribution to select the range to view. 

But perhaps we could add some more flexibility by

(a) using xlim to determine the sample points if xlim is specified,

(b) flanking the region determined by ppoints() a bit (have to decide how much) so that, for example, distributions with a finite interval for support show some of the portion where the pdf is 0.   As is, these "tails" are omitted.

The downside to adding these tails is that it adds bogus "vertical" lines to the plot if we do this with type="l". 

So we need to think about the pros and cons of various options here.

**Comment by nicholasjhorton** [comment]
I'm not wild about the default plot for F distributions: plotDist("f", df1=1, df2=96)
Is there an easy fix?

**Comment by rpruim** [comment]
This is not a "bug".  The behavior is the same here as for all of the distributions.  Really, the problem here is the distribution -- the density function has no maximum and the ascent to the vertical asymptote is very steep and the descent into the horizontal asymptote is very flat.

The current solution is that you should just use `ylim` to see the portion of it that you want.  I'd actually be curious to know what window you think is best for this distribution, what proportion of the distribution is displayed on your plot, and how many tries it takes you to come up with your window.  

I'm happy to entertain a heuristic that you think does a better job, but keep in mind that it should work well for more typical distributions (i.e. ones that don't involve improper integrals) as well. Here's part of the problem -- for most distributions, I think we want to see the central 99%, certainly the central 95%.  But these sorts of heuristics work badly for this particular distribution.  Below are some example points on the density curve to illustrate the problem.

```r
p <- c(0.001, 0.01, 0.025, 0.05, 0.5,  0.95, 0.975, 0.99, 0.999)
x <- qf(p, 1, 96)
y <- df(x, 1, 96)
cbind(p, x, y) %>% round(4)
##           p       x        y
##  [1,] 0.001  0.0000 316.6560
##  [2,] 0.010  0.0002  31.6623
##  [3,] 0.025  0.0010  12.6578
##  [4,] 0.050  0.0040   6.3163
##  [5,] 0.500  0.4584   0.4665
##  [6,] 0.950  3.9402   0.0285
##  [7,] 0.975  5.1852   0.0136
##  [8,] 0.990  6.9065   0.0052
##  [9,] 0.999 11.5245   0.0005


```

**Comment by nicholasjhorton** [comment]
I think that it's hard for students to visualize F distributions with the current setup.  

I had them run:
xpf(2, df1=1, df2=5)
xpf(2, df1=1, df2=25)
xpf(2, df1=5, df2=5)
xpf(2, df1=5, df2=25)

to explore.  I wish I could have had them run equivalent calls to "plotDist()" so my arbitrary 2 wasn't needed.  Just my $0.02, Nick

**Comment by rpruim** [comment]
OK.  It took a bit, but I've figured out why the two plots are different.  They both do essentially the same thing to compute the points to be plotted.  It is a bit of an accident that things work better for `xpf()`.  The happy accident comes because if no `ymax` is provided, I compute one  and allow some head room for the labels that go above the plot.  But my heuristic for this uses the 95th percentile of the plotted y-values:
```r
ymax <- 1.1 * quantile(ydata, 0.95, na.rm=TRUE)
```
So for distributions like F(1, 96) -- where the density at the 95the percentile is much smaller than, say, at the 99th percentile -- this has a side effect of clipping the asymptote.

**Comment by rpruim** [comment]
PS. For having students look at the F dists, you might use `xqf()` with `p = 0.95`.  That is probably more meaningful than your arbitrary `2`, since it shows that traditional critical value.

**Comment by rpruim** [comment]
Now comes decision time:

1) should I modify `plotDist()` to set `ylim` the way `xpf()` does [probably a good idea]
2) Is `ymax <- 1.1 * quantile(ydata, 0.95, na.rm=TRUE)` the right heuristic to use?

**Comment by rpruim** [comment]
Oops.  Didn't copy enough code before.  Here's the chunk that sets `ylim` in `xpf()` and friends:
```r
ymax <- 1.1 * quantile(ydata, 0.95, na.rm=TRUE)
  if (missing(ylim)) {
    ylim = c(0, 1.4 * ymax)  # quantile(ydata, 0.95, na.rm = TRUE))
  }
```

**Comment by nicholasjhorton** [comment]
Your suggestion to teach with xqf is a really good one.  

Is there a way to assess the skewness in a quick and dirty way as an alternative mechanism to setting the limits?  I certainly don't want to break plotDist("norm") or others that work fine at present.

**Comment by rpruim** [comment]
I think I have something reasonable now.  One issue is that the solution used by `xpf()` and friends won't work for discrete distributions.  So I'm sampling again *after* determining that the distribution is continuous.

**Comment by rpruim** [comment]
```r
plotDist("f", df1=1, df2 = 99)
```

![image](https://cloud.githubusercontent.com/assets/722231/25308165/e1710336-277c-11e7-849f-40a35ca799c6.png)
