### ISSUE TITLE
formula interface for paired t test

### ISSUE THREAD

**Issue by rpruim** [ProjectMOSAIC/mosaic#269]
Ideally, how do we want to do paired t tests?  We can do this, and perhaps this makes the most sense and emphasizes that paired t tests are nothing special:

```r
> t.test( ~(Air - Helium), data=heliumFootballs)

	One Sample t-test

data:  data$(Air - Helium)
t = -0.4198, df = 38, p-value = 0.677
alternative hypothesis: true mean is not equal to 0
95 percent confidence interval:
 -2.687423  1.764346
sample estimates:
 mean of x 
-0.4615385 
```

With a little work, we could probably get
```r
t.test(~ Air - Helium, data=heliumFootballs)
```
to work as well.  (It does not currently.)

Are there other syntax options we would want to support?

**Comment by rpruim** [comment]
Last chance to champion this in the `mosaic` package.  Else we can refer people to `tigerstats`.

**Comment by AmeliaMN** [comment]
Apparently I'm 5 years too late here! But I would have loved to have the `paired=TRUE` argument work with formula syntax.
