### ISSUE TITLE
default markdown template does not compile to pdf 

### ISSUE THREAD

**Issue by nicholasjhorton** [ProjectMOSAIC/mosaic#339]
The default markdown template in version 0.9-4 works fine to generate html or Word, but fails if you change to pdf as output format (because of the .gif).

output file: Preview-160dd1f9c986b.knit.md

pandoc: Error producing PDF from TeX source.
! LaTeX Error: Unknown graphics extension: .gif.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.109 ...cnZjLmFjLnVrL0ltYWdlcy9sb2dvX3IuZ2lm.gif}

Error: pandoc document conversion failed with error 43
Execution halted

**Comment by nicholasjhorton** [comment]
I believe that the fancy template still compiles to pdf (by default) as of 0.9.3-1.99.  Is it feasible to change this to html (for folks without LaTeX installed)?

**Comment by rpruim** [comment]
I changed the default to HTML.  PDF should also work for those who have things installed if they toggle the output format.

**Comment by nicholasjhorton** [comment]
Thanks: this one bit me several times at the workshop last week.

Nick

> On May 12, 2015, at 6:49 AM, Randall Pruim <notifications@github.com> wrote:
> 
> I changed the default to HTML. PDF should also work for those who have things installed if they toggle the output format.
> 
> —
> Reply to this email directly or view it on GitHub.
> 

Nicholas Horton 
Professor of Statistics
Department of Mathematics and Statistics, Amherst College
Box 2239, 31 Quadrangle Dr
Amherst, MA 01002-5000
https://www.amherst.edu/people/facstaff/nhorton
