### ISSUE TITLE
Reduce dependencies if possible

### ISSUE THREAD

**Issue by rpruim** [ProjectMOSAIC/mosaic#378]
There has been some discussion on R-devel regarding Depends/Imports/Suggests and some of the new checks that CRAN is performing.  In particular:

>Field ‘Depends’ should nowadays be used rarely, only for packages which are intended to be put on the search path to make their facilities available to the end user (and not to the package itself): for example it makes sense that a user of package latticeExtra would want the functions of package lattice made available.

We've already been moving in this direction, but could move more.  In particular, having `lattice` in depends probably makes sense, but `ggplot2` could move to imports.  `dplyr` is another case -- I think we need to do this to get `do()` and `tally()` to behave properly, but otherwise this could be avoided.

Anyway, as we prepare the next release, we should revisit this.

**Comment by rpruim** [comment]
Our current list is pretty small
```
Depends:
    R (>= 3.0.0),
    car,
    dplyr,
    lattice (>= 0.20-21),
    ggplot2
```
and all of those are pretty well established packages.  I'm inclined to leave as is for now.

**Comment by nicholasjhorton** [comment]
I'd like to add tidyr: besides gather and spread, it includes the ever so useful "extract_numeric()".

**Comment by znmeb** [comment]
@nicholasjhorton +1 for tidyr; given tidyr, dplyr and ggplot2 you have the RStudio data wrangling and data visualization cheatsheets covered - <http://www.rstudio.com/resources/cheatsheets/>

**Comment by rpruim** [comment]
I don't see that `tidyr` is tightly enough connected to the `mosaic` package to make it a dependency.  I think that's a case where we tell people to attach the package.

Hmm.  I wonder what CRAN would say if we made a package called `mosaicFavs` that just caused a bunch of other packages (including `mosaicData`) to be attached to the search path.

**Comment by nicholasjhorton** [comment]
I don't like the name, but I really like the idea.

Nick

> On May 15, 2015, at 7:12 AM, Randall Pruim <notifications@github.com> wrote:
> 
> Hmm. I wonder what CRAN would say if we made a package called mosaicFavs that just caused a bunch of other packages (including mosaicData) to be attached to the search path.

Nicholas Horton 
Professor of Statistics
Department of Mathematics and Statistics, Amherst College
Box 2239, 31 Quadrangle Dr
Amherst, MA 01002-5000
https://www.amherst.edu/people/facstaff/nhorton

**Comment by rpruim** [comment]
I've just noticed the `DESCRIPTION` file in `tigerstats` includes
```
Depends: R(>= 2.10), mosaic, mosaicData, abd
```
So perhaps we could get `mosaicData` in as a dependency.  Or perhaps `tigerstats` will get flack for doing so in the next iteration...

**Comment by rpruim** [comment]
We have reluctant permission to make `mosaicData` a dependency.  I'm still a bit torn, but I'm planning to do this, but I'll likely leave `require(mosaicData)` in various documents for now -- perhaps with a note that `mosaic` actually does this for you.  But it is good for people to know that they can get the data without using the `mosaic`package if they like.
