### ISSUE TITLE
example(antiD) is noisy

### ISSUE THREAD

**Issue by nicholasjhorton** [ProjectMOSAIC/mosaic#384]
I get the following when I run example(antiD) using R version 3.1.1:

Warning messages:
1: In .local(object, ...) :
  Implicit variables without default values (dangerous!):  A
2: In valVec[n] <- as.character(v) :
  number of items to replace is not a multiple of replacement length
3: In .local(object, ...) :
  Some default values taken from current environment:  a
4: In .local(object, ...) :
  Implicit variables without default values (dangerous!):  A
5: In valVec[n] <- as.character(v) :
  number of items to replace is not a multiple of replacement length
6: In .local(object, ...) :
  Some default values taken from current environment:  y

**Comment by rpruim** [comment]
The "implicit variables" warning can be removed by specifying default values for variables in functions created using `D()` and `anitD()`.  I've done this in all but one case; I've added a comment about the warning in that case.

I'm not seeing the other warnings.
