### ISSUE TITLE
cdata() should warn if proportion requested is too precise for amount of data supplied

### ISSUE THREAD

**Issue by rpruim** [ProjectMOSAIC/mosaic#390]

**Comment by rpruim** [comment]
What rule of thumb would we use for this?  The idea is that is a little silly to be estimating the central 95% of a distribution from a sample of size 10.  It seems like a comparison like
```r
(k / n) > p * (1-p)
```
could be used to trigger the warning for some constant `k`.  Not sure what constant `k` to use.  Is it even worth bothering with the error message?

(My idea is that  ` 0.5 * p * (1-p)` will be less than the tail probability, and we should want to expect some number of observations in the tails.  The larger `k` is, the more we expect to see in the tails.)

**Comment by nicholasjhorton** [comment]
I'd prefer to sweep this under the rug with a general sense that such calculations are tricky with small n (like Randy's advice to not calculate boxplots for samples with n=4).

Nick

**Comment by rpruim** [comment]
Consider this swept.
