### ISSUE TITLE
add xpbinom()?

### ISSUE THREAD

**Issue by nicholasjhorton** [ProjectMOSAIC/mosaic#417]

**Comment by rpruim** [comment]
What kind of plot would you prefer?  The current mechanism for the `xpdist()` functions is designed for continuous distributions, but we can likely expand it to handle discrete distributions, too.

**Comment by rpruim** [comment]
I've made a first attempt at extending pdist/qdist/etc to handle discrte distributions:

```r
> xpbinom( 50, size=100, prob=0.4)
[1] 0.983
```
Need to figure out white group coloring isn't working as I would like.

![image](https://cloud.githubusercontent.com/assets/722231/7547378/d7cea74a-f63f-11e4-95ab-79fefda0ac07.png)

**Comment by nicholasjhorton** [comment]
This looks good: thanks!

Nick

**Comment by rpruim** [comment]
But now it is better.

```r
> xpbinom( c(480, 500, 510), size=1000, prob=.48)
[1] 0.5127908 0.9027460 0.9731856
```
![image](https://cloud.githubusercontent.com/assets/722231/7576841/4068fb36-f896-11e4-8f60-aa632f4f7207.png)
```r
xpbinom( c(480, 500, 510), size=1000, prob=.48, lwd=3, vlwd=2)
```
![image](https://cloud.githubusercontent.com/assets/722231/7576875/87c82074-f896-11e4-84dd-943ea973282d.png)

**Comment by rpruim** [comment]
Added another little wrinkle.  When working with discrete distributions, the requested probabilities given to a q-function might not be (exactly possible).  The plot will report the actual probabilities of the quantiles returned.

```r
> xqpois( c(0.25, 0.5, 0.75), lambda=6, lwd=3, vlwd=2)
[1] 4 6 8
```
![image](https://cloud.githubusercontent.com/assets/722231/7576983/9caf2e32-f897-11e4-9624-ec312d49af7f.png)
