### ISSUE TITLE
simplify version numbering?

### ISSUE THREAD

**Issue by nicholasjhorton** [ProjectMOSAIC/mosaic#436]
We're presently at 0.9.3-1.99.  It's hard for me to explain to others what this means (or why we need five fields for versioning).  Can we try to move to a 4 or 3 level of versioning?  Just my $0.02,

Nick

**Comment by rpruim** [comment]
We discussed this when we introduced this numbering scheme.  The .99 indicates "beta".  CRAN releases will have numbers like 0.9.4 (or 0.9.4-x if we have to resubmit or do a light bug fix, etc.)

This is similar to the scheme Hadley is using and is primarily there to avoid having to renumber the beta branch perpetually.  In my ideal world, there would be something automatic for this and human intervention would only be needed to bump versions at higher than the last level.

Why are you trying to explain version numbers to people?

**Comment by rpruim** [comment]
Note:  Hadley has a new recommendation for version numbering:

> Add the .9000 suffix to the Version field in the DESCRIPTION to indicate that this is a development version. 

I'm happy to comply with Hadley's advice [here](http://r-pkgs.had.co.nz/description.html#version) and [here](http://r-pkgs.had.co.nz/release.html#release-version).

That would turn our version number into 0.9.3.9000 for now and 0.9.4 or 0.10.0 once released. 

The most important part is this:

 * The version number of your in-development package will have four components, major.minor.patch.dev, where dev is at least 9000. The number 9000 is arbitrary, but provides a strong visual signal there’s something different about this version number. Released packages don’t have a dev component, so now you need to drop that and pick a version number based on the changes you’ve made. For example, if the current version is 0.8.1.9000 will the next CRAN version be 0.8.2, 0.9.0 or 1.0.0? Use this advice to decide:

  * Increment patch, e.g. 0.8.2 for a patch: you’ve fixed bugs without adding any significant new features. I’ll often do a patch release if, after release, I discover a show-stopping bug that needs to be fixed ASAP. Most releases will have a patch number of 0.

   * Increment minor, e.g. 0.9.0, for a minor release. A minor release can include bug fixes, new features and changes in backward compatibility. This is the most common type of release. It’s perfectly fine to have so many minor releases that you need to use two (or even three!) digits, e.g. 1.17.0.

   * Increment major, e.g. 1.0.0, for a major release. This is best reserved for changes that are not backward compatible and that are likely to affect many users. Going from 0.b.c to 1.0.0 typically indicates that your package is feature complete with a stable API.

**Comment by znmeb** [comment]
I haven't seen that but I'm sort of a fan of "semantic versioning". See <http://semver.org/>.
