### ISSUE TITLE
move mosaic package to ProjectMOSAIC organization?

### ISSUE THREAD

**Issue by rpruim** [ProjectMOSAIC/mosaic#437]
The main side effects of this would be:

 * github installation would be `install_github("ProjectMOSAIC/mosaic")`
 * Project MOSAIC as a project would be a bit more visible
 * It would be consistent with moving other github stuff to this organization (rather than having it owned by one or the other of us individually).

The only downside I see is that some people might try to install with `install_github("rpruim/mosaic")`.  But this should be a brief transitional disturbance.

**Comment by znmeb** [comment]
Fine with me - I'd just have to change one line of code.

**Comment by rpruim** [comment]
This has happened.  Note this from the github help pages regarding transferring repositories:

> When a repository is transferred, all links to the previous location are automatically redirected to the new location.

> In addition to redirecting web traffic, all git clone, git fetch, or git push operations targeting the previous location will continue to function as if made on the new location. 

This is good and should mean that `rpruim/mosaic` will continue to function.  But note the following:

> **However, this can be somewhat confusing, so we strongly recommend updating any existing local clones to point to the new repository URL.** You can do this by using git remote on the command line:

```
git remote set-url origin new_url
```
For more information, see "Changing a Remote's URL".

**Comment by rpruim** [comment]
Here's a log from my update of the repository URL:
```
$ git remote -v
origin	git@github.com:rpruim/mosaic.git (fetch)
origin	git@github.com:rpruim/mosaic.git (push)

$ git remote set-url origin git@github.com:ProjectMOSAIC/mosaic.git

$ git remote -v
origin	git@github.com:ProjectMOSAIC/mosaic.git (fetch)
origin	git@github.com:ProjectMOSAIC/mosaic.git (push)
```

**Comment by znmeb** [comment]
Will the mosaicData package move too? Is it still required / imported?

**Comment by rpruim** [comment]
It will be moving as well and will remain in imports (not depends or suggests) for the foreseeable future.
