### ISSUE TITLE
convert NEWS.Rd to NEWS.md

### ISSUE THREAD

**Issue by rpruim** [ProjectMOSAIC/mosaic#446]
I hate editing the `NEWS.Rd` file.  Hadley recommends using `NEWS.md` -- even though it is not supported by CRAN.  I'm leaning in that direction as well.

Presumably one ought to be able to convert `NEWS.md` to `NEWS.Rd`, but I have located a tool to do this for us.

**Comment by znmeb** [comment]
Can roxygen be tricked into doing that for you? It makes Rd from comments in R source / R notebooks. roxygen could stand some better documentation, though - I've had to piece together files by reading examples rather than having a documented API to work with.

**Comment by rpruim** [comment]
I don't think this is a job for `roxygen2`.  Have you looked at [Hadley's R packages "book"](http://r-pkgs.had.co.nz/man.html).  It has a section on documenting objects with and without `roxygen2`.

**Comment by znmeb** [comment]
I haven't read that recently - I don't have anything that big yet.

**Comment by rpruim** [comment]
I don't think you need to wait for a package to get big to benefit from it.  Simply read the portions that are appropriate for the things in your package.  Lots of good advice about planning and implementing a package as well as useful features in the `devtools` package that simplify the life of the package maintainer.

**Comment by rpruim** [comment]
Conversion is complete.  I little regular expression magic in vim and it was pretty easily done.  Much nicer to update this file than the old Rd file.
