### ISSUE TITLE
problems with derivedFactor()?

### ISSUE THREAD

**Issue by nicholasjhorton** [ProjectMOSAIC/mosaic#451]
Am I doing something wrong?

> x <- c(0, 0, 1, 1, NA)
> x2 <- derivedFactor(zero = x==0, nonzero = x==1)
Warning messages:
1: In .Primitive("max")(evalF$right[, 1], ...) :
  no non-missing arguments to max; returning -Inf
2: In .Primitive("min")(evalF$right[, 1], ...) :
  no non-missing arguments to min; returning Inf

**Comment by rpruim** [comment]
The value of `x2` is what you want it to be (I think), but the NA is causing `min()` and `max()` to throw warnings.  I'll see if it is possible to avoid the warnings.

**Comment by rpruim** [comment]
Warnings have been expunged.
```r
x <- c(0, 0, 1, 1, NA)
derivedFactor(zero = x==0, nonzero = x==1)
## [1] zero    zero    nonzero nonzero <NA>   
## Levels: zero nonzero
```
