### ISSUE TITLE
Possible different use of branches, tags, and install_github()

### ISSUE THREAD

**Issue by rpruim** [ProjectMOSAIC/mosaic#457]
I'm wondering if we should slightly modify how we do this.

 * tag CRAN releases with version tags like v0.10.0
 * move things from `beta` into `master` more frequently.  The github `master` should be a stable, "better than CRAN" version that can be installed with `install_github("ProjectMOSAIC/mosaic")`. 
 * still use the `beta` branch (or other branches) for things we are working on.  The beta branch might not be as ready-for-common-consumption as the master branch, but we can use it to let people easily test things (and easily revert back to the github `master` version, if they want).

In particular, I'm not sure there is a reason to pull the CRAN release from github by default.  There are simple enough ways to get the CRAN release from CRAN.  But we do want the master branch to contain a version that we are quite confidence works well -- and we should fix bugs rapidly should they be discovered. 

If there are no objections, I'm going to being moving in this direction.  In particular, I'll put a pre-release of the upcoming CRAN submission into master before I submit to CRAN.

**Comment by znmeb** [comment]
Sounds good to me.

**Comment by rpruim** [comment]
I've merged beta into master and pushed to github.  master is now a prerelease of version 0.10.

**Comment by rpruim** [comment]
Also updated the README a bit to reflect this change.
