### ISSUE TITLE
Produce a better error message when favstats() is used with categorical data

### ISSUE THREAD

**Issue by rpruim** [ProjectMOSAIC/mosaic#458]
Currently we have
```r
favstats(~sex, data=HELPrct)
## Error in maggregate(na.rm = na.rm, formula = ~(x), data = <environment>, : object 'na.rm' not found
```

**Comment by rpruim** [comment]
We should create similar issue for other cases where we could be more user friendly.

**Comment by rpruim** [comment]
This looks better:
```r
favstats(~sex, data=HELPrct)
## Warning in (function (x, ..., na.rm = TRUE) : Auto-converting factor to numeric.
##  min Q1 median Q3 max     mean       sd   n missing
##    1  2      2  2   2 1.763797 0.425218 453       0
```
**Note:** This change involved adding `stringsAsFactors = FALSE` to a `data.frame()` call in a function that gets used internally for a lot of aggregating functions.  This means that some behaviors will change because character vectors will not auto-promote to factors.

**Comment by nicholasjhorton** [comment]
Randy,

Thanks.  

The warning is really important (and looks eminently reasonable).

Nick
