### ISSUE TITLE
update README to include links to vignettes, and additional info

### ISSUE THREAD

**Issue by rpruim** [ProjectMOSAIC/mosaic#465]
This will give people landing at the mosaic github repo a place to get started and also give us a link we can share with others that doesn't require installing the mosaic package or waiting for CRAN updates.

**Comment by rpruim** [comment]
Github renders the Rmd files reasonably well, so we can link to those.  I'm going to store the PDFs of the Rnw vignettes in the repo so we have a link to built versions of those as well.

**Comment by znmeb** [comment]
The only gotcha I've found with using an Rmd for a README is that GitHub renders the YAML front matter as a table before the document. If you don't have YAML front matter or put it in an _output.yaml file that won't happen.

**Comment by rpruim** [comment]
Using `_output.yaml` is a good trick for getting rid of the YAML stuff at the top.

**Comment by rpruim** [comment]
But I'm not sure it will work for the vignettes since we have multiple vignettes and they require some information in the YAML section that is not the same.  But we can use the `_output.yaml' trick elsewhere.
