### ISSUE TITLE
Add Open Intro Statistics mosaic labs to mosaic resources?

### ISSUE THREAD

**Issue by nicholasjhorton** [ProjectMOSAIC/mosaic#468]
These may be useful for users of the mosaic package: https://www.openintro.org/stat/labs.php

Just a thought,

Nick

**Comment by rpruim** [comment]
Can do.  Do you want to compose a 1-2 sentence description?  Else I'll just say "OpenIntro Stats now has version of their text designed for use with the `mosaic` package."

**Comment by nicholasjhorton** [comment]
I'd suggest changing "text" to "labs".

Nick

> On May 20, 2015, at 7:46 PM, Randall Pruim <notifications@github.com> wrote:
> 
> Can do. Do you want to compose a 1-2 sentence description? Else I'll just say "OpenIntro Stats now has version of their text designed for use with the mosaic package."
> 
> —
> Reply to this email directly or view it on GitHub.
> 

Nicholas Horton 
Professor of Statistics
Department of Mathematics and Statistics, Amherst College
Box 2239, 31 Quadrangle Dr
Amherst, MA 01002-5000
https://www.amherst.edu/people/facstaff/nhorton
