### ISSUE TITLE
Create new package (fetch) and move data fetching code there.

### ISSUE THREAD

**Issue by rpruim** [ProjectMOSAIC/mosaic#473]
This is related to issues #364, #209, #199, and #405.

I've created the github repository and put `fetchData()`, `fetchGapminder()` and `fetchGoogle()` into it.  These three functions will be removed from `mosaic` at its next release.

We could also consider moving `CIAdata()` (perhaps as `fetchFactbook()`) and/or `read.file()`.

**Comment by rpruim** [comment]
These are all defunct in the beta branch.  Development should move to the `fetch` package.
```r
> fetchData()
Error: Use 'fetchData' from the fetch package instead.
> fetchGoogle()
Error: Use 'fetchGoogle' from the fetch package instead. Or see the `googlesheets' package.
> fetchGapminder()
Error: Use 'fetchGapminder' from the fetch package instead.
```

**Comment by nicholasjhorton** [comment]
I would prefer not to move CIAdata(): either it should be cleaned up and kept in mosaic (which we describe as general "utilities used to teach mathematics, statistics, computation and modeling") or deprecated.

**Comment by rpruim** [comment]
Do you think it is useful?  If so, I think it belongs in a package that focuses on retrieving data, not in mosaic.  Deprecation means it will go away for good.

**Comment by nicholasjhorton** [comment]
I think that it could be very useful, particularly if a short vignette could be created.

Could we find a time to talk more generally about lingering issues with the package (more big picture)?

Just a thought,

Nick

**Comment by rpruim** [comment]
I probably have more time than you this week.  Happy to chat.

**Comment by znmeb** [comment]
you might want to call the new package "mosaicFetch" rather than just "fetch".

**Comment by rpruim** [comment]
The `fetch` package has been created and I've moved a number of issues from here to there.

It's not too late to consider a name change, but I'm going to leave it `fetch` for the moment.

**Comment by rpruim** [comment]
For future reference, this is how I ported the issues over:

[https://github-issue-mover.appspot.com/](https://github-issue-mover.appspot.com/)
