### ISSUE TITLE
Add another plot type (line plot) to mPlot()

### ISSUE THREAD

**Issue by rpruim** [ProjectMOSAIC/mosaic#483]
Nice for time series, etc.  Use `type="l"` in lattice and `geom_line()` in ggplot2.

**Comment by nicholasjhorton** [comment]
Thanks!

Nick

> On Jun 23, 2015, at 6:46 AM, Randall Pruim <notifications@github.com> wrote:
> 
> Nice for time series, etc. Use type="l" in lattice and geom_line() in ggplot2.
> 
> —
> Reply to this email directly or view it on GitHub.
> 

Nicholas Horton 
Professor of Statistics
Department of Mathematics and Statistics, Amherst College
Box 2239, 31 Quadrangle Dr
Amherst, MA 01002-5000
https://www.amherst.edu/people/facstaff/nhorton

**Comment by rpruim** [comment]
Looks like this is working.

![image](https://cloud.githubusercontent.com/assets/722231/8322862/2c653408-1a90-11e5-9a53-dec24bc5f1e6.png)
