### ISSUE TITLE
Create ashplot()

### ISSUE THREAD

**Issue by rpruim** [ProjectMOSAIC/mosaic#485]
ASH = Average Shifted Histogram.  These look like density plots (and are in fact density plots with a triangle kernel).

```{r}
> example(ashplot)

ashplt> ashplot( ~age | substance, groups = sex, data = HELPrct)
```
![image](https://cloud.githubusercontent.com/assets/722231/8368560/0868870a-1c00-11e5-8ce0-d06d54674fe7.png)

**Comment by nicholasjhorton** [comment]
I have no objection (but wouldn't give it much priority).

**Comment by rpruim** [comment]
The documentation is light.  Perhaps we could add a reference.  But I'm closing for now.
