### ISSUE TITLE
Should t.test support 2 formulas?

### ISSUE THREAD

**Issue by rpruim** [ProjectMOSAIC/mosaic#504]
Email from Bob Milnikel:

> I'm finding that

```r
t.test(~Chocolate.Milk, ~Carbohydrate.Replacement, data = ex1124)
```
> performs a one-sample test on the first column, whereas

```r
t.test(ex1124$Chocolate.Milk, ex1124$Carbohydrate.Replacement)
```

> performs the two-sample test.  (I also get an error if I try the former with "paired = TRUE", which is I'm sure the same issue in a different guise.)

**Comment by rpruim** [comment]
Some thoughts.

 1.  I’m not sure we want to support the implied request, and here’s why:  I think that that is the wrong way to arrange the data and the wrong way to think about the 2-sample t test.  I much prefer to think of this as data with a quantitative response to a categorical predictor, which which case `t.test( response ~ group, data = mydata)` is the natural way to perform the test and a better way to arrange the data.

 2. One potential argument for the syntax you are looking for is that it might be nice to be able to easily compare a (wrong) 2-sample t to the (correct) paired t.  But I’m still not convinced that it wouldn’t be better to transform the data using `tidyr` instead.

 3. Even if we don’t support this, we might consider emitting a warning or error message when what you’ve done is attempted to alert the user.

**Comment by dtkaplan** [comment]
I certainly agree with (1).  Perhaps add something like this to the
documentation ...

Often, data is arranged with the paired values in two different variables.
This is an intuitive way to describe a pairing, and is the arrangement used
in "traditional interface" of the built-in t-test (that is, the function
t.test() in the stats package).

To illustrate, your data might look like:
```
example_data <- data.frame(before = rnorm(10), after = runif(10) )
```

The t-test in the traditional interface would be run
```
t.test(example_data$before, example_data$after)
```
Add the argument `paired=TRUE` to make a paired test.

The mosaic function mosaic::t.test(), like other mosaic functions, uses a
"formula" interface.  This requires two variables, one with the value and
the other with the group.  To convert the example data into a suitable
form, use a statement like this:
```
proper_form <-
  example_data %>%
  mutate(case_id = row.names(.)) %>%
  gather(key="when", value="voltage", before, after)
```

Now you can use the mosaic function to perform the paired or the unpaired
t-test, like this
```
t.test(voltage ~ when, data=proper_form)
t.test(voltage ~ when, data=proper_form, paired = TRUE )
```

Some advantages to using a proper form:
* works with mosaic functions
* works with unpaired tests even when they don't have groups of the same
size
* generalizes better

This last point may seem obscure if all you are thinking of is a paired
t-test.  But, suppose you want to treat the t-test as the special case of
one-way ANOVA with just two groups.  It's nice to show that these two tests
give identical results
```{r}
t.test(voltage ~ when, data=proper_form)
anova(lm(voltage ~ when, data=proper_form))
```
As for the paired t.test, this is equivalent to adding a covariate
identifying the pairs, e.g.
```{r}
t.test(voltage ~ when, data=proper_form, paired=TRUE)
anova(lm(voltage ~ when + case_number, data=proper_form))
```
The ANOVA here will handle more general repeated measures.



On Mon, Aug 17, 2015 at 9:37 AM, Randall Pruim <notifications@github.com>
wrote:

> Some thoughts.
>
>    1.
>
>    I’m not sure we want to support the implied request, and here’s why: I
>    think that that is the wrong way to arrange the data and the wrong way to
>    think about the 2-sample t test. I much prefer to think of this as data
>    with a quantitative response to a categorical predictor, which which case t.test(
>    response ~ group, data = mydata) is the natural way to perform the
>    test and a better way to arrange the data.
>    2.
>
>    One potential argument for the syntax you are looking for is that it
>    might be nice to be able to easily compare a (wrong) 2-sample t to the
>    (correct) paired t. But I’m still not convinced that it wouldn’t be better
>    to transform the data using tidyr instead.
>    3.
>
>    Even if we don’t support this, we might consider emitting a warning or
>    error message when what you’ve done is attempted to alert the user.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ProjectMOSAIC/mosaic/issues/504#issuecomment-131843315>
> .
>



-- 

...

DeWitt Wallace Professor of Mathematics, Statistics, and Computer Science
Macalester College

NEWS: Our new Data Science minor has been approved and is open to students
in the class of 2016 and later.  Come find out more!

**Comment by rpruim** [comment]
I'm going to leave this as is for now.  There are other ways to address the issue and other things that are higher priority.
