### ISSUE TITLE
Naming of results of do() -- edge cases

### ISSUE THREAD

**Issue by rpruim** [ProjectMOSAIC/mosaic#522]
As of issue #472 we are naming unnamed values based on the expression used.  Mostly this is good.

```r
> do(3) * foo()
  foo
1   5
2   5
3   5
```

Here's one case where the name could be better:

```r
> do(3) * HELPrct %>% foo()
  %>%
1   5
2   5
3   5
```

If that is the only unfortunate edge case, I think we can handle it as a special case.  Are there are other edge cases we want/need to deal with?

**Comment by rpruim** [comment]
This is a funky case too, but I'm not sure it is a case that is likely to arise in practice:

```r
> do (3) * (5 + 2)
  (
1 7
2 7
3 7
```

But perhaps this can be rewritten using logic like "if the name is 'nice enough', use it, else rename it to `"result"`."  Just have to figure out a good definition for 'nice enough'.

**Comment by dtkaplan** [comment]
Requiring on character [a-zA-Z] might be good enough for nice enough.

-Danny

On Mon, Sep 14, 2015 at 6:57 AM, Randall Pruim <notifications@github.com>
wrote:

> This is a funky case too, but I'm not sure it is a case that is likely to
> arise in practice:
>
> > do (3) * (5 + 2)
>   (1 72 73 7
>
> But perhaps this can be rewritten using logic like "if the name is 'nice
> enough', use it, else rename it to "result"." Just have to figure out a
> good definition for 'nice enough'.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ProjectMOSAIC/mosaic/issues/522#issuecomment-140048795>
> .
>



-- 

...

DeWitt Wallace Professor of Mathematics, Statistics, and Computer Science
Macalester College

NEWS: Our new Data Science minor has been approved and is open to students
in the class of 2016 and later.  Come find out more!

**Comment by nicholasjhorton** [comment]
I would like to advocate that we leave the naming as it was.

In the interim, I'm going to start adding:

names(res)

for any object called "res" that gets assigned from the output of "do()".  

That way if our naming changes in the future, people reading our books will have the tools to see what names are returned.

Sound reasonable?

Nick

> On Sep 14, 2015, at 9:15 AM, Daniel Kaplan <notifications@github.com> wrote:
> 
> Requiring on character [a-zA-Z] might be good enough for nice enough.
> 
> -Danny
> 
> On Mon, Sep 14, 2015 at 6:57 AM, Randall Pruim <notifications@github.com>
> wrote:
> 
> > This is a funky case too, but I'm not sure it is a case that is likely to
> > arise in practice:
> >
> > > do (3) * (5 + 2)
> > (1 72 73 7
> >
> > But perhaps this can be rewritten using logic like "if the name is 'nice
> > enough', use it, else rename it to "result"." Just have to figure out a
> > good definition for 'nice enough'.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/ProjectMOSAIC/mosaic/issues/522#issuecomment-140048795>
> > .
> >
> 
> 
> 
> -- 
> 
> ...
> 
> DeWitt Wallace Professor of Mathematics, Statistics, and Computer Science
> Macalester College
> 
> NEWS: Our new Data Science minor has been approved and is open to students
> in the class of 2016 and later. Come find out more!
> —
> Reply to this email directly or view it on GitHub.
> 

Nicholas Horton 
Professor of Statistics
Department of Mathematics and Statistics, Amherst College
Box 2239, 31 Quadrangle Dr
Amherst, MA 01002-5000
https://www.amherst.edu/people/facstaff/nhorton

**Comment by rpruim** [comment]
I usually use `head()` rather than `names()`.

Should we have `do()` return a tbl_df instead of a plane vanilla data frame?

**Comment by rpruim** [comment]
If you do
```r
do(3) * <whatever>
```
First, that also works.  I often do this -- especially when working interactively.

**Comment by rpruim** [comment]
I've updated `nice_names()` to convert `%>%` to `.result.` and I'm now checking to see whether `nice_names()` changes the auto-generated name.  If it does, I revert to `"result"`.  This seems like a reasonable compromise.

```r
foo
## function(...) 5
do(3) * foo()
##   foo
## 1   5
## 2   5
## 3   5
do(3) * HELPrct %>% foo()
##   result
## 1      5
## 2      5
## 3      5
do(3) * (5 + 3)
##   result
## 1      8
## 2      8
## 3      8
do(3) * 5
##   result
## 1      5
## 2      5
## 3      5
```

**Comment by nicholasjhorton** [comment]
Pedagogically I'm not wild about having foo() be the name of a function and foo also being a variable in a data frame. This seems to cause me confusion. 

All the best,

Nick

**Comment by rpruim** [comment]
I like naming functions after what they do or produce, and I like the result of `do()` to record this information for me.  So I like the current behavior.

I'd like to see use cases where (a) you have used a well written and well named function, and (b) you don't like having things named after the function.  Note: If you give your return value a name, that will be kept, so that is another option that gives you complete control when you are writing your own function.

```r
do(3) * mean(~age, data = resample(HELPrct))
##       mean
## 1 36.40177
## 2 35.73289
## 3 35.28035
foo <- function(x) c(my_result = mean(x))
do(3) * foo( resample(1:100) )
##   my_result
## 1     50.41
## 2     47.68
## 3     47.62
```
The use of a generic name like "result" has always bothered me.  I like the examples above much better.

**Comment by nicholasjhorton** [comment]
Randy,

Thanks for this: I will adopt it as a way to control the naming.

Knowing this I'm happy to move in the direction that you suggest (and have implemented).

Nick

**Comment by rpruim** [comment]
OK.  But do let us know if you find examples that don't work for you.

**Comment by beanumber** [comment]
This one isn't good:
```
> null.dist <- do(5000) * tally(~ outcome + shuffle(treatment), data = Mites)[2,1]
> head(null.dist)
   [
1 16
2 14
3 16
4 14
5 17
6 13
```

**Comment by rpruim** [comment]
I'm going to wrap the renaming I do to eliminate things like "shuffle" and "resample" with `make.names()` which will guarantee syntactically viable names.  Testing against this will convert things to result whenever that name would have been syntactically unviable.

```r
null.dist <- do(5000) * tally(~ outcome + shuffle(treatment), data = Mites)[2,1]
head(null.dist)
##   result
## 1     17
## 2     15
## 3     14
## 4     14
## 5     14
## 6     16
```

**Comment by rpruim** [comment]
Follow up on the example above.  Why not generate all the values in the null distribution and use variable names?  [2,1] is pretty cryptic.

```r
> do(1) * tally(~ outcome + treatment, data = Mites)
  no.wilt.mites wilt.mites no.wilt.no.mites wilt.no.mites
1            15         11                4            17
> do(1) * tally(~ outcome + treatment, data = Mites)[1,2]
  result
1      4
```

**Comment by nicholasjhorton** [comment]
That's a great suggestion.

Nick

> On Oct 6, 2015, at 11:29 AM, Randall Pruim <notifications@github.com> wrote:
> 
> Follow up on the example above. Why not generate all the values in the null distribution and use variable names? [2,1] is pretty cryptic.
> 
> > do(1) * tally(~ outcome + treatment, data = Mites
> )
>   
> no.wilt.mites wilt.mites no.wilt.no.mites wilt.no.mites
> 1            15         11                4            17
> > do(1) * tally(~ outcome + treatment, data = Mites)[1,2
> ]
>   
> result
> 1      4
> —
> Reply to this email directly or view it on GitHub.
> 

Nicholas Horton 
Professor of Statistics
Department of Mathematics and Statistics, Amherst College
Box 2239, 31 Quadrangle Dr
Amherst, MA 01002-5000
https://www.amherst.edu/people/facstaff/nhorton

**Comment by nicholasjhorton** [comment]
I had one question: If the function returns a named argument (e.g. return(result=result)) will the returned value still be called "result"?

Nick

> On Oct 6, 2015, at 10:45 AM, Randall Pruim <notifications@github.com> wrote:
> 
> I'm going to wrap the renaming I do to eliminate things like "shuffle" and "resample" with make.names() which will guarantee syntactically viable names. Testing against this will convert things to result whenever that name would have been syntactically unviable.
> 
> null.dist <- do(5000) * tally(~ outcome + shuffle(treatment), data = Mites)[2,1
> ]
> head(
> null.dist
> )
> 
> ##   result
> ## 1     17
> ## 2     15
> ## 3     14
> ## 4     14
> ## 5     14
> ## 6     16
> —
> Reply to this email directly or view it on GitHub.
> 

Nicholas Horton 
Professor of Statistics
Department of Mathematics and Statistics, Amherst College
Box 2239, 31 Quadrangle Dr
Amherst, MA 01002-5000
https://www.amherst.edu/people/facstaff/nhorton

**Comment by rpruim** [comment]
@nicholasjhorton, your question has "result" in 3 places and functions don't return arguments, so I'm not exactly sure what you are asking.

If it is not answered via this example (repeated from above), let me know.
```r
foo <- function(x) c(my_result = mean(x))
do(3) * foo( resample(1:100) )
##   my_result
## 1     50.41
## 2     47.68
## 3     47.62
```

**Comment by nicholasjhorton** [comment]
This is good behavior, in my opinion.

Nick

> On Oct 7, 2015, at 9:31 AM, Randall Pruim <notifications@github.com> wrote:
> 
> @nicholasjhorton, your question has "result" in 3 places and functions don't return arguments, so I'm not exactly sure what you are asking.
> 
> If it is not answered via this example (repeated from above), let me know.
> 
> foo <- function(x) c(my_result = mean(x
> ))
> do(
> 3) * foo( resample(1:100
> ) )
> 
> ##   my_result
> ## 1     50.41
> ## 2     47.68
> ## 3     47.62
> —
> Reply to this email directly or view it on GitHub.
> 

Nicholas Horton 
Professor of Statistics
Department of Mathematics and Statistics, Amherst College
Box 2239, 31 Quadrangle Dr
Amherst, MA 01002-5000
https://www.amherst.edu/people/facstaff/nhorton

**Comment by rpruim** [comment]
I'm closing this.  But note that there may be some subtle differences in names of things due to the move to using `make.names()`.  This is probably a good thing since it means the naming conventions will be largely familiar to people from elsewhere, for example in `data.frame()`.
