### ISSUE TITLE
bug/feature in xpbinom() regarding range displayed.

### ISSUE THREAD

**Issue by rpruim** [ProjectMOSAIC/mosaic#523]
@nicholasjhorton notes that

```r
xpbinom(4, size=10, prob=0.4)
```
doesn't display the probability for 10, and asks: is this a bug?

**Comment by rpruim** [comment]
It’s a feature in the sense that it is working as I intended.  But we could tweak the behavior.

The problem is this guy:

```r
xpgeom(4, size=10, prob=0.4)
```
We can’t go “forever”, so we need a heuristic to handle non-finite supports.  The heuristic is to show the middle 99.8% of the distribution
```{r}
    if (missing(xlim) || is.null(xlim)) {
        xlim <- dpqrdist(dist, type = "q", p = c(0.001, 0.999), 
            ...)
    }
```
 This avoid errors when the support is not finite and displays "most" of the distribution.  Note that 
```r
dbinom(10, 10, .4)
## [1] 0.0001048576
```

We could modify this behavior to check whether `qdist(1)` is `Inf` and `qdist(0) = -Inf`.  If not, we could “go all the way”.  But there might actually be cases where this is worse.  Typically those tails have such low probability that they are not visible in the plot anyway.

Thoughts?

PS.  You an manually set the limits with `xlim = `

**Comment by nicholasjhorton** [comment]
How about adding an example that demonstrates this?  (I know that there are a lot there already but suspect that this could be insinuated in somewhere.)

Nick

P.S. Good gaudy colors on some of the examples: that's a happy thing!

> On Sep 19, 2015, at 4:28 PM, Randall Pruim <notifications@github.com> wrote:
> 
> It’s a feature in the sense that it is working as I intended. But we could tweak the behavior.
> 
> The problem is this guy:
> 
> xpgeom(4, size=10, prob=0.4)
> We can’t go “forever”, so we need a heuristic to handle non-finite supports. The heuristic is to show the middle 99.8% of the distribution
> 
>     if (missing(xlim) || is.null(xlim
> )) {
>         
> xlim <- dpqrdist(dist, type = "q", p = c(0.001, 0.999
> ), 
>             
> ...
> )
>     }
> 
> This avoid errors when the support is not finite and displays "most" of the distribution. Note that
> 
> dbinom(10, 10, .4
> )
> 
> ## [1] 0.0001048576
> We could modify this behavior to check whether qdist(1) is Inf and qdist(0) = -Inf. If not, we could “go all the way”. But there might actually be cases where this is worse. Typically those tails have such low probability that they are not visible in the plot anyway.
> 
> Thoughts?
> 
> PS. You an manually set the limits with xlim =
> 
> —
> Reply to this email directly or view it on GitHub.
> 

Nicholas Horton 
Professor of Statistics
Department of Mathematics and Statistics, Amherst College
Box 2239, 31 Quadrangle Dr
Amherst, MA 01002-5000
https://www.amherst.edu/people/facstaff/nhorton

**Comment by rpruim** [comment]
The colors depend on the theme and I don't like to mess with people's theme in the examples.  Glad you like the gaudy defaults.

I've decided to leave the behavior essentially as is.  Documentation has been updated a bit.  Also, I've widened things by half a tick on each side so that the last value of the discrete dists don't end up right on the edge of the plot.
