### ISSUE TITLE
group_mod() and MPSE()

### ISSUE THREAD

**Issue by nicholasjhorton** [ProjectMOSAIC/mosaic#527]
@dtkaplan, I really like the group_mod() and MPSE() functions: is there any way that they could be incorporated into the mosaic package?

**Comment by rpruim** [comment]
Danny and I worked on this today.  Here's the plan:

 * deprecate `mm()`
 * rename `group_mod()` -- currently using `gwm()`
 * bring functionality from `mm()` into `gwm()` and by creating the necessary methods

**Comment by rpruim** [comment]
I've pushed a first version of this to github in the beta branch.  CRAN checking isn't quite clean yet, but the most important things are in place.

**Comment by nicholasjhorton** [comment]
Any chance that these changes can be woven into Danny's CHANCE manuscript?

All the best,

Nick

**Comment by rpruim** [comment]
That's the plan.  But it would be good to think about other use cases for these functions since I'm not a fan of introducing functions that exist only to do a single example.  This is why I wanted to bring `mm()` functionality into `gwm()` rather than have them co-exist.

**Comment by dtkaplan** [comment]
Yes, I'm going to work the functions in mosaic/beta into the article.  That
way, all the software in the Chance article will be mosaic.

On Sat, Sep 26, 2015 at 8:55 AM, Randall Pruim <notifications@github.com>
wrote:

> That's the plan. But it would be good to think about other use cases for
> these functions since I'm not a fan of introducing functions that exist
> only to do a single example. This is why I wanted to bring mm()
> functionality into gwm() rather than have them co-exist.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ProjectMOSAIC/mosaic/issues/527#issuecomment-143444713>
> .
>



-- 

...

DeWitt Wallace Professor of Mathematics, Statistics, and Computer Science
Macalester College
