### ISSUE TITLE
Should aggregating functions support non-data.frame tbls?

### ISSUE THREAD

**Issue by rpruim** [ProjectMOSAIC/mosaic#528]
Nick wants to know if this is on our wish list.

**Comment by rpruim** [comment]
Nick's example
```r
library(mosaic)
library(RMySQL)
db <- src_mysql(host="scidb.smith.edu", user="mth292", password="RememberPi", dbname="airlines")
flights <- tbl(db, "flights")
oneday <-
  flights %>%
  filter(month==5, day==31, year==2015, dest=="BDL")
  favstats(~ arr_delay, data=data.frame(oneday))

## min    Q1 median   Q3 max     mean       sd  n missing
##  -19 -8.25    0.5 38.5 262 25.26667 54.55766 60       1

favstats(~ arr_delay, data=oneday)

## Error in eval(expr, envir, enclos) : object 'arr_delay' not found
```

**Comment by rpruim** [comment]
The are two ways I can imagine approaching this:

1) cast the `data` argument to a data frame.

This will be unbelievably expensive if used improperly and likely require people to terminate their R sessions to recover.

2) Remplement the internals of `maggreagate()` using `dplyr`.

Some of this already happens when you set `.format = "table"`, but a full implementation would be no trivial for reasons illustrated here:

```r
oneday %>% group_by(carrier) %>% summarise( m = mean(arr_delay))
## Source: mysql 5.5.44-0ubuntu0.14.04.1 [mth292@scidb.smith.edu:/airlines]
## From: <derived table> [?? x 2]
## 
##    carrier       m
##      (chr)   (dbl)
## 1       AA 55.7500
## 2       B6 12.1111
## 3       DL 25.4667
## 4       EV 17.3333
## 5       OO 25.2500
## 6       UA 64.0000
## 7       US  4.0000
## 8       WN 26.5789
## ..     ...     ...
## Warning message:
## In .local(conn, statement, ...) :
##   Decimal MySQL column 1 imported as numeric

Mean <- mean
oneday %>% group_by(carrier) %>% summarise( m = Mean(arr_delay))
## Source: mysql 5.5.44-0ubuntu0.14.04.1 [mth292@scidb.smith.edu:/airlines]
## From: <derived table> [?? x 2]
## 
## Error in .local(conn, statement, ...) : 
##   could not run statement: FUNCTION airlines.MEAN does not exist
```

Only certain functions can be applied to data inside the data base.  Even a simple renaming of the mean function causes this to break.  And functions not in the special list will also fail:

```r
oneday %>% group_by(carrier) %>% summarise( m = median(arr_delay))
## Source: mysql 5.5.44-0ubuntu0.14.04.1 [mth292@scidb.smith.edu:/airlines]
## From: <derived table> [?? x 2]
## 
## Error in .local(conn, statement, ...) : 
##   could not run statement: FUNCTION airlines.MEDIAN does not exist
```
So some of the functions we want can't be done inside the data base, leaving only expensive solutions.

I'm inclined to say that `dplyr` is a different use case and to have people cast the results of a query to a data frame or tbl_df when this is sensible to do.

**Comment by beanumber** [comment]
What about writing a `favstats.tbl` helper function that does this:
```
favstats(~ arr_delay, data=collect(oneday))
```
that would at least solve Nick's problem, even though I see that it doesn't solve the bigger, underlying problem.

**Comment by rpruim** [comment]
first of all, the first argument is a formula, not a tbl, so S3 generics won't work here.  Second, this is a really bad idea if you use `flights` in place of `oneday`.  Better to teach about `collect()` than make it too easy for users to do bad things.

I only see real value in this if the computation can be pushed out into the data base.  We could perhaps create a version of `favstats()` that does this, but we might also need to change which numerical summaries are computed.

**Comment by beanumber** [comment]
> first of all, the first argument is a formula, not a tbl, so S3 generics won't work here.

That's why I said "helper function" instead of `method` :)

In Nick's case, could you catch the error if the data argument is a `tbl` and give a more constructive error message? 

I don't think you can compute medians and quantiles on the fly in MySQL, but I think you can in PostgreSQL using the [window functions](http://www.postgresql.org/docs/9.4/static/tutorial-window.html).

**Comment by nicholasjhorton** [comment]
I'm not necessarily advocating for a technological solution: perhaps a different error message from the mosaic aggregation functions or a description of a pedagogical approach to move people from basic operations with data frames to more sophisticated data wrangling with tbls would do the trick for me.

I've been burned a couple of times using non-dplyr compliant functions with some data management operations and suspect that this is a more general problem.

Perhaps @hadley might have some insights (or a pointer to writings or other github issues that address this).

Just my $0.02,

Nick

> On Oct 6, 2015, at 2:13 PM, Randall Pruim <notifications@github.com> wrote:
> 
> Nick wants to know if this is on our wish list.
> 
> 

Nicholas Horton 
Professor of Statistics
Department of Mathematics and Statistics, Amherst College
Box 2239, 31 Quadrangle Dr
Amherst, MA 01002-5000
https://www.amherst.edu/people/facstaff/nhorton

**Comment by rpruim** [comment]
Something like this?
```r
favstats( arr_delay ~ carrier, data=oneday)
## Error: Your tbl is not a data.frame.  Perhaps you need dplyr functions here.
favstats( arr_delay ~ carrier, data=17)
## Error: data must be an environment or data.frame.
```

**Comment by nicholasjhorton** [comment]
That's what I had in mind.  

Nick

> On Oct 6, 2015, at 3:50 PM, Randall Pruim <notifications@github.com> wrote:
> 
> Something like this?
> 
> favstats( arr_delay ~ carrier, data=oneday
> )
> 
> ## Error: Your tbl is not a data.frame.  Perhaps you need dplyr functions here.
> 
> favstats( 
> arr_delay ~ carrier, data=17
> )
> 
> ## Error: data must be an environment or data.frame.
> —
> Reply to this email directly or view it on GitHub.
> 

Nicholas Horton 
Professor of Statistics
Department of Mathematics and Statistics, Amherst College
Box 2239, 31 Quadrangle Dr
Amherst, MA 01002-5000
https://www.amherst.edu/people/facstaff/nhorton
