### ISSUE TITLE
make confidence interval-friendly version of qnorm()?

### ISSUE THREAD

**Issue by beanumber** [ProjectMOSAIC/mosaic#533]
Today, students struggled to understand why `qnorm(0.975)` is the right way to get the critical value for a 95% confidence interval. I realized that perhaps this is entirely an artifact of the way that `qnorm()` is written. 

Would you consider the following function:

```
z_star <- function (x, ...) {
   alpha <- 1 - x
   qnorm(c(alpha/2, 1 - alpha/2), ...)
}
```
To the user, if they want an `x`% confidence interval, then they just type `z_star(x)`. 

Now, perhaps there is a pedagogical value in forcing them to understand about the symmetry of the normal distribution, and the two-tailed nature of CIs, etc. But perhaps we are just beholden to the fact that for years the critical values in the back of books contained the left tail. And perhaps that is just because cdfs and pdfs are similarly defined by the left tail?

In any case, for any distribution, there is a handy way of saying: "give me the left or right tail probability." But for a symmetric distribution, why isn't there a handy way of saying: "give me the middle probability?"

**Comment by rpruim** [comment]
How about
```r
cdist("norm", 0.95)
## [1] -1.959964  1.959964
```
Works for any distribution.  We could define a slew of functions like `cnorm()`, `ct()`, `cchisq()`, etc. but I don't know if this is really necessary.  I can't say that I have even used `cdist()` much.

**Comment by rpruim** [comment]
@beanumber, what are your current thoughts?  Does `cdist()` work for you?  If not, how many functions of the form `cnorm()`, `ct()`, etc. would you want?

**Comment by beanumber** [comment]
I didn't know about `cdist`, but yes, that solves my problem. I don't think we need to define all the other functions, since this one will work for any parametric distribution. 

The only other one I would want would be `cdata`, and I can see that that exists as well.
