### ISSUE TITLE
Should the formula come first in cdata()

### ISSUE THREAD

**Issue by rpruim** [ProjectMOSAIC/mosaic#537]
Currently the order of the arguments is
```r
cdata(0.95, ~ diffmean, data = Boot.dist2)
```

Advantages to the switch:
  * in most functions with formulas, the formula comes first
  * the name of the formula argument is not consistent across functions, so it shouldn't be used with a name
  * it is easy enough to put `p=0.90` first if you want
  * there is no good default for the formula, but `p = 0.95` is a reasonable default for the probability

Disadvantage:
  * it will cause some old code to break

**Comment by nicholasjhorton** [comment]
I think that this would be helpful to change (even though it will cause some errors with old code).

If the change is made, is it feasible to try to identify old usage and generate a reasonable error message?

Nick

> On Oct 30, 2015, at 7:44 AM, Randall Pruim <notifications@github.com> wrote:
> 
> Currently the order of the arguments is
> 
> cdata(0.95, ~ diffmean, data = Boot.dist2)
> Advantages to the switch:
> 
> 	• in most functions with formulas, the formula comes first
> 	• the name of the formula argument is not consistent across functions, so it shouldn't be used with a name
> 	• it is easy enough to put p=0.90 first if you want
> 	• there is no good default for the formula, but p = 0.95 is a reasonable default for the probability
> Disadvantage:
> 
> 	• it will cause some old code to break
> —
> Reply to this email directly or view it on GitHub.
> 

Nicholas Horton 
Professor of Statistics
Department of Mathematics and Statistics, Amherst College
Box 2239, 31 Quadrangle Dr
Amherst, MA 01002-5000
https://www.amherst.edu/people/facstaff/nhorton

**Comment by dtkaplan** [comment]
Yes, I always mess up on cdata(). Should data= be second?
​

On Fri, Oct 30, 2015 at 6:44 AM, Randall Pruim <notifications@github.com>
wrote:

> Currently the order of the arguments is
>
> cdata(0.95, ~ diffmean, data = Boot.dist2)
>
> Advantages to the switch:
>
>    - in most functions with formulas, the formula comes first
>    - the name of the formula argument is not consistent across functions,
>    so it shouldn't be used with a name
>    - it is easy enough to put p=0.90 first if you want
>    - there is no good default for the formula, but p = 0.95 is a
>    reasonable default for the probability
>
> Disadvantage:
>
>    - it will cause some old code to break
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ProjectMOSAIC/mosaic/issues/537>.
>



-- 

...

DeWitt Wallace Professor of Mathematics, Statistics, and Computer Science
Macalester College

**Comment by rpruim** [comment]
I think `data` should not be second.  Here's why:

  1. I think `data = ` should ALWAYS be explicit because there are some places where you must be explicit and remembering which is which is tedious.  If you follow that rule, then it doesn't matter where `data` appears.

  2. That would make it harder to omit `data` and look in the enclosing environment.  (You would have to name the probability argument.)  I'd rather support `cdata(~1:100, 0.9)` than `cdata( ~x, my_data)`.

  3. `data` is a clearer, more consistent name than `p` (or is it `prob`? drat which function uses which?)

**Comment by nicholasjhorton** [comment]
I also don't want data to be second for the first and second reasons.

Nick

> On Oct 30, 2015, at 3:22 PM, Randall Pruim <notifications@github.com> wrote:
> 
> I think data should not be second. Here's why:
> 
> 	• I think data = should ALWAYS be explicit because there are some places where you must be explicit and remembering which is which is tedious. If you follow that rule, then it doesn't matter where data appears.
> 
> 	• That would make it harder to omit data and look in the enclosing environment. (You would have to name the probability argument.) I'd rather support cdata(~1:100, 0.9) than cdata( ~x, my_data).
> 
> 	• data is a clearer, more consistent name than p (or is it prob? drat which function uses which?)
> 
> —
> Reply to this email directly or view it on GitHub.
> 

Nicholas Horton 
Professor of Statistics
Department of Mathematics and Statistics, Amherst College
Box 2239, 31 Quadrangle Dr
Amherst, MA 01002-5000
https://www.amherst.edu/people/facstaff/nhorton

**Comment by rpruim** [comment]
```r
cdata( ~ Sepal.Length, 0.5, data = iris)
##       low        hi central.p 
##       5.1       6.4       0.5 
cdata( 0.5, ~ Sepal.Length, data = iris)
## Error in cdata(0.5, ~Sepal.Length, data = iris) : 
##   Invalid values of p.  Are your arguments in the wrong order?
```

**Comment by rpruim** [comment]
I've switched the order for `ddata()`, `pdata()`, `qdata()`, and `rdarta()` as well.  Seems like they should all match.

**Comment by dtkaplan** [comment]
You've convinced me.  -Danny

On Fri, Oct 30, 2015 at 2:22 PM, Randall Pruim <notifications@github.com>
wrote:

> I think data should not be second. Here's why:
>
>    1.
>
>    I think data = should ALWAYS be explicit because there are some places
>    where you must be explicit and remembering which is which is tedious. If
>    you follow that rule, then it doesn't matter where data appears.
>    2.
>
>    That would make it harder to omit data and look in the enclosing
>    environment. (You would have to name the probability argument.) I'd rather
>    support cdata(~1:100, 0.9) than cdata( ~x, my_data).
>    3.
>
>    data is a clearer, more consistent name than p (or is it prob? drat
>    which function uses which?)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ProjectMOSAIC/mosaic/issues/537#issuecomment-152623872>
> .
>



-- 

...

DeWitt Wallace Professor of Mathematics, Statistics, and Computer Science
Macalester College
