### ISSUE TITLE
add iqr to favstats() output

### ISSUE THREAD

**Issue by rpruim** [ProjectMOSAIC/mosaic#538]

**Comment by nicholasjhorton** [comment]
I'd prefer not to further clutter favstats: it's already a lot of information.

Just my $0.02,

Nick

> On Oct 30, 2015, at 8:55 AM, Randall Pruim <notifications@github.com> wrote:
> 
> Closed #538 via 3e09c97.
> 
> —
> Reply to this email directly or view it on GitHub.
> 

Nicholas Horton 
Professor of Statistics
Department of Mathematics and Statistics, Amherst College
Box 2239, 31 Quadrangle Dr
Amherst, MA 01002-5000
https://www.amherst.edu/people/facstaff/nhorton

**Comment by rpruim** [comment]
Hmm... I guess it is a little bit more info.  But for books that teach mean with sd and median with iqr, it is handy to have it precomputed.

```r
favstats( ~age | sex, data = HELPrct)
##     sex min Q1 median   Q3 max  iqr   mean     sd   n missing
## 1 female  21 31     35 40.5  58  9.5 36.252 7.5849 107       0
## 2   male  19 30     35 40.0  60 10.0 35.468 7.7501 346       0
```

**Comment by nicholasjhorton** [comment]
How about adding an IQR flag and setting it to FALSE by default?  I really am not wild about this addition. 

All the best,

Nick

**Comment by nicholasjhorton** [comment]
Who reports IQR by the way?  Only intro stats courses in my experience. 

All the best,

Nick

**Comment by rpruim** [comment]
I removed it.
