### ISSUE TITLE
mplot(TukeyHSD()) plots group differences in odd order.

### ISSUE THREAD

**Issue by rpruim** [ProjectMOSAIC/mosaic#541]
![image](https://cloud.githubusercontent.com/assets/722231/10939766/004f5c0e-82d2-11e5-9ce1-e43d9b5f1af9.png)

Better choices would be:
  * ordered by p-value
  * ordered by the difference
  * some sort of dictionary order

**Comment by rpruim** [comment]
Each of these now works:
```r
mplot(TukeyHSD(lm(births ~ wday, data = Births78)), order = "pval")
mplot(TukeyHSD(lm(births ~ wday, data = Births78)), order = "diff")
mplot(TukeyHSD(lm(births ~ wday, data = Births78)), order = "asis")
```
![image](https://cloud.githubusercontent.com/assets/722231/10940695/c62c808e-82d5-11e5-941e-0092cd8592f9.png)
![image](https://cloud.githubusercontent.com/assets/722231/10940717/e1b0cee6-82d5-11e5-8b3b-8bb51a5a65b0.png)
![image](https://cloud.githubusercontent.com/assets/722231/10940726/ec31c44c-82d5-11e5-98e1-1ff7165623cd.png)

**Comment by nicholasjhorton** [comment]
Nice!

Nick

> On Nov 4, 2015, at 9:26 AM, Randall Pruim <notifications@github.com> wrote:
> 
> Each of these now works:
> 
> mplot(TukeyHSD(lm(births ~ wday, data = Births78)), order = "pval"
> )
> mplot(TukeyHSD(lm(
> births ~ wday, data = Births78)), order = "diff"
> )
> mplot(TukeyHSD(lm(
> births ~ wday, data = Births78)), order = "asis")
> 
> 
> 
> 
> —
> Reply to this email directly or view it on GitHub.
> 

Nicholas Horton 
Professor of Statistics
Department of Mathematics and Statistics, Amherst College
Box 2239, 31 Quadrangle Dr
Amherst, MA 01002-5000
https://www.amherst.edu/people/facstaff/nhorton

**Comment by dtkaplan** [comment]
Yes, very nice!

-Danny

On Wed, Nov 4, 2015 at 8:26 AM, Randall Pruim <notifications@github.com>
wrote:

> Each of these now works:
>
> mplot(TukeyHSD(lm(births ~ wday, data = Births78)), order = "pval")
> mplot(TukeyHSD(lm(births ~ wday, data = Births78)), order = "diff")
> mplot(TukeyHSD(lm(births ~ wday, data = Births78)), order = "asis")
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/722231/10940695/c62c808e-82d5-11e5-941e-0092cd8592f9.png>
> [image: image]
> <https://cloud.githubusercontent.com/assets/722231/10940717/e1b0cee6-82d5-11e5-8b3b-8bb51a5a65b0.png>
> [image: image]
> <https://cloud.githubusercontent.com/assets/722231/10940726/ec31c44c-82d5-11e5-98e1-1ff7165623cd.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ProjectMOSAIC/mosaic/issues/541#issuecomment-153740637>
> .
>



-- 

...

DeWitt Wallace Professor of Mathematics, Statistics, and Computer Science
Macalester College
