### ISSUE TITLE
when to release the new version of mosaic to CRAN?

### ISSUE THREAD

**Issue by nicholasjhorton** [ProjectMOSAIC/mosaic#545]
@rpruim notes that it needs to be before the JMM.  I concur.

But the changes with qdata() will break working code.  Despite the excellent error message:

> qdata(c(.025, .975), ~ mean, data=trials)
Error in qdata(c(0.025, 0.975), ~mean, data = trials):
Invalid values of p.  Are your arguments in the wrong
order?

I would suggest waiting until the end of the semester (December 20th?) to add to CRAN, and that once it is there, a set of changes are described widely to the community.

Just my $0.02.

**Comment by rpruim** [comment]
I think that is OK.  The new things are not so urgent that they cannot wait.
