### ISSUE TITLE
best way to compute p-values for randomization tests?

### ISSUE THREAD

**Issue by rpruim** [ProjectMOSAIC/mosaic#547]
For a test statistic t, the recommended upper tailed test computes the p-value as based on a randomization distribution with r replicates is

```r
1 + count( ~ (T >= t), data = RandomizationDistirbution) / (1 + nrow(RandomizationDistribution))
```

This isn't as easy as 

```r
prop( ~ (T >= t), data = RandomizationDistribution)
```

Question: should we create a drop-in replacement for `prop()` that adds `1` to numerator and denominator, and if so, what should be call it?

Some options:
  * Don't even teach this.  Just use `prop()` as above.  [Note: this can produce p-values of 0.]
  * Teach this, but don't use a custom function.  The calculation can be pretty readily done from the output of `tally()` by adding one to numerator and denominator and dividing.
  * Teach this and provide a tool that make computing the number simpler.

**Comment by nicholasjhorton** [comment]
I'd suggest eliciting wider feedback (post to SIGMAA-StatEd, SBI, isostat, or Stat Ed section lists?)

Just my $0.02,

Nick

> On Nov 10, 2015, at 3:28 PM, Randall Pruim <notifications@github.com> wrote:
> 
> For a test statistic t, the recommended upper tailed test computes the p-value as based on a randomization distribution with r replicates is
> 
> 1 + count( ~ (T >= t), data = RandomizationDistirbution) / (1 + nrow(RandomizationDistribution))
> This isn't as easy as
> 
> prop( ~ (T >= t), data = RandomizationDistribution)
> Question: should we create a drop-in replacement for prop() that adds 1 to numerator and denominator, and if so, what should be call it?
> 
> Some options:
> 
> 	• Don't even teach this. Just use prop() as above. [Note: this can produce p-values of 0.]
> 	• Teach this, but don't use a custom function. The calculation can be pretty readily done from the output of tally() by adding one to numerator and denominator and dividing.
> 	• Teach this and provide a tool that make computing the number simpler.
> —
> Reply to this email directly or view it on GitHub.
> 

Nicholas Horton 
Professor of Statistics
Department of Mathematics and Statistics, Amherst College
Box 2239, 31 Quadrangle Dr
Amherst, MA 01002-5000
https://www.amherst.edu/people/facstaff/nhorton

**Comment by rpruim** [comment]
I went ahead and added a new function `prop1()` that adds 1 to the numerator and denominator.  See the  Start Teaching LIttle Book for examples.
