### ISSUE TITLE
Avoid name collision between mosaic::count() and dplyr::count()?

### ISSUE THREAD

**Issue by rpruim** [ProjectMOSAIC/mosaic#549]
With some work we can probably make these coexist the way we have with `tally()` and `do()`

**Comment by rpruim** [comment]
This seems to be working.  I made `count()` generic, added methods for `tbl` and `data.frame` that wrap `count_()` the same way that `dplyr::count()` does.  The default method does what `mosaic::count()` always used to do.

```r
require(mosaic)
HELPrct %>% count(sex, substance)
## Source: local data frame [6 x 3]
## Groups: sex [?]
## 
##      sex substance     n
##   <fctr>    <fctr> <int>
## 1 female   alcohol    36
## 2 female   cocaine    41
## 3 female    heroin    30
## 4   male   alcohol   141
## 5   male   cocaine   111
## 6   male    heroin    94
count( ~sex | substance, data = HELPrct)
## female.alcohol female.cocaine  female.heroin 
##             36             41             30 
```

**Comment by nicholasjhorton** [comment]
I worry that things aren't fully sussed.  Consider:


> HELPmiss %>% dplyr::count(sex)
# A tibble: 2 × 2
     sex     n
  <fctr> <int>
1   male   359
2 female   111
> HELPmiss %>% mosaic::count(sex)
 1. 
470

**Comment by rpruim** [comment]
Are you using the latest/greatest?

```r
HELPmiss %>% mosaic::count(sex)
## # A tibble: 2 × 2
##      sex     n
##   <fctr> <int>
## 1   male   359
## 2 female   111
```

**Comment by nicholasjhorton** [comment]
devtools::install_github("ProjectMOSAIC/mosaic", ref="beta")

isn't working for me: I get a bunch of error messages.  

Is there change merged into the master branch?

**Comment by nicholasjhorton** [comment]
I tried again from a clean slate:
Warning: /private/var/folders/42/dmhqyzmd1kv9070bc14qbjh40000gp/T/Rtmp3WZZMp/devtools17dbc7eae7453/ProjectMOSAIC-mosaic-5d62c4a/man/plotDist.Rd:26: unknown macro '\item'

is the error when I try to install the "beta" branch.

Can you replicate this error?

**Comment by rpruim** [comment]
Already fixed locally (will push soon).  Rd files don't like % (treat it as comment).

**Comment by nicholasjhorton** [comment]
It's still not working for me: am I missing something?

> HELPmiss %>% count()
# A tibble: 1 × 1
      n
  <int>
1   470
> sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: macOS Sierra 10.12.4

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] mosaic_0.14.9004  Matrix_1.2-8      mosaicData_0.14.0 ggplot2_2.2.1     lattice_0.20-35   dplyr_0.5.0.9004 
[7] RMySQL_0.10.11    DBI_0.6-1        

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.10     knitr_1.15.1     magrittr_1.5     MASS_7.3-45      splines_3.3.2    devtools_1.12.0 
 [7] munsell_0.4.3    colorspace_1.3-2 R6_2.2.0         ggdendro_0.1-20  rlang_0.0.0.9018 httr_1.2.1      
[13] plyr_1.8.4       tools_3.3.2      grid_3.3.2       gtable_0.2.0     git2r_0.18.0     withr_1.0.2     
[19] lazyeval_0.2.0   assertthat_0.2.0 digest_0.6.12    tibble_1.3.0     gridExtra_2.2.1  tidyr_0.6.1     
[25] curl_2.3         memoise_1.1.0    glue_1.0.0       scales_0.4.1    
>
