### ISSUE TITLE
Namespace issue with histogram

### ISSUE THREAD

**Issue by homerhanumat** [ProjectMOSAIC/mosaic#557]
When mosaic is not loaded,

```
lattice::histogram(~Petal.Length, data = iris)
```

gives a percentage-style histogram, as per the lattice default.

When mosaic is loaded the same call to `lattice::histogram()` gives a density-style histogram, as per the default in `mosaic::histogram()`.

**Comment by rpruim** [comment]
I'm not sure what the NAMESPACE issue is.  The use of the density scale by default in mosaic is intentional, in part to make it easier to overlay density curves and so the scale stays consistent as bin widths are varied.

**Comment by homerhanumat** [comment]
So as far as you know, mosaic has done nothing to override the user's ability to access another package's functions via :: ?

**Comment by rpruim** [comment]
The confusion here is that there is no `mosaic::histogram()`.  The implementation is different.  When the mosaic package loads, it changes the default panel function for the `lattice::histogram()` function.  There are functions to move back and forth between the lattice defaults and the mosaic defaults: `mosaicLatticeOptions()` and `restoreLatticeOptions()`. 

I'll open up a new issue to update the documentation in a way that makes this easier to find.

**Comment by homerhanumat** [comment]
I see, thanks.  I saw that there was no mosaic::histogram, but could not
find the .onload code to see what ti was doing to lattice.  Anyway, no
problem:  I've got a workaround for the thing I need to do for my students.
