### ISSUE TITLE
Cleaning gwm 

### ISSUE THREAD

**Issue by dtkaplan** [ProjectMOSAIC/mosaic#572]
* Make predict.groupwiseModel() use the same "type" argument as other predict methods.
    - dropped original "prob" behavior
    - now "prob" gives the probability of a specific level or, when `level = ".all"`, a dataframe of probs for each level.  (Should this be a matrix, like `predict.rpart()`?
* Clean up warnings and messages from dplyr about combining character and factor levels

This is now completed and merged with beta branch.  But I **cannot** compile the vignettes, and so I don't pass the build checks.  So I **have not** merged the `gwm` branch, which contains these changes, into the `beta` branch.

Randy, can you check out the `gwm` branch, confirm that it passes the checks, and, if you're happy with it, merge it into `beta`?  Thanks.

One small fix to branch gwm added at 3:19pm on Tuesday.  I'll leave it alone from here.

**Comment by rpruim** [comment]
the pushed gwm branch did not pass tests:

```
predict.groupwiseModel: warning in rank(desc(model_value), ties =
  "first"): partial argument match of 'ties' to 'ties.method'
MSPE: no visible binding for global variable ‘model_value’
predict.groupwiseModel: no visible binding for global variable
  ‘model_value’

Undocumented arguments in documentation object 'predict.groupwiseModel'
  ‘object’ ‘newdata’ ‘...’
```

I'm addressing these now.  It would be good to figure out why you cannot build the package.

It would also be good to have unit tests for this code if they do not already exist.

**Comment by rpruim** [comment]
done and merged into beta.

I changed one instance of `model_value` to `model_vals` since there was no instance of `model_value` in sight.  But perhaps there is another bug lurking.

**Comment by dtkaplan** [comment]
Thanks, Randy.  I'll close out my gwm branch now.  I agree about the unit
tests.  I'm trying to be better about writing them as I write package code.

-Danny

On Tue, Mar 15, 2016 at 4:39 PM, Randall Pruim <notifications@github.com>
wrote:

> done and merged into beta.
>
> I changed one instance of model_value to model_vals since there was no
> instance of model_value in sight. But perhaps there is another bug
> lurking.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> <https://github.com/ProjectMOSAIC/mosaic/issues/572#issuecomment-197032992>
>



-- 

...

DeWitt Wallace Professor of Mathematics, Statistics, and Computer Science
Macalester College
