### ISSUE TITLE
mUSmap() needs an example

### ISSUE THREAD

**Issue by rpruim** [ProjectMOSAIC/mosaic#573]
The old example used data from car, but we have removed that dependency, so the example has been removed.

**Comment by nicholasjhorton** [comment]
Is something reasonable found in data(States)?

Nick

> On Mar 15, 2016, at 4:55 PM, Randall Pruim <notifications@github.com> wrote:
> 
> The old example used data from car, but we have removed that dependency, so the example has been removed.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> 

Nicholas Horton 
Professor of Statistics
Department of Mathematics and Statistics, Amherst College
Box 2239, 31 Quadrangle Dr
Amherst, MA 01002-5000
https://www.amherst.edu/people/facstaff/nhorton

**Comment by rpruim** [comment]
Looks like another package dependency... What data set do you mean?

**Comment by nicholasjhorton** [comment]
Oops: my bad. 

How about data(USArrests)?

Nick

> On Mar 15, 2016, at 5:20 PM, Randall Pruim <notifications@github.com> wrote:
> 
> Looks like another package dependency... What data set do you mean?
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> 

Nicholas Horton 
Professor of Statistics
Department of Mathematics and Statistics, Amherst College
Box 2239, 31 Quadrangle Dr
Amherst, MA 01002-5000
https://www.amherst.edu/people/facstaff/nhorton

**Comment by rpruim** [comment]
That data set would be fine.  Trouble is, `mUSmap()` seems to be broken.  I'm wondering if something changed out from under us.

Does anyone use this?  Should we just get rid of all the mapping stuff and leave that to people who do mapping stuff?
![image](https://cloud.githubusercontent.com/assets/722231/13795150/d763ee74-ead5-11e5-98fb-4608db25c8b1.png)

**Comment by nicholasjhorton** [comment]
I would have no objections to deprecating it in this release to try to flush out users.

Nick

> On Mar 15, 2016, at 5:46 PM, Randall Pruim <notifications@github.com> wrote:
> 
> That data set would be fine. Trouble is, mUSmap() seems to be broken. I'm wondering if something changed out from under us.
> 
> Does anyone use this? Should we just get rid of all the mapping stuff and leave that to people who do mapping stuff?
> 
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> 

Nicholas Horton 
Professor of Statistics
Department of Mathematics and Statistics, Amherst College
Box 2239, 31 Quadrangle Dr
Amherst, MA 01002-5000
https://www.amherst.edu/people/facstaff/nhorton

**Comment by rpruim** [comment]
I think it should go directly to defunct unless someone wants to fix it.  As is, it isn't useful.

**Comment by rpruim** [comment]
OK.  I think I found the problem.  Looks like the new `ggplot2` has removed the `order` aesthetic from `geom_polygon`.  But I can mimic things by modifying the data with `arrange()`.

```r
mUSMap(USArrests %>% mutate(state = row.names(.)), key="state", fill = "UrbanPop")
## Mapping API still under development and may change in future releases.
```
![image](https://cloud.githubusercontent.com/assets/722231/13795964/7335cac6-eada-11e5-86d7-677c555d1411.png)

**Comment by dtkaplan** [comment]
Randy,

I'm so glad you found the problem.

I've been putting together some alternatives as part of my
formula-interface-to-plotting system (rooted in ggplot2 now, but
potentially upgrade-able to ggvis, etc.).  But they aren't ready yet.  When
that's on CRAN, maybe it would be a good idea first to deprecate mUSAmap()
and mWorldmap() in mosaic, with a redirect to the new functions.

That package is coming along well; I'm optimistic.

-Danny

On Tue, Mar 15, 2016 at 5:20 PM, Randall Pruim <notifications@github.com>
wrote:

> OK. I think I found the problem. Looks like the new ggplot2 has removed
> the order aesthetic from geom_polygon. But I can mimic things by
> modifying the data with arrange().
>
> mUSMap(USArrests %>% mutate(state = row.names(.)), key="state", fill = "UrbanPop")## Mapping API still under development and may change in future releases.
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/722231/13795964/7335cac6-eada-11e5-86d7-677c555d1411.png>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ProjectMOSAIC/mosaic/issues/573#issuecomment-197050696>
>



-- 

...

DeWitt Wallace Professor of Mathematics, Statistics, and Computer Science
Macalester College
