### ISSUE TITLE
Decide what needs to be a vignette and what can be left out

### ISSUE THREAD

**Issue by rpruim** [ProjectMOSAIC/mosaic#574]
```
* checking installed package size ... NOTE
  installed size is  8.9Mb
  sub-directories of 1Mb or more:
    R     1.8Mb
    doc   6.5Mb
```

**Comment by nicholasjhorton** [comment]
Do you have a proposal?

Nick

> On Mar 15, 2016, at 5:18 PM, Randall Pruim <notifications@github.com> wrote:
> 
> * checking installed package size ... NOTE
>   installed size is  8.9Mb
>   sub-directories of 1Mb or more:
>     R     1.8Mb
>     doc   6.5Mb
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> 

Nicholas Horton 
Professor of Statistics
Department of Mathematics and Statistics, Amherst College
Box 2239, 31 Quadrangle Dr
Amherst, MA 01002-5000
https://www.amherst.edu/people/facstaff/nhorton

**Comment by nicholasjhorton** [comment]
I think that the status quo is best here (if we can proceed to resubmit the package with the doc warning).  I don't want to get all full of attitude but we are talking about 6.5Mb, not 6.5GB or 6.5TB.  :-<
