### ISSUE TITLE
mosaic msummary() prunes "Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1" line, but still prints signif stars

### ISSUE THREAD

**Issue by nicholasjhorton** [ProjectMOSAIC/mosaic#579]
I'm not a big fan of the significance stars, but I'm not sure we want to set:
options(show.signif.stars=FALSE).  Thoughts?

**Comment by rpruim** [comment]
It does exactly what I intended.  You can use options to turn off the signif stars if you don't want them at all.  But even when they are there, I don't need to see the silly legend every time.  The point of `msummary()` was to reduce the number of lines of output, and getting rid of the legend does that.  (The starts themselves only add a bit of width, so I left them.)

**Comment by nicholasjhorton** [comment]
I've been pushing msummary() hard to instructors and students (and it's been very popular).  And I hate the significance stars.  But I'm not sure that it makes to print the stars without the legend.

Just my $0.02,

Nick

> On Mar 31, 2016, at 10:48 PM, Randall Pruim <notifications@github.com> wrote:
> 
> It does exactly what I intended. You can use options to turn off the signif stars if you don't want them at all. But even when they are there, I don't need to see the silly legend every time. The point of msummary() was to reduce the number of lines of output, and getting rid of the legend does that. (The starts themselves only add a bit of width, so I left them.)
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> 

Nicholas Horton 
Professor of Statistics
Department of Mathematics and Statistics, Amherst College
Box 2239, 31 Quadrangle Dr
Amherst, MA 01002-5000
https://www.amherst.edu/people/facstaff/nhorton

**Comment by rpruim** [comment]
We could try to get rid of the stars too, if you like.  My take is that the legend is no so necessary since the p-value is sitting right there.  But the stars can help direct your attention in cases where there are quite a few rows to the table and only some show small p-values.

I'd rather get rid of the stars than add the legend.

**Comment by dtkaplan** [comment]
I think the stars without the legend works well.  As Randy says, they
direct the eye and, without the legend, it's easy enough to get a reminder
of what the stars mean by looking at the p-value they are assigned to.



On Fri, Apr 1, 2016 at 7:34 AM, Randall Pruim <notifications@github.com>
wrote:

> We could try to get rid of the stars too, if you like. My take is that the
> legend is no so necessary since the p-value is sitting right there. But the
> stars can help direct your attention in cases where there are quite a few
> rows to the table and only some show small p-values.
>
> I'd rather get rid of the stars than add the legend.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ProjectMOSAIC/mosaic/issues/579#issuecomment-204381222>
>



-- 

...

DeWitt Wallace Professor of Mathematics, Statistics, and Computer Science
Macalester College
