### ISSUE TITLE
should xchisq.test() call the fourth column "standardized residual" as opposed to just "residual"

### ISSUE THREAD

**Issue by nicholasjhorton** [ProjectMOSAIC/mosaic#587]
I propose that we change:

<residual>

to 

<standardized residual> in chisq.test(), since residuals are just observed minus expected, no?

**Comment by rpruim** [comment]
The name was borrowed from the named item in the object that `chisq.test()` produces.  Here's the help.

```
A list with class "htest" containing the following components:

statistic	the value the chi-squared test statistic.
parameter	the degrees of freedom of the approximate chi-squared distribution of the test statistic, NA if the p-value is computed by Monte Carlo simulation.
p.value	    the p-value for the test.
method	    a character string indicating the type of test performed, and whether Monte Carlo simulation or continuity correction was used.
data.name	a character string giving the name(s) of the data.
observed	the observed counts.
expected	the expected counts under the null hypothesis.
residuals	the Pearson residuals, (observed - expected) / sqrt(expected).
stdres	    standardized residuals, (observed - expected) / sqrt(V), where V is the residual cell variance (Agresti, 2007, section 2.4.5 for the case where x is a matrix, n * p * (1 - p) otherwise).
```
I guess we could call them Pearson residuals if you like.

**Comment by nicholasjhorton** [comment]
I would happily adopt "Pearson residuals" instead of residuals.

Nick

> On Apr 27, 2016, at 4:23 PM, Randall Pruim <notifications@github.com> wrote:
> 
> The name was borrowed from the named item in the object that chisq.test() produces. Here's the help.
> 
> A list with class "htest" containing the following components:
> 
> statistic   the value the chi-squared test statistic.
> parameter   the degrees of freedom of the approximate chi-squared distribution of the test statistic, NA if the p-value is computed by Monte Carlo simulation.
> p.value     the p-value for the test.
> method      a character string indicating the type of test performed, and whether Monte Carlo simulation or continuity correction was used.
> data.name   a character string giving the name(s) of the data.
> observed    the observed counts.
> expected    the expected counts under the null hypothesis.
> residuals   the Pearson residuals, (observed - expected) / sqrt(expected).
> stdres      standardized residuals, (observed - expected) / sqrt(V), where V is the residual cell variance (Agresti, 2007, section 2.4.5 for the case where x is a matrix, n * p * (1 - p) otherwise).
> 
> I guess we could call them Pearson residuals if you like.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> 

Nicholas Horton 
Professor of Statistics
Department of Mathematics and Statistics, Amherst College
Box 2239, 31 Quadrangle Dr
Amherst, MA 01002-5000
https://www.amherst.edu/people/facstaff/nhorton

**Comment by rpruim** [comment]
done.
