### ISSUE TITLE
possible irregularity in t.test()

### ISSUE THREAD

**Issue by nicholasjhorton** [ProjectMOSAIC/mosaic#588]
There's an irregularity in t.test() that I wanted to point out.

Under 0.13 the following code works fine

> test10
function(){
  xvals <- mvrnorm(n=100, mu, Sigma)
  tests <- apply(xvals, 2, t.test)
  pvals <- sapply(tests, function(x){x$p.value})
  pvals <- sort(pvals)
  return(pvals)
}

but under 0.13.900003 it yields the error

 Error in lazyeval::lazy(x) : Promise has already been forced 

This is fixed by specifying which t.test function:

> test10
function(){
  xvals <- mvrnorm(n=100, mu, Sigma)
  tests <- apply(xvals, 2, stats::t.test)
  pvals <- sapply(tests, function(x){x$p.value})
  pvals <- sort(pvals)
  return(pvals)
}

**Comment by rpruim** [comment]
Reproducible examples are nicer.  Missing are your defs of `mu` and `Sigma`, and you should say which `mvrnorm()` you are using (from `MASS` or from `mvrnorm`).

I'm not able to recreate this problem doing
```r
require(mosaic)
M <- Matrix(rnorm(100), ncol = 5)
M %>% apply(2, t.test) %>% sapply(pval) %>% sort()
##    p.value    p.value    p.value    p.value    p.value 
## 0.02676316 0.46632480 0.54897116 0.73712684 0.77000867 
```

If you are still having issues, please submit a minimal reproducible example using `mosaic` from the beta branch.
