### ISSUE TITLE
unable to install ProjectMOSAIC/mosaic, ref="master" or ref="beta"

### ISSUE THREAD

**Issue by nicholasjhorton** [ProjectMOSAIC/mosaic#596]
I'm not able to install the master of ProjectMOSAIC/mosaic on either my mac (R 3.2.3 (2015-12-10)) or on my Digital ocean machine (R 3.3.0 (2016-05-03)) even after updating packages:

It yields the message:

** preparing package for lazy loading
Error : 'expr_text' is not an exported object from 'namespace:lazyeval'
Error : unable to load R code in package ‘mosaic’
ERROR: lazy loading failed for package ‘mosaic’

Do I need something beyond what is on CRAN to get this to work?

**Comment by rpruim** [comment]
You need to install `lazyeval` from github.  Hadley will be submitting to CRAN on June 10 and our github version of the package is preparing for that.

**Comment by rpruim** [comment]
I've added to the DESCRIPTION file a directive that `lazyeval` must be newer.

**Comment by rpruim** [comment]
Try installing from beta now.

**Comment by nicholasjhorton** [comment]
I was able to install the development version of lazyeval and install the beta branch.  Thanks!
