### ISSUE TITLE
stop supporting binom.test( ~ a, SomeData); same for prop.test()

### ISSUE THREAD

**Issue by rpruim** [ProjectMOSAIC/mosaic#597]
I think we should require
```r
binom.test( ~ a, data = SomeData)
```
Support for the other is more awkward in the new `lazyeval` API, and it's probably OK to require `data = ` anyway.

Am I forgetting anything important?

**Comment by nicholasjhorton** [comment]
I didn't know that

binom.test(~ sex=="female", HELPrct)

was supported and would have no problems requiring:

binom.test(~ sex=="female", data=HELPrct)

Nick

> On Jun 10, 2016, at 6:15 PM, Randall Pruim <notifications@github.com> wrote:
> 
> I think we should require
> 
> binom.test( ~ a, data = SomeData)
> Support for the other is more awkward in the new lazyeval API, and it's probably OK to require data = anyway.
> 
> Am I forgetting anything important?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Nicholas Horton 
Professor of Statistics
Department of Mathematics and Statistics, Amherst College
Box 2239, 31 Quadrangle Dr
Amherst, MA 01002-5000
https://www.amherst.edu/people/facstaff/nhorton

**Comment by rpruim** [comment]
My current draft version does this:
```r
binom.test( ~ a, TestData)
## Error: Improper `n'; did you forget `data = ' perhaps?
```

**Comment by rpruim** [comment]
And for good measure, I have this as well:
```r
binom.test(a, data = TestData)
## Error in .local(x, n, p, alternative, conf.level, ...) : 
##   binom.test: If data is not NULL, first argument should be a formula.
```

**Comment by dhananyashunmugam** [comment]
I have clarification regarding binom.test, I'm working on multinomial regression model, I have calculated overall accuracy using "confusionMatrix" function by "caret" R package. For multiclass model, I have used 1 vs all approach and calculated accuracy for each class using Accuracy function. My doubt is can i use binom.test function to calculate 95% CI accuracy for each class?

**Comment by rpruim** [comment]
@dhananyashunmugam, You can certainly use `binom.test()` (either the version in our package or `stats::binom.test()` on data of this sort, but it isn't clear that it will be doing what you want, and there are methods that target multinomial distributions directly (see `DescTools::MultinomCI()` for one such example).  

But there are other questions to be sorted out first, like what exactly you are trying to estimate (in-sample accuracy? out-of-sample accuracy?) and whether you have the correct data for the estimate(s) you are trying to make. 

Since this is not really a question about the `mosaic` package, I'd suggest posing your question elsewhere where you  are likely to get more responses.
