### ISSUE TITLE
concerns about name of derivedFactor()

### ISSUE THREAD

**Issue by nicholasjhorton** [ProjectMOSAIC/mosaic#600]
I'm increasingly concerned that the "derivedFactor()" function in mosaic may be discounted by people who don't like factors in R.  I don't think that there's anything about "derivedFactor()" that requires the return value to be a factor.  Would it be feasible to consider renaming this to something like "derivedVariable()" (or adding that as an alias)?

**Comment by rpruim** [comment]
All I needed to do was leave off the last bit of converting to a factor.  There is now a new  `.asFactor` argument.  `derivedVariable()` has the default set to FALSE.  `derivedFactor()` has the default set to TRUE.  Else things behave as before, I think.

```r
drvdFc> # Method 3: use TRUE to catch any fall through slots
drvdFc> modHELP <- mutate(HELPrct, drink_status = derivedFactor( 
drvdFc+   abstinent = i1 == 0,
drvdFc+   moderate = (i1<=1 & i2<=3 & sex=='female') |
drvdFc+      (i1<=2 & i2<=4 & sex=='male'),
drvdFc+   highrisk=TRUE,
drvdFc+   .ordered = TRUE,
drvdFc+   .method = "first"
drvdFc+   )
drvdFc+ )

drvdFc> tally( ~drink_status, data=modHELP )

abstinent  moderate  highrisk 
       68        28       357 

drvdFc> is.factor(modHELP$drink_status)
[1] TRUE

drvdFc> modHELP <- mutate(HELPrct, drink_status = derivedVariable( 
drvdFc+   abstinent = i1 == 0,
drvdFc+   moderate = (i1<=1 & i2<=3 & sex=='female') |
drvdFc+      (i1<=2 & i2<=4 & sex=='male'),
drvdFc+   highrisk=TRUE,
drvdFc+   .ordered = TRUE,
drvdFc+   .method = "first"
drvdFc+   )
drvdFc+ )

drvdFc> is.factor(modHELP$drink_status)
[1] FALSE
```

**Comment by nicholasjhorton** [comment]
This looks great!

All the best,

Nick
