### ISSUE TITLE
The shiny r markdown template is not renderable by default

### ISSUE THREAD

**Issue by haozhu233** [ProjectMOSAIC/mosaic#609]
Hi, when I was trying to organize some CRAN packages with markdown templates, I found that the shiny templates in this package is not renderable with the current skeleton.Rmd as it cannot recognize `inputPanel()`. I briefly went through the document and I'm wondering maybe you want to add `eval = FALSE` to those code chunks?

**Comment by nicholasjhorton** [comment]
I'm not able to replicate this problem.  Can you please include the output from sessionInfo() and the error message?

**Comment by haozhu233** [comment]
Ach, I suddenly realized that this is a template with shiny runtime. That's why it cannot be rendered by `rmarkdown::render()`. 

I'm going to close this issue. Sorry for this false reporting. :P
