### ISSUE TITLE
issue with mplot(which=7)

### ISSUE THREAD

**Issue by nicholasjhorton** [ProjectMOSAIC/mosaic#613]
When specifying system="ggplot2" the output of mplot(which=7) is garbled.

> library(mosaic)
> mod <- lm(cesd ~ substance, data=HELPrct)
> msummary(mod)
                 Estimate Std. Error t value Pr(>|t|)    
(Intercept)       34.3729     0.9246  37.178  < 2e-16 ***
substancecocaine  -4.9518     1.3602  -3.640 0.000304 ***
substanceheroin    0.4981     1.4405   0.346 0.729669    

Residual standard error: 12.3 on 450 degrees of freedom
Multiple R-squared:  0.0382,	Adjusted R-squared:  0.03393 
F-statistic: 8.936 on 2 and 450 DF,  p-value: 0.0001563

mplot(mod, which=7, rows=2:3) yields

![image](https://cloud.githubusercontent.com/assets/530542/17464595/7db6160c-5cb0-11e6-9b34-adf91ebc25fa.png)

while

mplot(mod, which=7, rows=2:3, system="ggplot2")

yields the incorrect

![image](https://cloud.githubusercontent.com/assets/530542/17464604/8ea6dc1c-5cb0-11e6-902f-dac8001da371.png)

**Comment by rpruim** [comment]
Fixed the bug (had `labels` where we needed `levels` in one call to `factor()`).
![image](https://cloud.githubusercontent.com/assets/722231/17517682/7095c4d2-5e12-11e6-87eb-cde81a8bcbfd.png)
