### ISSUE TITLE
cor() documentation issue

### ISSUE THREAD

**Issue by nicholasjhorton** [ProjectMOSAIC/mosaic#616]
The documentation states that the calling sequence for cor() is:

cor(x, y = NULL, ..., data = NULL)

**Comment by rpruim** [comment]
Good catch, we should fix this.

Well, fix it, dear Henry, dear Henry...  I guess our documentation is a leaky bucket.

**Comment by rpruim** [comment]
I'm trying to recall the point of this since
```r
args(cor)
## function (x, y = NULL, ..., data = NULL) 
```

This syntax allows us to support both formula-style and vector-style input:

```r
cor(length ~ width, data = KidsFeet)
## [1] 0.6410961
cor(KidsFeet$length, KidsFeet$width)
## [1] 0.6410961
```

**Comment by nicholasjhorton** [comment]
I agree: all of the other functions have the same form up at the top (which requires the analyst to look at the examples below).  

My only suggestion at this point in time is to add an example for cor() with missing data.  But looking at the documentation for mosaic_1.1.0 I also wonder if there's a workaround to the 

data.frame(mean(age ~ shuffle(sex), data = HELPrct, .format = "table"))

call.

**Comment by nicholasjhorton** [comment]
I'm not sure what's best here, but think that:

cor(x, y = NULL, ..., data = NULL)

is confusing, since

cor(length, width, data = KidsFeet)

doesn't work, but is implied by the formulation above.  I'll defer to @rpruim about what's best here but I do find this confusing (and couldn't justify the status quo for one of my Teaching Stats using R workshop this weekend).

**Comment by rpruim** [comment]
I think your "implication" is just false.  There is no claim that `cor(x, y, data = foo)` will work as you are imaging.  But we don't have much freedom to change the signature much, because we need unnamed arguments to work with 

```r
> args(stats::cor)
function (x, y = NULL, use = "everything", method = c("pearson", 
    "kendall", "spearman")) 
```

so `x, y = NULL` is required.

**Comment by nicholasjhorton** [comment]
I don't disagree with your factual statement.  

I'm just telling you that this is confusing for instructors and students.

**Comment by rpruim** [comment]
Here are some things we can do:
* add something to the documentation (not sure just what)
* produce an error or warning message if `data` and `y` are both non-null.

**Comment by rpruim** [comment]
```r
cor( length, width, data = KidsFeet)
## Error: When `data' is specified, `y' should not be used.
```
