### ISSUE TITLE
possible error with mosaic::count vs dplyr::count

### ISSUE THREAD

**Issue by nicholasjhorton** [ProjectMOSAIC/mosaic#619]
Katie St. Clair noted: Quick comment about the mosaic package - it is breaking the count command in dplyr. For a while I just thought I forgot how dplyr:count worked.

NH writes: I've not verified this, but do see the following:

> find("count")
[1] "package:mosaic" "package:dplyr" 

Is some work needed to make these interoperate?  (Or is this not an issue?)

**Comment by rpruim** [comment]
Old news: See #549
