### ISSUE TITLE
Clean up documentation for do()

### ISSUE THREAD

**Issue by rpruim** [ProjectMOSAIC/mosaic#620]
In particular highlight:
- naming 
- the c() trick

Move a renaming example forward.

**Comment by nicholasjhorton** [comment]
Would it be possible to add something to Details or Notes about how the naming is done?  I realize that this is actually part of * but suspect that this would be a better place to add this.

Just my $0.02,

Nick

> On Oct 7, 2016, at 11:30 AM, Randall Pruim <notifications@github.com> wrote:
> 
> In particular highlight:
> 
> 	• naming
> 	• the c() trick
> Move a renaming example forward.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Nicholas Horton 
Professor of Statistics
Department of Mathematics and Statistics, Amherst College
PO Box 5000, AC #2239
Amherst, MA 01002-5000

**Comment by nicholasjhorton** [comment]
It might be useful to take a sweep through the mosaic guide to resampling to add some discussion of this point.

**Comment by rpruim** [comment]
I've added this to the documentation:

**Naming**
The names used in the object returned from do() are inferred from the objects created in each replication. Roughly, this the strategy employed.

* If the objects have names, those names are inherited, if possible.

* If the objects do not have names, but do() is used with a simple function call, the name of that function is used. Example: `do(3) * mean(~height, data = Galton)` produces a data frame with a variable named mean.

* In cases where names are not easily inferred and a single result is produced, it is named `result`.

To get different names, one can rename the objects as they are created, or rename the result returned from do(). Example of the former: `do(3) * c(mean_height = mean(~height, data = resample(Galton)))`.

**Examples**
```r
# change the names on the fly
do(3) * mean(~height, data = resample(Galton))
do(3) * c(mean_height = mean(~height, data = resample(Galton)))
```
