### ISSUE TITLE
split out mosaicCalc from mosaic 

### ISSUE THREAD

**Issue by rpruim** [ProjectMOSAIC/mosaic#621]
Allow calculus functions to have separate development cycle.

**Comment by nicholasjhorton** [comment]
Can we find a time to make a decision about this?  I suspect that it would make sense to split out mosaicCalc.

**Comment by nicholasjhorton** [comment]
the decision to split out the calculus functions needs to be documented in NEWS.md.  This should list the functions that have moved (e.g., antiD(), which was the only one I tended to use).

**Comment by nicholasjhorton** [comment]
Anything else needed on this front?

**Comment by dtkaplan** [comment]
Attaching `mosaic` doesn't attach `mosaicCalc`. I tried the obvious fix, adding `mosaicCalc` to Imports in DESCRIPTION, but got a message that `mosaicCalc` isn't found (although it was installed from CRAN).  Suggestions?

**Comment by rpruim** [comment]
I think we don't want `mosaic` to depend on `mosaicCalc`.  The fix it to manually use `require(mosaicCalc)`.  The use cases for `mosaic` and `mosaicCalc` have, I think, a very small intersection.

**Comment by dtkaplan** [comment]
OK.  Just wanted to make sure it wasn't an omission.

**Comment by rpruim** [comment]
CRAN really doesn't like us having lots of hard dependencies.  We already have more than they would prefer.  I had to ask for special permission to keep `mosaicData` a dependency.

**Comment by nicholasjhorton** [comment]
It was my understanding that mosaic would not DEPEND on mosaicCalc, for the reasons that @rpruim outlined.
