### ISSUE TITLE
does method="se" work for confint()?

### ISSUE THREAD

**Issue by nicholasjhorton** [ProjectMOSAIC/mosaic#622]
Documentation says: method  
a character vector of methods to use for creating confidence intervals. Choices are "percentile" (or "quantile") which is the default, "stderr" (or "se"), "bootstrap-t", and "reverse" (or "basic"))

But:

> confint(rnorm(100), method="se")
> Error in match.arg(method, c("stderr", "percentile", "quantile"), several.ok = TRUE) : 
>   'arg' should be one of “stderr”, “percentile”, “quantile”

Note that "basic" isn't given as an option either...

**Comment by rpruim** [comment]
You are reading the documentation that only applies when confint() is given a do.data.frame.  confint() is a method and does different things with different first argument classes.
