### ISSUE TITLE
Installing mosaic error_ not available for R version 

### ISSUE THREAD

**Issue by ebuehler90** [ProjectMOSAIC/mosaic#623]
I am an absolute beginner trying to learn R and am encountering a problem downloading the mosaic package. I am using R Studio and continually get the error message: 
Installing package(s) into ‘C:/Program Files/R/R-2.15.2/library’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘mosaic’ is not available (for R version 2.15.2)

I have tried downloading it via the install packages feature and writing the code in the script (install.packages). I am not sure why it is not working. Do I need to change the something in RStudio itself or find a different version of mosaic? 

I also tried these lines of code that I had found for searching with this problem but they resulted in the same error message: 
install.packages("mosaic",repos = "http://cran.us.r-project.org/")
install.packages("/path/to/file/mosaic_0.14.4.tar.gz",repos = NULL, type="source")

**Comment by nicholasjhorton** [comment]
Sorry for the problems.  

You'll want to update your version of R and try again: the current version of the package requires at least R 3.0.0.

Nick

**Comment by nicholasjhorton** [comment]
Sorry for the problems.  

You'll want to update your version of R and try again: the current version of the package requires at least R 3.0.0.

Nick

> On Oct 24, 2016, at 6:53 AM, ebuehler90 <notifications@github.com> wrote:
> 
> I am an absolute beginner trying to learn R and am encountering a problem downloading the mosaic package. I am using R Studio and continually get the error message: 
> Installing package(s) into ‘C:/Program Files/R/R-2.15.2/library’
> (as ‘lib’ is unspecified)
> Warning in install.packages :
> package ‘mosaic’ is not available (for R version 2.15.2)
> 
> I have tried downloading it via the install packages feature and writing the code in the script (install.packages). I am not sure why it is not working. Do I need to change the something in RStudio itself or find a different version of mosaic?
> 
> I also tried these lines of code that I had found for searching with this problem but they resulted in the same error message: 
> install.packages("mosaic",repos = "http://cran.us.r-project.org/")
> install.packages("/path/to/file/mosaic_0.14.4.tar.gz",repos = NULL, type="source")
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Nicholas Horton 
Professor of Statistics
Department of Mathematics and Statistics, Amherst College
PO Box 5000, AC #2239
Amherst, MA 01002-5000
