### ISSUE TITLE
dotPlot doesn't work if openintro package is loaded

### ISSUE THREAD

**Issue by mlaviolet** [ProjectMOSAIC/mosaic#628]
While working on some examples for a class, I discovered an issue with the "openintro" package: the dotPlot function throws an error if mosaic is loaded. My session follows. 
```{r}
library(mosaic)
library(openintro)
dotPlot(~age, HELPrct)
# throws following error
# Error in min(x, na.rm = na.rm) : invalid 'type' (list) of argument
detach("package:openintro", unload = TRUE)
dotPlot(~age, HELPrct)
# now it works
```
Subsequently I found that no error is thrown if openintro is loaded first, and that both packages contain a function dotPlot. Could you address this issue? Thanks!

```{r}
R version 3.3.2 (2016-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] mosaic_0.14.4     Matrix_1.2-7.1    mosaicData_0.14.0 ggplot2_2.2.0    
[5] lattice_0.20-34   dplyr_0.5.0      

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.8      tidyr_0.6.0      assertthat_0.1   MASS_7.3-45     
 [5] grid_3.3.2       R6_2.2.0         plyr_1.8.4       gtable_0.2.0    
 [9] DBI_0.5-1        magrittr_1.5     scales_0.4.1     lazyeval_0.2.0  
[13] ggdendro_0.1-20  splines_3.3.2    tools_3.3.2      munsell_0.4.3   
[17] colorspace_1.3-2 gridExtra_2.2.1  tibble_1.2 
```

**Comment by rpruim** [comment]
No, we cannot.  We have no way of controlling the names of function in other people's packages.  We have pointed out to `openintro` that they reused `dotPlot()` and that this causes problems (https://github.com/OpenIntroOrg/openintro-r-package/issues/7), but unless they want to make a change, there is nothing we can do.  I'm not compelled to build in a work-around to make these co-exist since I don't consider `openintro` to warrant that sort of effort at this point.

**Comment by nicholasjhorton** [comment]
Michael,

Just a reminder, you can specify which version of dotPlot() you want:

mosaic::dotPlot() will yield our version, while
openintro::dotPlot() will yield the openintro version.

Nick

> On Dec 18, 2016, at 1:34 PM, Michael Laviolette <notifications@github.com> wrote:
> 
> While working on some examples for a class, I discovered an issue with the "openintro" package: the dotPlot function throws an error if mosaic is loaded. My session follows.
> 
> library(mosaic)
> library(openintro)
> dotPlot(~age, HELPrct)
> # throws following error
> # Error in min(x, na.rm = na.rm) : invalid 'type' (list) of argument
> detach("package:openintro", unload = TRUE)
> dotPlot(~age, HELPrct)
> # now it works
> 
> Subsequently I found that no error is thrown if openintro is loaded first, and that both packages contain a function dotPlot. Could you address this issue? Thanks!
> 
> R version 3.3.2 (2016-10-31)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows >= 8 x64 (build 9200)
> 
> locale:
> [1] LC_COLLATE=English_United States.1252 
> [2] LC_CTYPE=English_United States.1252   
> [3] LC_MONETARY=English_United States.1252
> [4] LC_NUMERIC=C                          
> [5] LC_TIME=English_United States.1252    
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] mosaic_0.14.4     Matrix_1.2-7.1    mosaicData_0.14.0 ggplot2_2.2.0    
> [5] lattice_0.20-34   dplyr_0.5.0      
> 
> loaded via a namespace (and not attached):
>  [1] Rcpp_0.12.8      tidyr_0.6.0      assertthat_0.1   MASS_7.3-45     
>  [5] grid_3.3.2       R6_2.2.0         plyr_1.8.4       gtable_0.2.0    
>  [9] DBI_0.5-1        magrittr_1.5     scales_0.4.1     lazyeval_0.2.0  
> [13] ggdendro_0.1-20  splines_3.3.2    tools_3.3.2      munsell_0.4.3   
> [17] colorspace_1.3-2 gridExtra_2.2.1  tibble_1.2 
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Nicholas Horton 
Professor of Statistics
Department of Mathematics and Statistics, Amherst College
PO Box 5000, AC #2239
Amherst, MA 01002-5000

**Comment by mlaviolet** [comment]
Seems like OpenIntro would have done better to just keep data sets in their package. Thanks for the prompt reply.

**Comment by rpruim** [comment]
You can also load data sets without attaching the package that contains them.  Here are two ways.

```r
head(openintro::acs12)
##   income         employment hrs_work  race age gender citizen time_to_work    lang married
## 1  60000 not in labor force       40 white  68 female     yes           NA english      no
## 2      0 not in labor force       NA white  88   male     yes           NA english      no
## 3     NA               <NA>       NA white  12 female     yes           NA english      no
## 4      0 not in labor force       NA white  17   male     yes           NA   other      no
## 5      0 not in labor force       NA white  77 female     yes           NA   other      no
## 6   1700           employed       40 other  35 female     yes           15   other     yes
##           edu disability   birth_qrtr
## 1     college         no jul thru sep
## 2 hs or lower        yes jan thru mar
## 3 hs or lower         no oct thru dec
## 4 hs or lower         no oct thru dec
## 5 hs or lower        yes jul thru sep
## 6 hs or lower        yes jul thru sep
data(acs12, package = "openintro")
```

So, if all you want is the data sets, you can grab them without attaching the package.  (For our data sets, you can just use the `mosaicData` package without the `mosaic` package.)
