### ISSUE TITLE
Support for chisq.test

### ISSUE THREAD

**Issue by VectorPosse** [ProjectMOSAIC/mosaic#633]
I'd love to be able to use formula notation in chisq.test. For example:

`library(openintro)`
`chisq.test(smoke ~ maritalStatus, data = smoking)`

**Comment by nicholasjhorton** [comment]
> On Mar 1, 2017, at 6:24 PM, Sean Raleigh <notifications@github.com> wrote:
> 
> I'd love to be able to use formula notation in chisq.test. For example:
> 
> library(openintro)
> chisq.test(smoke ~ maritalStatus, data = smoking)
> 
> —

I'd do this in the following way:

> library(openintro)
> tally(smoke ~ maritalStatus, data=smoking)
     maritalStatus
smoke Divorced Married Separated Single Widowed
  No       103     669        46    269     183
  Yes       58     143        22    158      40
> chisq.test(tally(smoke ~ maritalStatus, data=smoking))

	Pearson's Chi-squared test

data:  tally(smoke ~ maritalStatus, data = smoking)
X-squared = 74.98, df = 4, p-value = 2.012e-15


Is that a workable option on your end?

Nick



Nicholas Horton 
Professor of Statistics
Department of Mathematics and Statistics, Amherst College
PO Box 5000, AC #2239
Amherst, MA 01002-5000

**Comment by VectorPosse** [comment]
Since I'm working with fairly non-technical undergrads, I'm trying to keep commands as simple and consistent as possible. The fact that `chisq.test` isn't consistent with other types of tests is an R thing, not a mosaic thing, so I get that. I was just wondering if you felt mosaic could make the choice to standardize this command. Since your commands are wrappers for the base R commands, I can also understand why you wouldn't want to mess with the weird "table as input" functionality.

**Comment by nicholasjhorton** [comment]
Perhaps the openintro folks might be willing to create a wrapper for this (they've done similar things in the past).

Just my $0.02,

Nick

> On Mar 4, 2017, at 5:10 PM, Sean Raleigh <notifications@github.com> wrote:
> 
> Since I'm working with fairly non-technical undergrads, I'm trying to keep commands as simple and consistent as possible. The fact that chisq.test isn't consistent with other types of tests is an R thing, not a mosaic thing, so I get that. I was just wondering if you felt mosaic could make the choice to standardize this command. Since your commands are wrappers for the base R commands, I can also understand why you wouldn't want to mess with the weird "table as input" functionality.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Nicholas Horton 
Professor of Statistics
Department of Mathematics and Statistics, Amherst College
PO Box 5000, AC #2239
Amherst, MA 01002-5000

**Comment by VectorPosse** [comment]
Thanks for quick response, Nick.

**Comment by rpruim** [comment]
I'm sure we discussed doing this at some point, but I don't recall why we decided not to do it.  `chisq.test()` does allow you to send in to vectors:
```r
> chisq.test(KidsFeet$biggerfoot, KidsFeet$domhand)

	Pearson's Chi-squared test with Yates' continuity correction

data:  KidsFeet$biggerfoot and KidsFeet$domhand
X-squared = 2.5911, df = 1, p-value = 0.1075

Warning message:
In chisq.test(KidsFeet$biggerfoot, KidsFeet$domhand) :
  Chi-squared approximation may be incorrect

> chisq.test(tally(biggerfoot ~ domhand, data = KidsFeet))

	Pearson's Chi-squared test with Yates' continuity correction

data:  tally(biggerfoot ~ domhand, data = KidsFeet)
X-squared = 2.5911, df = 1, p-value = 0.1075

Warning message:
In chisq.test(tally(biggerfoot ~ domhand, data = KidsFeet)) :
  Chi-squared approximation may be incorrect
```
I think this is doable in 3-4 lines of code.... Trying to figure out if there is a gotcha I'm not seeing just now.

**Comment by rpruim** [comment]
I've implemented this (locally, for the moment) in `xchisq.test()`.
```r
> xchisq.test( sex ~ substance, data = HELPrct)

	Pearson's Chi-squared test

data:  tally(x, data = data)
X-squared = 2.0264, df = 2, p-value = 0.3631

   36       41       30   
( 41.81) ( 35.90) ( 29.29)
[0.8068] [0.7236] [0.0173]
<-0.898> < 0.851> < 0.131>
     
  141      111       94   
(135.19) (116.10) ( 94.71)
[0.2495] [0.2238] [0.0053]
< 0.500> <-0.473> <-0.073>
     
key:
	observed
	(expected)
	[contribution to X-squared]
	<Pearson residual>
```

**Comment by rpruim** [comment]
On github now.
