### ISSUE TITLE
Support for cor.test?

### ISSUE THREAD

**Issue by VectorPosse** [ProjectMOSAIC/mosaic#635]
Have you considered wrapping cor.test so that it supports the tilde notation?

**Comment by rpruim** [comment]
`cor.test()` already has a formula interface.  See the examples:

```r
## Formula interface.
require(graphics)
pairs(USJudgeRatings)
cor.test(~ CONT + INTG, data = USJudgeRatings)
```

Unfortunately, the authors of `cor.test()` have chosen to use formulas differently from how we would probably have done things.  We do support `tally(~ x + y)`, so this form does exist in `mosaic`, and perhaps can be thought of as reflecting that neither variable is necessarily the response variable.

Not sure yet whether it is worth the hassle to support this.

**Comment by VectorPosse** [comment]
Sorry, I should have been more clear about which formula interface I meant. (As you correctly inferred: y ~ x)

Since I cover correlation and regression together (as many do, I imagine), I was thinking it would be easier on the students to see cor.test(y ~ x, data = ___ ) and lm(y ~ x, data = ___ ). But I also get that it might not be worth the hassle.

**Comment by rpruim** [comment]
It's a bit of a pain to write wrappers around S3 methods from other packages, but since we only need to extend the behavior by one situation (formulas of the shape `y~x`, I went ahead and did it.

```r
> cor.test(CONT ~ INTG, data = USJudgeRatings)

	Pearson's product-moment correlation

data:  CONT and INTG
t = -0.8605, df = 41, p-value = 0.3945
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 -0.4168591  0.1741182
sample estimates:
       cor 
-0.1331909 
```
@VectorPosse, feel free to install from github and give it a test drive.

**Comment by VectorPosse** [comment]
Thanks. I really appreciate all the work you guys put into this amazing package.
