### ISSUE TITLE
Output of xqnorm with lower.tail = FALSE 

### ISSUE THREAD

**Issue by luebby** [ProjectMOSAIC/mosaic#637]
While xpnorm works correctly with option lower.tail = FALSE the additional output of xqnorm seems to be wrong:

> xqnorm(0.1, lower.tail = FALSE)
	P(X <= 1.2815515655446) = 0.1
	P(X >  1.2815515655446) = 0.9

[1] 1.281552

**Comment by nicholasjhorton** [comment]
Karsten,

I don't think that this is a bug in xpnorm().

This is what the underlying R functions in the stats package do (which are called by the mosaic functions):

> pnorm(1.28)
[1] 0.8997274
> pnorm(1.28, lower.tail=FALSE)
[1] 0.1002726
> qnorm(0.1)
[1] -1.281552
> qnorm(0.1, lower.tail=FALSE)
[1] 1.281552

The documention states:

lower.tail	logical; if TRUE (default), probabilities are P[X ≤ x] otherwise, P[X > x].

I also find this a little confusing (but had never thought about using lower.tail with qnorm()).

**Comment by luebby** [comment]
Nicholas,

thanks for the fast reply!

And you are definitely right, my only "objection" was the printed output:

P(X <= 1.2815515655446) = 0.1
P(X > 1.2815515655446) = 0.9

(I use it sometimes for didactic reasons.)

Karsten



Am 01.04.2017 um 14:59 schrieb Nicholas Horton:

**Comment by nicholasjhorton** [comment]
Ah: I now see your point.  I'm reopening this to see what Randy has to say.

**Comment by luebby** [comment]
I guess a fix is easy (?): Just don't pass the lower.tail option in the first line (q=...) but for the returned object at the end.

xqnorm <- function (p, mean = 0, sd = 1, plot = TRUE, verbose = TRUE, digits = 4, 
          lower.tail = TRUE, log.p = FALSE, xlim, ylim, invisible = FALSE, 
          vlwd = 2, vcol = trellis.par.get("add.line")$col, rot = 45, 
          ...) 
{
  q = qnorm(p, mean = mean, sd = sd, log.p = log.p)
  z = (q - mean)/sd
  if (verbose) {
    cat(paste("\tP(X <= ", q, ") = ", p, "\n", sep = ""))
    cat(paste("\tP(X >  ", q, ") = ", 1 - p, "\n", sep = ""))
    cat("\n")
  }
  if (plot & length(p) == 1) {
    print(.plot_one_norm(p = p, q = q, mean, sd, xlim = xlim, 
                         ylim = ylim, digits = digits, vlwd = vlwd, vcol = vcol, 
                         rot = rot, ...))
  }
  if (plot & length(p) > 1) {
    print(.plot_multi_norm(p = p, q = q, mean, sd, xlim = xlim, 
                           ylim = ylim, digits = digits, vlwd = vlwd, vcol = vcol, 
                           rot = rot, ...))
  }
  if (invisible) {
    return(invisible(qnorm(p, mean = mean, sd = sd, lower.tail = lower.tail, 
                           log.p = log.p)))
  }
  return(qnorm(p, mean = mean, sd = sd, lower.tail = lower.tail, 
               log.p = log.p))
}

**Comment by rpruim** [comment]
@luebby, I think that your solution would make the output true, but not what was requested.  I've fixed this a different way, and also set things so that the digits argument affects the text printout as well as the plot.

```r
> xqnorm(c(0.6, 0.1), lower.tail = FALSE, digits = 3)
	P(X <= -0.253) =  0.4 
 	P(X <=  1.282) =  0.9 
	P(X > -0.253) =  0.6 
 	P(X >  1.282) =  0.1 
```

**Comment by rpruim** [comment]
Tweaking the output a bit while I'm at it:
```r
> xqnorm(c(0.6, 0.1), lower.tail = FALSE, digits = 3, mean = 2, sd = 5)

If X ~ N(2, 5), then 

	P(X <= 0.733) = 0.4
 	P(X <= 8.408) = 0.9
	P(X >  0.733) = 0.6
 	P(X >  8.408) = 0.1

[1] 0.7332645 8.4077578
```
