### ISSUE TITLE
xqqmath: pch=20 not overriding default (pch=16) 

### ISSUE THREAD

**Issue by lbcollins** [ProjectMOSAIC/mosaic#638]
pch arguement appears to be ignored in xqqmath.  

Can others replicate this problem?  For me, the following code demonstrates the behavior described.

`x <- rnorm(100) `
`lattice::qqmath(~x)  # default plotting (circle with no fill)`
`lattice::qqmath(~x, pch=20)  # changes to smaller filled dots`

`mosaic::xqqmath(~x)  # default plotting (circle with no fill)`
`mosaic::xqqmath(~x, pch=20)  # no change in plot symbols!`

**Comment by rpruim** [comment]
Fixed.
```r
xqqmath( ~ length, data = KidsFeet, pch = 21, col = "red", fill = "skyblue")
```
![image](https://cloud.githubusercontent.com/assets/722231/25066105/c3c0b3aa-21ea-11e7-841f-fc681cbc5183.png)
