### ISSUE TITLE
Add "repeat()" function for chaining version of do()

### ISSUE THREAD

**Issue by rpruim** [ProjectMOSAIC/mosaic#642]
As per discussion in #641, it might be nice to allow the following syntax:

```r
rflip(20) %>% 
  repeat(2000)
```
which would be equivalent to 

```r
do(2000) * rflip(20)
```
Unfortunately, `repeat` is a keyword, so we would need another name.  `do()` is bad because it is part of `dplyr`.  

Nominations for a name are now open.

**Comment by rpruim** [comment]
From @dtkaplan:

I certainly agree that we should wait for `rlang`. (Also, that gets me past
a very busy work period!)

I don't know enough about `magrittr` to write a function such as the
`repeat(5000)` imagined here. The problem from me is getting the
unevaluated LHS of the pipe --- everything to the left of `repeat(5000)`.
That's the only reason I put things in a `magrittr`-like operator.

Nomination for name: `trials()`.

**Comment by rpruim** [comment]
I think I would prefer a verb to a noun.  (I though about `again()` but didn't like that for the same reason.)  

Perhaps `repeat_n()` (sort of like `dplyr::sample_n()`)?

**Comment by rpruim** [comment]
Also, I'm wondering if this should go in its own little package.  It is largely independent of other things in `mosaic` and could be used without the rest of mosaic (even by people who are annoyed with some aspects of `mosaic` but who like `dplyr`).

**Comment by beanumber** [comment]
Note that @mine-cetinkaya-rundel has written a similar function called `rep_sample_n()` for the `oilabs` package: (https://github.com/OpenIntroOrg/oilabs/blob/master/R/rep_sample_n.R)

If memory serves it is as fast as `replicate()`, which is considerably faster than `dplyr::do()` and `mosaic::do()`. 

I would love to see something like this become part of the `tidyverse`. 

The name `repeat_n()` seems good to me.

**Comment by rpruim** [comment]
I don't think something like this belongs bogged down by OI overhead.

`mosaic::do()` is also as fast as replicate (and can be faster since it uses `parallel` -- if you are "doing" the right things.  The slow part is all of the extraction of clever bits.  But we can perhaps rethink that and see if there is a more efficient way to go.

**Comment by rpruim** [comment]
Looks like `rep_sample_n()` is solving a different (and much narrower) problem: sampling from a data frame.  We want something that will execute more or less arbitrary code (and ideally tidy up the mess that might be produced into a handy data frame).

**Comment by beanumber** [comment]
Remember we looked at this before? I'm not seeing the performance of `mosaic::do()` here:
```
# devtools::install_github("OpenIntroOrg/oilabs")
library(mosaic)
library(oilabs)
n <- 2000
k <- 50
rep_oilabs <- function() {
  HELPrct %>% 
    rep_sample_n(size = k, reps = n, replace = TRUE) %>%
    summarise(x_bar = mean(mcs))
}

rep_mosaic_do <- function() {
  do(n) * HELPrct %>% 
    sample_n(k, replace = TRUE) %>%
    summarise(x_bar = mean(mcs))
}

rep_dplyr_do <- function() {
  data.frame(replicate = 1:n) %>%
    group_by(replicate) %>%
    dplyr::do(sample_n(HELPrct, size = k, replace = TRUE) %>% 
               summarize(x_bar = mean(mcs)))
}

microbenchmark::microbenchmark(rep_oilabs(), rep_mosaic_do(), rep_dplyr_do(), times = 10)
```
```
|========================================================================= |100% ~0 s remaining     Unit: milliseconds
            expr       min        lq      mean    median        uq       max neval cld
    rep_oilabs()  106.2532  110.3054  141.8308  114.6724  156.9724  240.7725    10 a  
 rep_mosaic_do() 3304.0372 3398.3346 3432.0767 3441.1385 3452.3431 3547.6736    10   c
  rep_dplyr_do() 3148.7853 3178.5994 3241.5678 3244.3996 3275.1313 3399.3520    10  b 
```
Should I be doing something different? [This computer has 16 cores.]

I agree that `rep_sample_n()` is solving a narrower problem and belongs in a more usable place.

**Comment by rpruim** [comment]
Here are some quick benchmarks based on `repeatR`.  To be fair, `repeatR` does not yet do all the fancy auto-formatting stuff.  But it appears to me much faster than `do()` right now.
```r
rep_mosaic_do <- function() {
  do(2000) * HELPrct %>% 
    sample_n(50, replace = TRUE) %>%
    summarise(x_bar = mean(mcs))
}

rep_mosaic_do2 <- function() {
  do(2000) * mean( ~ mcs, data = resample(HELPrct, size = 50))
}

rep_repeatR <- function() {
  mean( ~ mcs, data = resample(HELPrct, size = 50)) %>% 
    repeat_n(2000, combine = function(x) data.frame(mean = unlist(x)))
}

rep_repeatR0 <- function() {
  mean( ~ mcs, data = resample(HELPrct, size = 50)) %>% 
    repeat_n(2000, cull = function(x) x, combine = function(x) x)
}

rep_oilabs <- function() {
  HELPrct %>% 
    oilabs::rep_sample_n(size = 50, reps = 2000, replace = TRUE) %>%
    summarise(x_bar = mean(mcs))
}

microbenchmark::microbenchmark(
  rep_repeatR(), rep_repeatR0(),
  rep_oilabs(), rep_mosaic_do(), rep_mosaic_do2(), 
  times = 10)
```
```r
Unit: milliseconds
             expr        min        lq      mean    median        uq       max neval  cld
    rep_repeatR()  529.82189  545.9514  580.2811  576.4670  612.1571  639.7490    10  b  
   rep_repeatR0()  517.03473  524.8166  568.1935  548.4559  604.2564  705.2771    10  b  
     rep_oilabs()   91.06257  105.9961  112.5200  112.3689  120.8798  128.9048    10 a   
  rep_mosaic_do() 3703.64971 3764.6260 3926.7062 3932.8676 4032.8422 4226.9883    10    d
 rep_mosaic_do2() 2192.95356 2252.4572 2340.3272 2331.5373 2368.3504 2656.2524    10   c 
```

**Comment by rpruim** [comment]
And for comparison, here it is with the `parallel` package on board:

```r
Unit: milliseconds
             expr       min        lq      mean    median        uq       max neval  cld
    rep_repeatR()  343.6042  359.5088  381.1254  368.4385  387.1630  487.6827    10  b  
   rep_repeatR0()  338.9992  347.1126  404.9190  358.7068  513.7864  534.9931    10  b  
     rep_oilabs()  105.7408  234.5803  238.8523  251.3029  265.6347  370.4087    10 a   
  rep_mosaic_do() 2036.5484 2100.6303 2170.5611 2134.0516 2248.3951 2463.3913    10    d
 rep_mosaic_do2() 1209.2062 1228.8609 1268.6113 1247.6858 1262.0586 1411.9240    10   c 
```

Not sure why oilabs is slower here...  But I ran these at different times, so the load due to other things may be interfering a bit.

**Comment by beanumber** [comment]
See also `modelr::bootstrap()` and `purrr:rerun()` and `resamplr`.

**Comment by rpruim** [comment]
For now, this is in its own package and development will happen at https://github.com/ProjectMOSAIC/repeatR
