### ISSUE TITLE
histogram not exported object from namespace:mosaic

### ISSUE THREAD

**Issue by lbcollins** [ProjectMOSAIC/mosaic#643]
I cannot access the mosaic package version of the histogram function:

mosaic::histogram(~x)
Error: 'histogram' is not an exported object from 'namespace:mosaic'

lattice::histogram(~ x) works just fine.

This error message is replicable in R 3.3.1 and R 3.3.3 (on Mac) and R 3.3.3 (on Linux) even after running update.packages("mosaic").

...and since that didn't work, I forced an update directly from the developer sight:
devtools::install_github("ProjectMOSAIC/mosaic", force=TRUE)

Still the same error.

**Comment by nicholasjhorton** [comment]
Does this help?

library(mosaic)
> find("histogram")
[1] "package:lattice"
> find("xhistogram")
[1] "package:mosaic"

**Comment by rpruim** [comment]
There is no `histogram()` function in the `mosaic` package.  That's why `mosaic::histogram()` fails.  Instead, when the `mosaic` package loads, it changes the default *panel* function used for creating histograms.  See `?panel.xhistogram`.

**Comment by rpruim** [comment]
And please DO NOT USE `xhistogram()`.  If you try, you will just get a message telling you not to do that.

```r
> xhistogram(~ rnorm(100))
Error: xhistogram() is no longer needed; simply use histogram() with the mosaic package attached.
```

**Comment by lbcollins** [comment]
Right.  `xhistogram` was deprectated.  ...and is now defunct?

I will start another issue to explain the more salient issue.  Thanks for correcting me that the namespace was not the issue causing my problem.

**Comment by rpruim** [comment]
Originally we needed `xhistogram()` because `lattice::histogram()` did not support supply a breaks *function*, which we needed.  Once that was added to `lattice`, we no longer had reason to keep `xhistogram()`.

**Comment by lbcollins** [comment]
I found the solution in `?panel.xhistogram`

This no longer works (illustration of error is attached):
`histogram(~z, density=TRUE)`

But this does work:
`histogram(~z, density=TRUE, fit="normal")`

![screen shot 2017-04-29 at 3 15 39 pm](https://cloud.githubusercontent.com/assets/5378205/25558601/b073dae2-2cef-11e7-9999-dfe86f0ef71d.png)

**Comment by lbcollins** [comment]
Actually, this is all I need:

`histogram(~z, fit="normal")`

**Comment by rpruim** [comment]
New thread?

**Comment by rpruim** [comment]
But I can't reproduce.  So if you open a new thread be sure to give some info about your system (version of package especially).

**Comment by rpruim** [comment]
And please give self-contained (minimal) reproducible examples.

**Comment by rpruim** [comment]
```r
> set.seed(123)
> histogram(~rnorm(100), fit = "normal")
```
![image](https://cloud.githubusercontent.com/assets/722231/25558656/2031f7c0-2cf9-11e7-9d5d-3d67c6c5d3b1.png)

```r
> sessionInfo()
R version 3.3.3 Patched (2017-03-15 r72368)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X El Capitan 10.11.6

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] mosaic_0.14.9004     Matrix_1.2-8         mosaicData_0.14.9000 ggplot2_2.2.1       
[5] lattice_0.20-34      dplyr_0.5.0.9004    

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.10     tidyr_0.6.1      assertthat_0.2.0 MASS_7.3-45      grid_3.3.3      
 [6] R6_2.2.0         plyr_1.8.4       gtable_0.2.0     magrittr_1.5     scales_0.4.1    
[11] rlang_0.0.0.9018 lazyeval_0.2.0   ggdendro_0.1-20  splines_3.3.3    tools_3.3.3     
[16] glue_1.0.0       munsell_0.4.3    colorspace_1.3-2 gridExtra_2.2.1  tibble_1.3.0   
```

**Comment by lbcollins** [comment]
All is fine.  Thank you very much for the example.  I can reproduce your working result.

**Comment by rpruim** [comment]
Glad to hear there is no problem.
