### ISSUE TITLE
convert from lazyeval to rlang

### ISSUE THREAD

**Issue by rpruim** [ProjectMOSAIC/mosaic#646]

**Comment by rpruim** [comment]
I'm not going to let a complete conversation slow down the release of mosaic 1.0, but we should probably keep this as a goal.  Hadley says that lazyeval won't be going away, but I think rlang is the right package to use going forward.

**Comment by nicholasjhorton** [comment]
Is this related to https://github.com/ProjectMOSAIC/mosaic/issues/754?

**Comment by rpruim** [comment]
possibly.  or just changes to rlang itself.

I closed this because it is (mostly) done and we have an open #750 to track down any remaining edge issues.
