### ISSUE TITLE
brainstorm next steps for outreach

### ISSUE THREAD

**Issue by nicholasjhorton** [ProjectMOSAIC/mosaic#647]
posting of the mosaic package paper first needs:

1. updated mosaic on CRAN
2. ggformula on CRAN

other pieces:

1. Minimal R with ggformula  (needed for mosaic CRAN release?)
2. mplot support for ggformula  (needed for mosaic CRAN release?)

After mosaic on CRAN with ggformula support

3. addendum to mosaic package paper (elaboration of ggformula)  [Nick?]
4. guest blog entry on ggformula (SAS and R: drafted by Randy)?
5. ggformula in R Journal

Student Guide to R [Nick]
Start Teaching with R 
Start Modeling in R?  Third edition of "Fresh Approach"?

ICOTS short course (Danny probably, Nick probably, Randy maybe)?

**Comment by nicholasjhorton** [comment]
I'm ready to move forward with the next steps for outreach, but it requires a new version of mosaic on CRAN.  Any updates on when that might be feasible?

**Comment by nicholasjhorton** [comment]
I'm blocked on the next steps for the mosaic outreach (that really would benefit from happening before the JSM) until the new version of mosaic is on CRAN.  Is it possible to see what's needed to get things installed?

**Comment by rpruim** [comment]
Should have mosaic 1.0 on CRAN soon -- pending any issues getting it through all the checks.

At that point, we are probably ready to move on the ggformula blog post and R Journal articles.
