### ISSUE TITLE
need to add second "Minimal R" with support for ggformula

### ISSUE THREAD

**Issue by nicholasjhorton** [ProjectMOSAIC/mosaic#649]
I suspect that it would be helpful to keep both (and eventually deprecate the lattice version).

**Comment by rpruim** [comment]
Have to decide if this belong in `mosaic` or in `ggformula`, but I don't expect the translation itself to be difficult.

**Comment by nicholasjhorton** [comment]
The following changes are needed on page 3:

bwplot(), xyplot(), histogram(), densityplot(), freqpolygon(), qqmath(), ladd(), dotPlot(), bargraph(), and xqqmath()

Could qqmath() and xqqmath() be combined?

and on page 4:

replace histogram(~ heads, ...)
replace densityplot(~ age | sex, ...)
replace bwplot(age ~ substance | sex, ...)
replace xyplot(length ~ width,...)
