### ISSUE TITLE
add date or version number to Minimal R vignette

### ISSUE THREAD

**Issue by nicholasjhorton** [ProjectMOSAIC/mosaic#652]

**Comment by nicholasjhorton** [comment]
Done via https://github.com/ProjectMOSAIC/mosaic/commit/c142f3be3f8b46082ea8b3d8314133cd0279c3e4

I've also made a number of small changes to both vignettes.  It would be great for @rpruim to take a quick read through (since his name is on this).

**Comment by rpruim** [comment]
Pitching `ggformula` in the lattice version:
![image](https://user-images.githubusercontent.com/722231/28395586-1cd1abac-6cc3-11e7-8021-ddd21c02d49d.png)
