### ISSUE TITLE
other suggestions for changes to Minimal R

### ISSUE THREAD

**Issue by nicholasjhorton** [ProjectMOSAIC/mosaic#654]
1) remove merge() from Minimal R Data Transformation?  I was surprised to see it there.

2) change "pbinom()" to "xpbinom()", drop "pnorm()", add "x" before "pchisq()" and friends?

3) remove "read.file()"?

4) remove log10(), abs(), choose(): they are nice but not needed IMHO.

5) drop TukeyHSD() and glm() from inference

Just my $0.02: feel free to incorporate or ignore as you see fit.

**Comment by nicholasjhorton** [comment]
The revisions look great.  Minor comment:

# this package contains data se

is clipped by the end of the column.  How about dropping the comment (and the library(mosaicData)? call?) or rephrasing it?

**Comment by rpruim** [comment]
I'm editing at the moment.  `mosaicData` is already gone.

**Comment by rpruim** [comment]
Just pushed.  A few more edits.

Right now there is mention of `gf_model()` which doesn't exist.  We should remove that if we don't build it ;-)

**Comment by rpruim** [comment]
Note: several of the things you suggest removing are in the b/w sections -- those are optional.
