### ISSUE TITLE
mplot() query (with ggformula)

### ISSUE THREAD

**Issue by nicholasjhorton** [ProjectMOSAIC/mosaic#659]
Shouldn't there be two regression lines?  

![screen shot 2017-07-02 at 1 24 05 pm](https://user-images.githubusercontent.com/530542/27772113-d08ba294-5f29-11e7-9352-81812fb6a418.png)

**Comment by rpruim** [comment]
Since color is not defined in the `ggplot()` call, we need to include `color = ` in the model layers as well.  Easy fix.
