### ISSUE TITLE
should mplot() boxplots be side by side?

### ISSUE THREAD

**Issue by nicholasjhorton** [ProjectMOSAIC/mosaic#660]
They are when using ggplot2 (but not ggformula)
![screen shot 2017-07-02 at 1 27 24 pm](https://user-images.githubusercontent.com/530542/27772151-499a84f2-5f2a-11e7-8972-96f7054955ea.png)

**Comment by rpruim** [comment]
This is a `ggformula` issue.  ust needed to set default position in `gf_boxplot()` to "dodge".  Fixed in `ggformula`.
