### ISSUE TITLE
simplify code emitted by mplot()?

### ISSUE THREAD

**Issue by rpruim** [ProjectMOSAIC/mosaic#661]
If go with the current inheritance mechanism in `ggformula`, we can simplify things a bit in the code emitted by `mplot()`.  This is a reminder to do that once we settle on the `ggformula` behavior.

**Comment by nicholasjhorton** [comment]
I'd hope that this might be feasible (as the present code emitted by mplot() is more intimidating than the equivalent lattice code).

**Comment by rpruim** [comment]
Do you like having `gf_labs()` emitted?  It is there to provide a placeholder for adding a title.

Do we want to add a title input item to the manipulate controls?

**Comment by rpruim** [comment]
We can easily reduce this to the following given the new `ggformula` behavior.  (I just did it.)
```r
gf_point(age ~ cesd, data = HELPrct, color = ~ substance) %>%
gf_lm() %>% 
gf_theme(legend.position = "right") %>% 
gf_labs(title = "")
```
We could omit `gf_theme()` when position is "right", since that is the default, and we can omit `gf_labs()` if we don't want to provide a placeholder for labeling.   Or we could go the other direction and make it
```r
gf_labs(title = "", x = "", y = "", caption = "")
``` 

Just need to decide what we want.  Thought?

**Comment by nicholasjhorton** [comment]
> On Jul 3, 2017, at 10:08 AM, Randall Pruim <notifications@github.com> wrote:
> 
> Do you like having gf_labs() emitted? It is there to provide a placeholder for adding a title.

Yes.
> 
> Do we want to add a title input item to the manipulate controls?

No (it's already too long).  The placeholder works well in my experience.

Nick
> 

Nicholas Horton 
Professor of Statistics
Department of Mathematics and Statistics, Amherst College
PO Box 5000, AC #2239
Amherst, MA 01002-5000

**Comment by rpruim** [comment]
How's this?

```r
gf_point(age ~ cesd, data = HELPrct, color = ~ substance) %>%
gf_lm() %>% 
gf_labs(title = "", x = "", y = "", caption = "")
```

**Comment by nicholasjhorton** [comment]
How about defaulting to the variable names:

gf_point(age ~ cesd, data = HELPrct, color = ~ substance) %>%
gf_lm() %>% 
gf_labs(title = "", x = "cesd", y = "age", caption = "")

**Comment by rpruim** [comment]
Yes.  Being dumb.  We shouldn't be setting x and y.  The defaults are good there.  I'll get that fixed.

**Comment by nicholasjhorton** [comment]
This now looks good to me (and I'll close the issue unless you think otherwise).
