### ISSUE TITLE
RStudio-style cheatsheet for mosaic

### ISSUE THREAD

**Issue by mlaviolet** [ProjectMOSAIC/mosaic#662]
The minimalR vignette and the RJournal article are great resources for instructors, but a similar resource for students is needed. I'd like to suggest a cheatsheet in the RStudio style. _The Student's Guide to R_ would make a good organizing framework. Cheatsheet columns for types of analysis such as _One Quantitative Variable_ could include commands for numerical summaries, graphical summaries, and inference procedures. I hope you'll consider it.

Thanks!

**Comment by nicholasjhorton** [comment]
Thanks for your comment.  I use the Minimal R vignette for my students (just the last two pages) and hand this out early in the semester.  

We'd welcome any contributions of other vignettes along the lines that you suggest if you wanted to draft something.

**Comment by AmeliaMN** [comment]
I'm working on [a cheatsheet comparing R syntaxes](http://www.science.smith.edu/~amcnamara/sds220/handouts/Syntax-cheatsheet.pdf), if that is interesting. I'd love feedback on what else might be useful!

**Comment by dtkaplan** [comment]
That's really nice, Amelia. You might want to think about changing the
formula plotting commands to ggformula.

Regards,
Danny

**Comment by nicholasjhorton** [comment]
I'd be glad to take care of that transition. 

All the best,

Nick

**Comment by mlaviolet** [comment]
I put together a draft for a cheatsheet. For now, I used the lattice graphics but it could easily be adapted to ggformula.

[mosaic-cheatsheet.pptx](https://github.com/ProjectMOSAIC/mosaic/files/1485010/mosaic-cheatsheet.pptx)

**Comment by nicholasjhorton** [comment]
Thanks for your work on this.  It looks like a good start.  I suspect that ggformula would be better than lattice given the direction of the package and the quality of the graphics.  
I wonder whether a second page might allow demonstration of some multivariable displays and multiple regression plotting and use of makeFun().  The existing "Minimal R" vignette has some examples but they could be improved.

**Comment by mlaviolet** [comment]
Thanks for the feedback. The examples you mention could work in a "Part 2" cheatsheet. I agree that ggformula is ultimately the way to go, but there are some lattice graphs I haven't figured out how to duplicate with ggformula (for instance, bar graphs with percentages instead of counts). Thanks again!
