### ISSUE TITLE
consider updating the Graphics with Mosaic vignette to at least mention ggformula

### ISSUE THREAD

**Issue by nicholasjhorton** [ProjectMOSAIC/mosaic#663]
https://github.com/ProjectMOSAIC/mosaic/blob/master/vignettes/GraphicsWithMosaic.Rmd

**Comment by rpruim** [comment]
I think I'll just add this:


You might also like to see the vignette that compares using `lattice` to use `ggformula`,
a formula interface to `ggplot2`.

**Comment by rpruim** [comment]
using, that should be.

**Comment by nicholasjhorton** [comment]
That sounds good to me.
