### ISSUE TITLE
need a new ggformula vignette (or at least mention in the graphics vignette)

### ISSUE THREAD

**Issue by nicholasjhorton** [ProjectMOSAIC/mosaic#664]

**Comment by nicholasjhorton** [comment]
I've stubbed out a lattice/ggformula conversion document that I would propose to include as a new vignette (see https://github.com/ProjectMOSAIC/mosaic/commit/23df4165785c827509236136ec0c153cf573a4e9 and https://github.com/ProjectMOSAIC/mosaic/blob/beta/vignettes/ggformula-lattice.Rmd).  Comments and suggestions welcomed.

**Comment by nicholasjhorton** [comment]
I've pushed some additions to the vignette.

**Comment by rpruim** [comment]
I just surrounded all = with spaces on either side.  (There is a reason the space bar is the biggest key...)

Also changed theme for ggplot2.

**Comment by rpruim** [comment]
I don't like leaving data = to last in complex plots.  The template is `goal( y ~ x, data =, ...)` not `goal(y ~ x, ..., data =)`.

Can we switch this globally in the vignette?

**Comment by nicholasjhorton** [comment]
I don't object.

**Comment by rpruim** [comment]
OK.  I'll do this in a moment.

**Comment by rpruim** [comment]
I like this example, but the long lines are bad.  I've inserted multi-line strings instead.  The only downside is that you have to left justify the second line to avoid getting unwanted white space in the results.
```{r}
gf_point(cesd ~ age, data = HELPrct,
         color = ~ sex) %>%
  gf_lm() %>% 
  gf_theme(legend.position = "top") %>% 
  gf_labs(title = "This is my plot", 
    x = "age (in years)", 
    y = "CES-D measure of
depressive symptoms")
```

**Comment by rpruim** [comment]
@nicholasjhorton, should we close this?  Anything we want to add?  Should there be any additional text.  (After the intro, is basically just code examples comparing the two systems.)

**Comment by nicholasjhorton** [comment]
I'm ready to close this (we can always add to it later).

**Comment by rpruim** [comment]
I've move this vignette to `ggformula`.  That seems like the right place for it.

**Comment by nicholasjhorton** [comment]
That's fine as long as there's a pointer added to this in the mosaic-resources.Rmd file.

**Comment by rpruim** [comment]
Go ahead and add the pointer.  I'll pull it in before submitting.

**Comment by nicholasjhorton** [comment]
What URL should I use?

**Comment by rpruim** [comment]
https://cran.r-project.org/package=ggformula/vignettes/ggformula-lattice.pdf

It will likely throw a bad URL note, but we can explain.  Or I may submit `mosaicCore` and `ggformula` first so `mosaic` can check properly.

**Comment by rpruim** [comment]
Make sure all the other urls have package = syntax.  Although these get redirected (so they are a pain to copy and paste from a browser), CRAN requires this format to avoid NOTES.

**Comment by nicholasjhorton** [comment]
Done via https://github.com/ProjectMOSAIC/mosaic/commit/ea09981abf5a5e11bf5b710c279b52535905bf4f

I'm not sure what URL's you are referring to: can you let me know what else is needed?

**Comment by rpruim** [comment]
Any URLs that refer to files on CRAN associated with a package.

We may be clean already.

**Comment by rpruim** [comment]
Ack.  We may need to revert.  It appears that vignettes cannot use reverse dependencies:

```
Rebuilding ggformula-lattice.Rmd
Failed with error:  'package 'ggformula' required by 'mosaic' could not be found'
Quitting from lines 24-33 (ggformula-lattice.Rmd) 
```
Apparently the `ggformula` package  doesn't exist sufficiently when the vignette tries to load `mosaic`
