### ISSUE TITLE
mplot() simplification re: ggformula

### ISSUE THREAD

**Issue by nicholasjhorton** [ProjectMOSAIC/mosaic#666]
<img width="1125" alt="screen shot 2017-07-16 at 8 50 53 am" src="https://user-images.githubusercontent.com/530542/28247709-fab73594-6a03-11e7-87ad-0d25cf692208.png">

Can mplot() elide the gf_theme() call if there's no color specified?

**Comment by rpruim** [comment]
The logic is more complicated than that, but this is done.

**Comment by nicholasjhorton** [comment]
Thanks!
