### ISSUE TITLE
adjust naming of vignettes?

### ISSUE THREAD

**Issue by nicholasjhorton** [ProjectMOSAIC/mosaic#671]
At present, it looks that there's duplication in the vignettes: is there a way to clarify the names?
<img width="901" alt="screen shot 2017-07-26 at 8 33 23 am" src="https://user-images.githubusercontent.com/530542/28620973-4922805e-71dd-11e7-87ef-8a4fb7602156.png">

**Comment by rpruim** [comment]
That's controlled by 
```
%\VignetteIndexEntry{}
```
Looks like the ggformula/lattice comparison doc was made by copying the header from the Less Volume document.  That explains why that name is duplicated.

The other one is more sensible, we just need to add on something indicating which plotting system is used in each.

**Comment by rpruim** [comment]
![image](https://user-images.githubusercontent.com/722231/29383273-d5707d4c-829d-11e7-913f-53bd6c8b830c.png)
