### ISSUE TITLE
difference in behavior of mplot() vs. plot()

### ISSUE THREAD

**Issue by nicholasjhorton** [ProjectMOSAIC/mosaic#673]
library(mosaic)
fm <- lm(cesd ~ substance + mcs + sex + homeless, data = HELPrct)
mplot(fm, which=4)
plot(fm, which=4)

Note that observation numbers are left off the mplot() version for "which=4".

![screen shot 2017-08-29 at 7 23 41 am](https://user-images.githubusercontent.com/530542/29818596-05bdd6c4-8c8b-11e7-86f1-be462a63df2d.png)

**Comment by rpruim** [comment]
It is nicer if code is in text rather than screen shot.

I'll look and see how much effort this would take.

**Comment by rpruim** [comment]
I've done this for the gg versions

![image](https://user-images.githubusercontent.com/722231/32627509-ac6f78de-c560-11e7-9f97-46c42d1ab504.png)

**Comment by rpruim** [comment]
added some controls over the id labeling.

```r
mplot(fm, id.n = 4, w = 4, multiplot = TRUE, id.nudge = .5, id.size = 3, id.color = "red")
```

![image](https://user-images.githubusercontent.com/722231/32628635-89f24dd2-c564-11e7-972e-af119c5c77b2.png)
