### ISSUE TITLE
add gg option to statTally()

### ISSUE THREAD

**Issue by rpruim** [ProjectMOSAIC/mosaic#679]
Currently the plot use lattice graphics.

**Comment by nicholasjhorton** [comment]
and make it the default?

**Comment by rpruim** [comment]
already is ;-)

**Comment by rpruim** [comment]
Here's the current gg version

![image](https://user-images.githubusercontent.com/722231/31949651-dc339eee-b8a7-11e7-8d07-e337fafffb0c.png)

Would it be better to shade the "less extreme" rather than the "more extreme" portion of the distribution?

**Comment by nicholasjhorton** [comment]
I don't have strong feelings.
