### ISSUE TITLE
xpt() and xqt() commands with the option lower.tail=F causes an error

### ISSUE THREAD

**Issue by userName237** [ProjectMOSAIC/mosaic#682]
After updating the package to the newest version the xpt() and xqt() commands with the option lower.tail=F causes an error.

**Comment by rpruim** [comment]
```r
xpt(0:3, df = 3, lower.tail = FALSE)
## [1] 0.50000000 0.19550111 0.06966298 0.02883444
```
![image](https://user-images.githubusercontent.com/722231/32574630-c9b4859a-c49f-11e7-90bf-08a89dcc2d8a.png)

**Comment by userName237** [comment]
Thanks for looking into this right away! I'm still getting the error (see below for output the pt() command works fine but not the xpt() command) I'll look into what's going on with the setup on my end, but if you have an idea what is going on, any feedback is appreciated.

![image](https://user-images.githubusercontent.com/33492863/32574996-cd52792c-c4a0-11e7-8428-0d4ff04e120d.png)
