### ISSUE TITLE
Q3 is unexpected sometimes in favstats()

### ISSUE THREAD

**Issue by jiyunson** [ProjectMOSAIC/mosaic#688]
Not all the time, but sometimes the Q3 from favstats() is wrong. 
For example:
```favstats(~ mpg, data= mtcars)```
This returns:
min     Q1 median   Q3  max     mean       sd  n missing
 10.4 15.425   19.2 22.8 33.9 20.09062 6.026948 32       0

But we noticed Q3 didn't correspond to the upper hinge on boxplots (in ggformula and ggplot2).
```gf_boxplot(mpg ~ 1, data = mtcars)```
We tried computing the 5 number summary using ```ntile()``` and looking at it with a scatterplot.
```mtcars$mpg.qrt <- as.factor(ntile(mtcars$mpg, 4))```
```gf_point(mpg ~ mpg.qrt, data = mtcars)```
The boxplot and scatterplot look like Q3 should be around 26 (rather than 22.8). 

We also tried ```maggregate()``` which seems to do what ```favstats()``` does.
```maggregate(mpg ~ mpg.qrt, data = mtcars, FUN=min)```

Any ideas as to what is going on?

**Comment by rpruim** [comment]
I think `favstats()` is working just as it should.  `quantile()`, `fivenum()`, and `gf_boxplot()` all agree.

``` r
require(mosaic)
favstats(~ mpg, data= mtcars)
#>   min     Q1 median   Q3  max     mean       sd  n missing
#>  10.4 15.425   19.2 22.8 33.9 20.09062 6.026948 32       0
quantile(mtcars$mpg)
#>     0%    25%    50%    75%   100% 
#> 10.400 15.425 19.200 22.800 33.900
fivenum(mtcars$mpg)
#> [1] 10.40 15.35 19.20 22.80 33.90
gf_boxplot(mpg ~ " ", data = mtcars) %>% gf_labs(x = "")
```

![](https://i.imgur.com/T7cMv8v.png)

PS.  Do you know about `reprex::reprex()`?  That will make it easier to paste examples into github posts.

**Comment by jiyunson** [comment]
The top hinge of the boxplot (in your example) doesn't look like 22.8.

**Comment by jiyunson** [comment]
I'm new to posting stuff on github so thanks for the tip about reprex!

**Comment by jiyunson** [comment]
Oh! Sorry I realize my error! I misinterpreted the notch on the y-intercept! Thanks!

**Comment by rpruim** [comment]
`reprex()` is slick and the default format is for github.  Check it out.
