### ISSUE TITLE
query about MAD

### ISSUE THREAD

**Issue by nicholasjhorton** [ProjectMOSAIC/mosaic#691]
I've always thought that MAD was "median absolute deviation from the median".  But the MAD() function in mosaic is the mean of the deviation of each observation from each other observation.  Is there a citation for the current mosaic defined statistic?

**Comment by rpruim** [comment]
It is used in Tintle *et al* chapter 9.  That's the reason for creating it.  I don't know whether they have a reference to other places it is used.  The help file does mention `stats::mad()`, which does the thing you were expecting, but we can perhaps mention this issue more explicitly.

**Comment by rpruim** [comment]
I looked it up, and `MAD()` gets used in chapter 8 of ISI.  It would be possible to move this function into the `ISIwithR` package if thought it was not generally useful to our primary audience.

**Comment by rpruim** [comment]
I've put this in the documentation:

All pairs mean and sum of absolute differences

**Description**

The functions compute the sum or mean of all pairwise absolute differences. This different from `stats::mad()`, which computes the median absolute difference of each value from the median of all the values. See the `ISIwithR` package (and the textbook it accompanies) for examples using these functions in the context of simulation-based inference.

**Comment by nicholasjhorton** [comment]
This looks great. Only suggestion: “different” should be “differs”.  

All the best,

Nick

**Comment by rpruim** [comment]
This was fixed long ago.  Closing.
