### ISSUE TITLE
xpt() and xqt() suggestion

### ISSUE THREAD

**Issue by jiyunson** [ProjectMOSAIC/mosaic#694]
Hi, we really like how in xpnorm() you can set the mean and standard deviation so that students do not have to do the conversion to z-score. Would it be possible to get a feature like that for xpt() and xqt()? For example, when we ask students to figure out the critical t values for a sampling distribution of means, we have them use xqt() but then they have to multiply that value by standard error. It would be great if we could enter standard error into the function and the t-score would appear (much like how the z-score appears in the plot of xqnorm) and the value in the original units is also in the output (which appears both in the plot and console output of xqnorm).

**Comment by rpruim** [comment]
The usual notation of a t-distribution doesn't have a parameter for center (it's always 0) or for spread (it's determined by the degrees of freedom).  So the situation here is a bit different from the normal distribution.

I'll have to think about whether I like adding this feature.

**Comment by rpruim** [comment]
@dtkaplan @nicholasjhorton : Any thoughts on this.  I'm currently not inclined to change `xpt()` and `xqt()` because I want them to behave like `pt()` an `qt()`.  Is it worth introducing another function for this?  If so, what would it be called?

I'm planning to leave this on the back burner for now.

**Comment by jiyunson** [comment]
Yeah, this is not as important of an issue for us either because we've moved away from the t-distribution in general and have focused more on sampling distributions generated via randomization, bootstrapping, and simulation.

**Comment by nicholasjhorton** [comment]
I'm glad to hear of your move towards resampling inference. Any suggestions that you might have about https://cran.r-project.org/web/packages/mosaic/vignettes/Resampling.pdf would be appreciated.
