### ISSUE TITLE
Problem with xpf() in DataCamp Light

### ISSUE THREAD

**Issue by UCLATALL** [ProjectMOSAIC/mosaic#700]
I'm not sure who could fix this... I run the Mosaic package in DataCamp Light for students. This code works fine in R Studio: xpf(3.305, df1=1, df2=42). However, in DCL it generates this error code: Error: argument is missing, with no default. Any suggestions?

**Comment by nicholasjhorton** [comment]
Is it possible to confirm what version of R and mosaic is running in DataCamp Light?  Can you run "sessionInfo()" and share the output?

**Comment by UCLATALL** [comment]
> sessionInfo()
R version 3.4.0 (2017-04-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.2 LTS

Matrix products: default
BLAS: /usr/lib/libblas/libblas.so.3.6.0
LAPACK: /usr/lib/lapack/liblapack.so.3.6.0

locale:
[1] C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] supernova_1.0     mosaic_1.1.0      Matrix_1.2-8      mosaicData_0.16.0
[5] ggformula_0.6     ggplot2_2.2.1     lattice_0.20-34   dplyr_0.5.0      
[9] RBackend_4.8.6   

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.9        compiler_3.4.0     plyr_1.8.4         tools_3.4.0       
 [5] testwhat_4.3.1     evaluate_0.10.1    praise_1.0.0       tibble_1.2        
 [9] gtable_0.2.0       rlang_0.2.0        DBI_0.5-1          parallel_3.4.0    
[13] ggdendro_0.1-20    Lock5Data_2.8      gridExtra_2.2.1    stringr_1.1.0     
[17] grid_3.4.0         glue_1.2.0         mosaicCore_0.4.0   R6_2.2.0          
[21] tidyr_0.6.0        magrittr_1.5       MASS_7.3-45        scales_0.4.1      
[25] splines_3.4.0      stringdist_0.9.4.2 assertthat_0.1     colorspace_1.3-2  
[29] stringi_1.1.2      lazyeval_0.2.0     munsell_0.4.3      markdown_0.8      
[33] RCompletion_0.1.23 rjson_0.2.15      
>

**Comment by rpruim** [comment]
@UCLATALL, that's not the most recent version of the package, but I don't recall this issue coming up in the past, so I'm not sure if the issue is particular to data camp somehow or just an issue with the old version of `mosaic` or perhaps an old version of some other package.

What happens if you type `traceback()` just after you get the error message?

**Comment by rpruim** [comment]
I should have asked: when you run this in RStudio, what version of the package are you using?

**Comment by UCLATALL** [comment]
@nicholasjhorton The DataCamp Light people updated the version of Mosaic, but that did not solve the problem. Interestingly, xpnorm(1, 0, 1) works as expected. Any ideas would be appreciated.

**Comment by rpruim** [comment]
Any chance we can see the output of `traceback()` so we know which function is generating the error message?

**Comment by UCLATALL** [comment]
I ran ```traceback()``` right after ```xpf()``` and got the result: no traceback available.

**Comment by rpruim** [comment]
I'm not sure how to debug this.  I've done very little with data camp.  Is there a simple way for me to recreate the problem in data camp?

**Comment by UCLATALL** [comment]
You can use this link to get a DataCamp window with the mosaic package
pre-installed. You can try out various R commands, then try ```xpnorm```
(which works) and ```xpf``` (which does not).
https:///uclatall.github.io/intro-stats-modeling/data-camp/sandbox-400.html

**Comment by rpruim** [comment]
I tracked this down to a change in behavior in `tibble::data_frame()`.  The version on data camp is 1.2.  The version on my machine is 1.4.2.

That said, I think I can adjust the code in `mosaic:::plot_multi_dist()` so that it works with either version of `tibble`.

**Comment by rpruim** [comment]
I've implemented the fix in the `beta` branch.

**Comment by UCLATALL** [comment]
@rpruim Thanks so much for this! Can you tell me how to tell DataCamp to install the fix? I'm assuming that updating from CRAN is not an option yet. They typically ask for an R or bash command that will do the install. Thanks.

**Comment by rpruim** [comment]
I think you have two options:

 1. update the version of `tibble`
 2. update the version of `mosaic`

For the moment, updating `mosaic` would require working from the beta branch on github

```r
devtools::intall_github("ProjectMOSAIC/mosaic", ref = "beta")
```
but I expect that this will get merged into `master` soon and that the next CRAN release is not far off either.

You can update `tibble` with

```r
install.packages("tibble")
```
Version 1.4.2 is the one currently on CRAN.
