### ISSUE TITLE
update mosaic markdown templates to use ggformula

### ISSUE THREAD

**Issue by nicholasjhorton** [ProjectMOSAIC/mosaic#706]
1) prune some of the extra lines at the top
2) remove the lattice configuration
3) replace xyplot() with gf_point()

**Comment by rpruim** [comment]
There is a template in `ggformula` (fancy only at this point).  I see it has a bit of lattice cruft that we could decide to remove.

We should coordinate the efforts between `mosaic` and `ggformula`.

**Comment by nicholasjhorton** [comment]
I hope that we can decide to make this summer the time to make the push to ggformula and deprecate the lattice routines.  ggformula is a clear win and the lattice references are now distracting.

**Comment by nicholasjhorton** [comment]
I've made my proposed changes via https://github.com/ProjectMOSAIC/mosaic/commit/0e860261d194449b914d32078acc99da29d99860

Feel free to incorporate or ignore as you see fit.

I didn't update the Shiny template.  I don't think that is working and since no one has noticed, might propose it for deletion.
