### ISSUE TITLE
late june CRAN mosaic release with updated documentation?

### ISSUE THREAD

**Issue by nicholasjhorton** [ProjectMOSAIC/mosaic#708]
I anticipate that the updated vignettes, mosaic resources, and textbook materials (SDM4, IS5, IPS9) will be ready to be included in a CRAN mosaic release.  

Can we plan to do this on or around the 1 month anniversary of the current version (which went to CRAN on 2018-05-23)?

**Comment by rpruim** [comment]
We need to get things to CRAN (espeically ggformula) prior to the release of ggplot2 on June 24 (I think that is the target date.)
