### ISSUE TITLE
update mosaic-resources with fastR2

### ISSUE THREAD

**Issue by nicholasjhorton** [ProjectMOSAIC/mosaic#710]
* *Foundations and Applications of Statistics: An Introduction Using R* (R Pruim)
is an R-infused probability and mathematical statistics text that emphasizes
connections between probability and statistics. The book predates the `mosaic` package,
but much of the code originally in the `fastR` package has been moved into the `mosaic` package.

See needed changes in https://github.com/ProjectMOSAIC/mosaic/blob/master/vignettes/mosaic-resources.Rmd

**Comment by rpruim** [comment]
Updated to this:

* Foundations and Applications of Statistics: An Introduction Using R (R Pruim, second edition) is an R-infused probability and mathematical statistics text that emphasizes connections between probability and statistics. The first edition of the book predates the mosaic package, but much of the code originally in the fastR package has been moved into the mosaic package. The second edition is supported by the fastR2 package and uses ggformula for plotting.

    * https://bookstore.ams.org/amstext-28
    * www.ams.org/publications/authors/books/postpub/amstext-28
