### ISSUE TITLE
Bugs in gf_dotplot?

### ISSUE THREAD

**Issue by mlaviolet** [ProjectMOSAIC/mosaic#711]
I've noticed some odd behavior in `gf_dotplot` (version 1.3.0).

```
gf_dotplot(~ cesd, data = HELPrct)
gf_dotplot(~ cesd | sex, data = HELPrct)
gf_dotplot(~ cesd | sex, data = HELPrct, binwidth = 10)
```
The y-axis shows density, but the default label is "count."
The y_axis scale is fixed at the unit interval, resulting in dead space in the plot.
The `binwidth` argument behaves like `size`; that is, changing `binwidth` doesn't change the bins, only the size of the dots.

Please clarify. Thanks!

**Comment by rpruim** [comment]
These are simply known behaviors of `ggplot2`.   See https://github.com/tidyverse/ggplot2/issues/2203

Note:

 * the scale is not "density" in the usual sense.

 * `binwidth` does do more than change the size of the dots.  Compare `binwidth = 1` to `binwidth = 10` in your example to see.

Unfortunately, dotplots in `ggplot2` are only barely usable (or require some finicky work).  The main issue is that what makes a good dotplot is not independent of the aspect ratio of the plot as rendered.
And that makes some of these things a bit orthogonal to the way `ggplot2` is designed.

**Comment by rpruim** [comment]
See #712 for possible additions to documentation.
