### ISSUE TITLE
Add warning section to documentation for `gf_dotplot()`

### ISSUE THREAD

**Issue by rpruim** [ProjectMOSAIC/mosaic#712]
dotplots in `ggplot2` are not ideal (https://github.com/tidyverse/ggplot2/issues/2203).  `ggformula` inherits some of these traits.  

We could add a section to the documentation saying a bit more about the y-axis and the sorts of fiddling one typically needs to do to tune the plot.

**Comment by mlaviolet** [comment]
That would be very helpful. Thanks for the prompt response.
