### ISSUE TITLE
mplot ignores "system" argument when plotting "TukeyHSD" objects

### ISSUE THREAD

**Issue by mlaviolet** [ProjectMOSAIC/mosaic#716]
Reproducing the examples in the `mplot` documentation and the new Student's Guide, I was unable to create the ggplot graph on page 68. The function produces the lattice graph whether `method` is set to `"ggplot"` or nothing. The issue appears limited to `"TukeyHSD"` objects.

```
HELPrct <- mutate(HELPrct, subgrp = factor(substance, 
  levels = c("alcohol", "cocaine", "heroin"), labels = c("A", "C", "H")))
mod <- lm(cesd ~ subgrp, data = HELPrct)
HELPHSD <- TukeyHSD(mod, "subgrp")
mplot(HELPHSD, system = "ggplot2")
```

![rplot](https://user-images.githubusercontent.com/16492351/42717842-eb8c415e-86d1-11e8-8327-ec42d1696cf0.png)

**Comment by rpruim** [comment]
Hmm... Looks like there is a missing `return()`.  I've fixed it locally and will push to Github shortly.

Thanks for the notification.

``` r
library(mosaic)
TukeyHSD(cesd ~ substance, data = HELPrct) %>% mplot() %>%
  gf_refine(scale_color_viridis_c(end = 0.8, option = "A"))
```

![](https://i.imgur.com/C9ycdc4.png)

Created on 2018-07-14 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).
