### ISSUE TITLE
color choices in xpnorm() and related functions

### ISSUE THREAD

**Issue by nicholasjhorton** [ProjectMOSAIC/mosaic#717]
library(mosaic)
xpnorm(1.96)

Is this a good choice in terms of color blindness?

<img width="649" alt="screen shot 2018-08-07 at 8 38 19 am" src="https://user-images.githubusercontent.com/530542/43776260-4602be0c-9a1d-11e8-9ba9-0c3dcb03ca90.png">

![screen shot 2018-08-07 at 8 39 50 am](https://user-images.githubusercontent.com/530542/43776332-7f4f9f2c-9a1d-11e8-9aa6-81cf2ec1116a.png)

**Comment by rpruim** [comment]
![image](https://user-images.githubusercontent.com/722231/43803713-949f4810-9a67-11e8-9f10-8cb816b139ec.png)
