### ISSUE TITLE
warnings and drek in "ggformula-lattice.pdf"

### ISSUE THREAD

**Issue by nicholasjhorton** [ProjectMOSAIC/mosaic#720]
<img width="979" alt="screen shot 2018-09-04 at 4 44 18 pm" src="https://user-images.githubusercontent.com/530542/45056785-e0861500-b061-11e8-8011-6f5660c427fd.png">

**Comment by nicholasjhorton** [comment]
I've had students comment on this: is it possible to push an update to CRAN to address the problem?

**Comment by rpruim** [comment]
In the meantime, you can point them here: https://projectmosaic.github.io/mosaic/articles/ggformula-lattice.html

**Comment by rpruim** [comment]
I'm moving toward using this as our primary place to point people because

 * we can update it without going to CRAN, so updates can be immediate
 * it is a nicer way to navigate the information
 * examples include the output (see the "reference" section

I'll see whether we are ready for another CRAN update.

**Comment by nicholasjhorton** [comment]
That's fine with me.  My only concern is that it will break links that people have to the pdf versions of these materials.

Nikc

> On Sep 28, 2018, at 7:48 AM, Randall Pruim <notifications@github.com> wrote:
> 
> I'm moving toward using this as our primary place to point people because
> 
> 	• we can update it without going to CRAN, so updates can be immediate
> 	• it is a nicer way to navigate the information
> 	• examples include the output (see the "reference" section
> I'll see whether we are ready for another CRAN update.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Nicholas Horton 
Beitzel Professor of Technology and Society (Statistics and Data Science)
Amherst College

**Comment by rpruim** [comment]
We definitely want the PDF to build correctly as well.

**Comment by rpruim** [comment]
I did some clean up of the PDF and it compiles locally for me without the dreck.  We'll have to see if that is the case when it is auto-built during package install.
