### ISSUE TITLE
Negative value in CIAdata()?

### ISSUE THREAD

**Issue by luebby** [ProjectMOSAIC/mosaic#725]
``` r
> CIAdata("migr") %>% filter(country=="Afghanistan")
Retrieving data from https://www.cia.gov/library/publications/the-world-factbook/rankorder/rawdata_2112.txt
      country migr
1 Afghanistan  0.9
```

But [https://www.cia.gov/library/publications/the-world-factbook/fields/2112.html](https://www.cia.gov/library/publications/the-world-factbook/fields/2112.html):

> Afghanistan | -0.9 migrant(s)/1,000 population (2017 est.)

I guess this is due to a missing `-` in line 32 of `CIAdata()` at least
```r 
table[[2]] = as.numeric(gsub("[^.+-[:digit:] ]", "", table[[2]]))
```
seems to fix it for me.

**Comment by rpruim** [comment]
Thanks for pointing this out (and Merry Christmas).

I've decided to fix this using `readr::parse_number()`.

```r
library(mosaic)
CIAdata("migr") %>% filter(country=="Afghanistan")
## Retrieving data from https://www.cia.gov/library/publications/the-world-factbook/rankorder/rawdata_2112.txt
## Loading required namespace: RCurl
##       country migr
## 1 Afghanistan -0.9
```
