### ISSUE TITLE
mosaic::confint() options

### ISSUE THREAD

**Issue by nicholasjhorton** [ProjectMOSAIC/mosaic#726]
library(mosaic)
mod <- lm(pcs ~ mcs, data = HELPrct)
confint(mod, conf.level = 0.90)  # gives 95% interval, since correct option is "level"
confint(mod, level = 0.90)

Does it make sense to add an additional option for mosaic::confint() that accepts "conf.level" as an alias for "level"?

**Comment by rpruim** [comment]
The generic for `confint()` is defined in the stats package where the signature is set as
``` r
confint
#> function (object, parm, level = 0.95, ...) 
#> UseMethod("confint")
#> <bytecode: 0x7ff9c897d770>
#> <environment: namespace:stats>
```

<sup>Created on 2019-01-10 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

We could add an alias to each of the methods we define, but it would not work globally, only where we have created new methods.  That could lead to errors in other situations, so I'm not sure it is worth it.

**Comment by nicholasjhorton** [comment]
I concur with @rpruim.  I suggest instead that we include examples of changing the confidence level in some of our examples to make this more obvious.

**Comment by rpruim** [comment]
`example(confint)` already includes one such example.

**Comment by rpruim** [comment]
I had another idea:

``` r
 library(mosaic)
confint(rnorm(100), conf.level = 0.90)

#> Error in confint.numeric(rnorm(100), conf.level = 0.9):  Use `level` to set the confidence level, not `conf.level`.
```

<sup>Created on 2019-01-10 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by nicholasjhorton** [comment]
I like it!

All the best,

Nick
