### ISSUE TITLE
update ExtraDocs/LessVolume-MoreCreativity.Rmd

### ISSUE THREAD

**Issue by nicholasjhorton** [ProjectMOSAIC/mosaic#728]
I've made a first pass at changes.  

@rpruim can you please review the changes to https://github.com/ProjectMOSAIC/mosaic/blob/beta/ExtraDocs/LessVolume-MoreCreativity.Rmd (and merge into master once you have done so?

**Comment by rpruim** [comment]
There was a mix of lattice and ggformula.  I'm coverting all to ggformula.  Also adding `df_stats()` examples.
