### ISSUE TITLE
More Errors in pdist

### ISSUE THREAD

**Issue by killereins** [ProjectMOSAIC/mosaic#737]
According to issue #736 there are more bugs (inconsistencies) in the (x)pdist - command family:

library(mosaic) #latest vers.
xpnorm(3,  xlim = c(2, 4))
xpt(41.944,df=4, ncp=0, xlim=c(41,43))
xpchisq(41.944,df=4, ncp=0, xlim=c(41,43))
xpf(41.944,df1=4,df2=3, ncp=0, xlim=c(41,43))
In previous mosaic vers. all the above "zooms" were working very well after adding
the "default" ncp=0 - in the latest vers. 1.5.0
xpchisq stopped with the error message:
Error in xpchisq(41.944, df = 4, ncp = 0, xlim = c(41, 43)) : 
  unused argument (xlim = c(41, 43))

**Comment by rpruim** [comment]
When we added explicit arguments to these functions, ... was accidentally deleted in a couple places.

Examples above all work now.

``` r
suppressPackageStartupMessages(library(mosaic))
xpt(41.944,df=4, ncp=0, xlim=c(41,43))
```

![](https://i.imgur.com/8eo5HWH.png)

    #> [1] 0.999999
    xpchisq(41.944,df=4, ncp=0, xlim=c(41,43))

![](https://i.imgur.com/0SIlopJ.png)

    #> [1] 1
    xpf(41.944,df1=4,df2=3, ncp=0, xlim=c(41,43))

![](https://i.imgur.com/nn141UW.png)

    #> [1] 0.9942406

<sup>Created on 2019-03-12 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

Note: `reprex::reprex()` is very handy for providing reproducible examples for github issues.

**Comment by killereins** [comment]
Hi rpruim,
thanks a lot. Very fast!
Best regards
