### ISSUE TITLE
query about the behavior of qdata()

### ISSUE THREAD

**Issue by nicholasjhorton** [ProjectMOSAIC/mosaic#738]
I'm not wild about the return value for qdata(), which depends on how many quantiles are given:

``` r
library(mosaic); x <- rnorm(100); qdata(~ x, c(0.05, 0.95))$quantile; qdata(~ x, 0.05)$quantile

#> [1] -1.822249  1.379704
#> Error in qdata(~x, 0.05)$quantile: $ operator is invalid for atomic vectors
#> [1] -1.822249  1.379704
```

<sup>Created on 2019-03-25 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by rpruim** [comment]
It is an easy enough fix.  The only questions are

 * was there a reason we did it this way once upon a time?
 * does this break anything we don't want to break?

``` r
suppressPackageStartupMessages(library(mosaic))
x <- rnorm(100)
qdata(~x, 0.9) %>% class()
#> [1] "data.frame"
qdata(~x, c(0.8, 0.9)) %>% class()
#> [1] "data.frame"
qdata(~x, 0.9)$quantile
#> [1] 1.368128
qdata(~x, c(0.8, 0.9))$quantile
#> [1] 0.743970 1.368128
```

<sup>Created on 2019-03-26 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by nicholasjhorton** [comment]
Thanks for this fix.

More generally I'm not wild about qdata() returning what it does: doesn't the documentation state that it returns "For qdata, a vector of quantiles"?  That's not what quantile() returns, is it?

``` r
suppressPackageStartupMessages(library(mosaic)); qdata(~ rnorm(100), c(.05, .95)); quantile(rnorm(100), c(.05, .95))
#>      quantile    p
#> 5%  -1.753222 0.05
#> 95%  1.642827 0.95
#>        5%       95% 
#> -1.801939  1.646743
```

<sup>Created on 2019-03-26 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by rpruim** [comment]
So now the questions is whether we we want `qdata` and `cdata` to return the same type of thing.  Since `cdata()` returns both upper and lower limits, the data frame approach makes more sense there (and there is probably no reason to use a named vector when only one value is requested).

`qdata()` could return a vector (named or unnamed) if that's what we prefer.

In any case, we should make the documentation match what we decide to do.

**Comment by rpruim** [comment]
I think this is the solution that @nicholasjhorton is proposing:

``` r
suppressPackageStartupMessages(library(mosaic))
x <- rnorm(100)
qdata(~x, 0.9) %>% class()
#> [1] "numeric"
qdata(~x, c(0.8, 0.9)) %>% class()
#> [1] "numeric"
qdata(~x, 0.9)
#>      90% 
#> 1.182913
qdata(~x, c(0.8, 0.9))
#>       80%       90% 
#> 0.7128433 1.1829134
cdata(~x, 0.9) %>% class()
#> [1] "data.frame"
cdata(~x, c(0.8, 0.9)) %>% class()
#> [1] "data.frame"
cdata(~x, 0.9)
#>         low       hi central.p
#> 5% -1.64285 1.403338       0.9
cdata(~x, c(0.8, 0.9))
#>           low       hi central.p
#> 10% -1.045226 1.182913       0.8
#> 5%  -1.642850 1.403338       0.9
```

<sup>Created on 2019-03-26 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by rpruim** [comment]
While we are changing things, I'm inclined to make the names for `cdata()` be "lo" and "hi".   Other options would be "low" and "high" or "lower" and "upper".  But "low" and "hi" seems like a poor choice on my part.

I use "lo" and "hi" in my CalvinBayes package for HDIs because it keeps downstream plotting commands shorter.  But that's likely less of an issue here.

**Comment by rpruim** [comment]
Circling back to this.  I've current got things named "lower" and "upper".  @nicholasjhorton this is your last chance to express an opinion on naming.

``` r
suppressPackageStartupMessages(library(mosaic))
x <- rnorm(100)
qdata(~x, 0.9) %>% class()
#> [1] "numeric"
qdata(~x, c(0.8, 0.9)) %>% class()
#> [1] "numeric"
qdata(~x, 0.9)
#>     90% 
#> 1.31129
qdata(~x, c(0.8, 0.9))
#>       80%       90% 
#> 0.6840699 1.3112903
cdata(~x, 0.9) %>% class()
#> [1] "data.frame"
cdata(~x, c(0.8, 0.9)) %>% class()
#> [1] "data.frame"
cdata(~x, 0.9)
#>       lower    upper central.p
#> 5% -1.52867 1.678774       0.9
cdata(~x, c(0.8, 0.9))
#>         lower    upper central.p
#> 10% -1.308928 1.311290       0.8
#> 5%  -1.528670 1.678774       0.9
```

<sup>Created on 2019-08-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by nicholasjhorton** [comment]
Looks good to me.
