### ISSUE TITLE
Less Volume URL in mosaic-resources still references lattice functions

### ISSUE THREAD

**Issue by nicholasjhorton** [ProjectMOSAIC/mosaic#739]
see "Less Volume" link in https://cran.r-project.org/web/packages/mosaic/vignettes/mosaic-resources.html

**Comment by rpruim** [comment]
Interestingly, the Rmd file has already been updated to use ggformula, so I think the issue is with the rawgit URL.  

I'm going to try just moving this into vignettes in the normal way.  I don't recall anymore what issue we were trying to resolve by handling it in a different way years ago.

**Comment by rpruim** [comment]
I've moved two things from ExtraDocs into vignettes and updated the resources vignette to reflect the change.
