### ISSUE TITLE
issues with mplot() in mosaic 1.6.0

### ISSUE THREAD

**Issue by nicholasjhorton** [ProjectMOSAIC/mosaic#754]
Should look like this (but it doesn't): possible lazy eval issues?
<img width="1460" alt="PastedGraphic-16" src="https://user-images.githubusercontent.com/530542/78034514-d4ddfb80-7335-11ea-8629-ca365c9ae3d6.png">

**Comment by rpruim** [comment]
Pending some testing, I think this is fixed now.

**Comment by nicholasjhorton** [comment]
This is working on my end: thanks for your fix!
