### ISSUE TITLE
add Amy Wagaman's STAT2 materials using mosaic to list of resources?

### ISSUE THREAD

**Issue by nicholasjhorton** [ProjectMOSAIC/mosaic#756]
https://awagaman.people.amherst.edu/stat230/

see Rmd and pdf at the above link.

https://cran.r-project.org/web/packages/mosaic/vignettes/mosaic-resources.html

**Comment by dtkaplan** [comment]
I don't see any Rmd or pdf files at the awagaman.people.amherst.edu link.
Is that the address you intended?

- Danny

**Comment by nicholasjhorton** [comment]
The filename was clipped, here's a pointer to the Rmd file: https://awagaman.people.amherst.edu/stat230/Stat230CodeCompilationExampleCodeUsingNHANES.Rmd

**Comment by rpruim** [comment]
Perhaps this belongs in the documentation of NHANES either instead of here or in addition to here.

**Comment by rpruim** [comment]
Is there a better URL?  The one given just sends you to a bare Rnw file.  Also, the link should be fairly stable so we don't have to update it each time we submit the package.

**Comment by rpruim** [comment]
Looks like this is the URL to use: <https://awagaman.people.amherst.edu/stat230/Stat230CodeCompilationExampleCodeUsingNHANES.pdf>
