### ISSUE TITLE
Remove some vignettes from the package

### ISSUE THREAD

**Issue by rpruim** [ProjectMOSAIC/mosaic#758]
CRAN is balking because of the size of the package.  Most of the size comes from our documentation.  An easy fix is to remove most of this from the package and have people access from <https://projectmosaic.github.io/mosaic/>

**Comment by dtkaplan** [comment]
Yes. That's the direction everyone will have to move in.

- Danny

**Comment by rpruim** [comment]
If/when we have time, it might be worth writing a new "main vignette" for the package.   For the moment I'm leaving the resources vignette and Minimal R in and moving the rest to https://projectmosaic.github.io/mosaic/
