### ISSUE TITLE
version bump for the fall?

### ISSUE THREAD

**Issue by nicholasjhorton** [ProjectMOSAIC/mosaic#768]
@rpruim is this a good time to merge in changes and submit to CRAN for the start of the fall semester?  We're starting next week and I know that others are already moving forward.  (Or perhaps just merge beta into master so people get it by default if they install from GitHub?). Thanks as always for your efforts.

**Comment by rpruim** [comment]
beta and master are already the same:

![image](https://user-images.githubusercontent.com/722231/90521962-2518f700-e139-11ea-914f-28d0ea889f2e.png)

**Comment by rpruim** [comment]
Is a new PR for the resampling vignette coming?
