### ISSUE TITLE
antiD

### ISSUE THREAD

**Issue by sciencecasey** [ProjectMOSAIC/mosaic#771]
I'm using R Studio with mosaic and it says "could not find function antiD".   
I tried searching the help documents and copying code directly from examples online.  The help browser doesn't find antiD either, though D works fine.  Mosaic is loaded including dependencies.

**Comment by nicholasjhorton** [comment]
Sorry for the complications.

This function has moved into the `mosaicCalc` package:

```
> library(mosaicCalc)
> find("antiD")
[1] "package:mosaicCalc"
```

**Comment by dtkaplan** [comment]
I'll suggest  you  install  the beta  version of `mosaicCalc`,  which has a vignette.
```
remotes::install_github("ProjectMosaic/mosaicCalc", ref = "beta",  build_vignettes = TRUE)
```

**Comment by sciencecasey** [comment]
Thank you! I downloaded it and it works :)
