### ISSUE TITLE
prop.test won't take table as an input

### ISSUE THREAD

**Issue by staceyhancock** [ProjectMOSAIC/mosaic#773]
Hi @rpruim,

This semester, we're trying to use R for the first time in our intro stat course. I was using the default `prop.test()` function with a table as an input to perform a two-proportion hypothesis test. However, once I load the `mosaic` package, the `prop.test()` function no longer works:

```
survival <- factor(c(rep("Survived", 25), rep("Died", 65)), 
     levels = c("Survived","Died"))
group <- factor(rep.int(c("control", "treatment", "control", "treatment"), times = c(11, 14, 39, 26)), 
     levels = c("treatment", "control"))
cpr <- data.frame(survival, group)

data_tbl <- table(cpr$survival, cpr$group)

stats::prop.test(data_tbl)  # Works!
mosaic::prop.test(data_tbl)  # Error that argument "n" is missing
```

Any idea how to get around this? I ended up just always using `stats::prop.test()` when I call the function, but that presents an added item of confusion for students.

**Comment by rpruim** [comment]
Thanks fore reporting the bug.  Not sure how long this bug has been there since I've never tried to give `prop.test()` a 2-way table, but it wasn't too hard to fix.

```r
prop.test(data_tbl)
## 
## 	2-sample test for equality of proportions with continuity correction
## 
## data:  data_tbl
## X-squared = 1.2801, df = 1, p-value = 0.2579
## alternative hypothesis: two.sided
## 95 percent confidence interval:
##  -0.09582662  0.41582662
## sample estimates:
## prop 1 prop 2 
##   0.56   0.40 
```

On github now.  Will be on CRAN at next update there.

**Comment by staceyhancock** [comment]
Thanks for the quick fix, @rpruim!
