### ISSUE TITLE
Remove calls of order() applied to data frame

### ISSUE THREAD

**Issue by rpruim** [ProjectMOSAIC/mosaic#774]
From CRAN:

You may have seen that when running your package code with current
r-devel, one gets warnings about

 cannot xtfrm data frames

This is because you call order() on a data frame with k rows and 1
column which (currently) returns something of length k.

Now,

? sort says

    Sort (or _order_) a vector or factor (partially) into ascending or
    descending order.  For ordering along more than one variable,
    e.g., for sorting data frames, see ‘order’

where in turn ? order says

    ‘order’ returns a permutation which rearranges its first argument
    into ascending or descending order, breaking ties by further
    arguments.  ‘sort.list’ does the same, using only one argument.
    See the examples for how to use these functions to sort data
    frames, etc.

and then the examples clearly explain to use do.call() for data
frames, ideally also unnaming to avoid name clashes.

Can you please change your package code to no longer call order() on
data frames?

Please submit a new version after 2021-01-04 but before 2021-01-15.

Happy Holidays,
-k

**Comment by rpruim** [comment]
Looks like this arises in `.sort()` an internal, undocumented functions used by `findZeros()`:

```{r}
  if(type == 'byx'){
    return(data[order(data[1]),])
  }
  
  if(type == 'byy'){
    return(data[order(data[2]),])
  }
 ```

It looks to me like using `data[[1]]` and `data[[2]]` would work in the case that `data` is a data frame, but I haven't investigated enough to know whether that is guaranteed.  Perhaps I'll throw in a test using `inherits`.

@dtkaplan, do you have any additional info?

**Comment by rpruim** [comment]
Or perhaps `data$x` and `data$y` would be correct?  Analogous to `data$angle` in the next case.

**Comment by rpruim** [comment]
Since I haven't heard anything from @dtkaplan and my solution appears to resolve the issues, I'm going to stick with that for now.

**Comment by dtkaplan** [comment]
Thanks, Randy.
