### ISSUE TITLE
mislabeling of y-axis for mplot(MODEL, which = 1)

### ISSUE THREAD

**Issue by nicholasjhorton** [ProjectMOSAIC/mosaic#776]
``` r
suppressPackageStartupMessages(library(mosaic))
mod_temp <- lm(volume ~ avgtemp, data = RailTrail)
mplot(mod_temp, which = 1)  # displays standardized residuals, labeled as residuals
#> `geom_smooth()` using formula 'y ~ x'
```

![](https://i.imgur.com/gKkr8fO.png)

``` r
plot(mod_temp, which = 1)  # compare to standard plot
```

![](https://i.imgur.com/CMzYDJR.png)

<sup>Created on 2021-01-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by rpruim** [comment]
Given your examples, I think it is the data not the label that need to change.

``` r
suppressPackageStartupMessages(library(mosaic))
mod_temp <- lm(volume ~ avgtemp, data = RailTrail)
mplot(mod_temp, which = 1)  # displays standardized residuals, labeled as residuals
#> `geom_smooth()` using formula 'y ~ x'
```

![](https://i.imgur.com/ynldhxJ.png)

<sup>Created on 2021-01-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Should we use singular or plural?  I'm opting for singular for now.

**Comment by nicholasjhorton** [comment]
Thanks for fixing the plot to display residuals instead of standardized residuals! 

I would make both plural (to match `graphics::plot(MOD, which = 1)`)

**Comment by rpruim** [comment]
Plural matches, but I'm not sure it is correct.  Usually we label axes with a singular (the thing each dot represents).  I don't like to encourage naming variables with plural or labeling plots that way.

**Comment by rpruim** [comment]
Note: the base R function is not consistent: It uses "Cook's distance", not "Cook's Distances".  Same for "Leverage"

I'm going to make everything singular unless I see a compelling reason why plural is better.

**Comment by rpruim** [comment]
I'm reopening this because I think this change introduced a bug.  We are using `broom::augment()` to create a data frame with residuals.  Turns out, broom doesn't always include `.resid` for all types of models. I'm not sure it is well documented just what `broom::augment()` returns when, but here is an example that fails.

``` r
suppressPackageStartupMessages(library("mosaic"))
model <- lm( temp ~ sqrt(time), data = CoolingWater)
model %>% broom::augment() %>% head(3)
#> # A tibble: 3 x 7
#>    temp `sqrt(time)` .fitted .std.resid   .hat .sigma .cooksd
#>   <dbl>        <dbl>   <dbl>      <dbl>  <dbl>  <dbl>   <dbl>
#> 1  98.2         0       82.6       3.60 0.0398   4.30   0.269
#> 2  94.4         1       78.3       3.70 0.0330   4.29   0.233
#> 3  91.4         1.41    76.6       3.41 0.0304   4.31   0.182
mplot(model, which = 1)
#> Error in FUN(X[[i]], ...): object '.resid' not found
```

<sup>Created on 2021-01-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

This seems to be related to the transformation in the model.  If we remove `sqrt()` from the model above, things work.

``` r
suppressPackageStartupMessages(library("mosaic"))
model <- lm(temp ~ time, data = CoolingWater)
model %>% broom::augment() %>% head(3)
#> # A tibble: 3 x 8
#>    temp  time .fitted .resid .std.resid   .hat .sigma .cooksd
#>   <dbl> <dbl>   <dbl>  <dbl>      <dbl>  <dbl>  <dbl>   <dbl>
#> 1  98.2     0    64.3   33.9       4.60 0.0179   7.09   0.193
#> 2  94.4     1    64.1   30.3       4.12 0.0177   7.16   0.152
#> 3  91.4     2    63.8   27.6       3.74 0.0174   7.22   0.124
mplot(model, which = 1)
#> `geom_smooth()` using formula 'y ~ x'
```

![](https://i.imgur.com/kE40y6m.png)

<sup>Created on 2021-01-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by rpruim** [comment]
I'm going to close this.  If `broom::augment()` doesn't include `.resid`, I'm adding that in using `resid(model)` to get the residuals.
