### ISSUE TITLE
mplot()

### ISSUE THREAD

**Issue by nicholasjhorton** [ProjectMOSAIC/mosaic#777]
My students have been confused about the multiple uses of "mplot()".

I agree that they are very different.  

Would something like "interactive_plot(DATASET)" by a better name for the interactive plotter?

Would something like "model_plot(MODEL)" be a better name for the diagnostic plotter?

I'm terrible at naming, as @rpruim knows far too well.  But I wanted to raise the question.

**Comment by rpruim** [comment]
It is easy enough to include an alias so we have multiple names.

`interactive_plot()` is OK, although we don't really interact with the plot itself (as you would with {plotly}, we just have an interactive way to create a static plot.

Maybe `create_plot()`? or `design_plot()`?  Not sure what name we want, but if we settle on one, I can add that to the release planned for later today.

Side note: We already have a separate function for this, called `mPlot()`.  That's a bit of a legacy, and we don't really want people calling that, but it makes it super easy to create a function that only handles the manipulate part of `mplot()`.

For the other uses, I think of `mplot()` as the mosaic version of `plot()`.  It defaults to `plot()` whenever we have not defined something.  So I'm not as excited about coming up with a new name in that case -- at least not one for a special case, like models.
