### ISSUE TITLE
Changing colors and background

### ISSUE THREAD

**Issue by shadrackkibet** [ProjectMOSAIC/mosaic#780]
Is it possible to change colours, background (theme) in the following plot? if yes how can I change in the following code?

```
qdist("norm", seq(.1, .9, by = 0.10), 
      title ="Deciles of a normal distribution", show.legend = TRUE,
      pattern = "stripes")
```

![image](https://user-images.githubusercontent.com/26301973/107204622-f0159f00-6a0d-11eb-88f8-7e5e322a6302.png)

**Comment by rpruim** [comment]
You can use `gf_theme()` to change the theme for a single plot or `set_theme()` to change the default theme.
