### ISSUE TITLE
At what point do we force R 4.1 and start using |> ?

### ISSUE THREAD

**Issue by rpruim** [ProjectMOSAIC/mosaic#785]
If we use `|>` in our code or in our examples, then we pretty much force users to move to 4.1.  So the question is when to make that shift.

**Comment by nicholasjhorton** [comment]
My suggestion would be May, 2022. That would ensure that even laggards (e.g., Linux distros) would be caught up.

**Comment by rpruim** [comment]
That seems reasonable.

**Comment by rpruim** [comment]
done.
