### ISSUE TITLE
SaratogaHouses help file typo

### ISSUE THREAD

**Issue by lizheywood** [ProjectMOSAIC/mosaic#787]
There is a dataset in this library titled SaratogaHouses.  The help file (?SaratogaHouses) associated with it has a typo in one of the column names.  One of the columns is **Fireplaces** and the help file is spelled 'firplaces'.

Thank you!

**Comment by nicholasjhorton** [comment]
Thanks for alerting us to this issue. I've fixed the error:

https://github.com/ProjectMOSAIC/mosaicData/commit/cf8a5352a0fea8432ef08ee1773a111678baac23
