### ISSUE TITLE
Help: Troubles about installing the mosaic library

### ISSUE THREAD

**Issue by databeej2w** [ProjectMOSAIC/mosaic#790]
Hi! 

I am a lecturer teaching Introductory Statistics. I have been using the mosaic library in class since 2016. 
The greatest part of the mosaic library I think is that it allows finding numerical summaries of data by group.
The syntax is so simple, intuitive, and easy to remember than the "tapply()" in base R.
However, the installation of the mosaic library is very unstable. Every year, there are always students in my class that have trouble installing the mosaic library and I couldn't figure out what's the problem. Often the error message is like some package is not installed. The mosaic library has tons of libraries and has a complicated dependence structure. I couldn't figure out what to do from the error message. Usually, I have to suggest students completely removing R and R Studio and all the installed libraries and reinstall them, and it isn't always successful. 

I tried to Google the solutions and search the RStudio Community for the installation problems but couldn't find any. Can anyone direct me to a solution or have any tips? I am looking for a solution a tip as simple as possible that I can share with my students since they are mostly new to R and I don't expect them to be able to understand and follow complicated instructions.

Or is it possible to make the installation more stable? The installation often failed if some of the dependent libraries have been installed earlier. 

Thank you in advance!

**Comment by dtkaplan** [comment]
Is it possible for you to attach to your message a copy of the error message your students are seeing when the installation fails?

**Comment by nicholasjhorton** [comment]
I'm sorry to hear about these complications. You are correct that there are many interdependencies (particularly related to dplyr) and this can make things more difficult when installing.

My main tip is to ensure that students are running the most recent version of R and that they ensure that their other packages are updated. 

If there are examples where that doesn't address the problem it would be helpful to include the error message along with the output of `sessioninfo::session_info()` to help clarify the issue.
