### ISSUE TITLE
problems with package `terra`

### ISSUE THREAD

**Issue by hardin47** [ProjectMOSAIC/mosaic#791]
i have a student trying to install `mosaic`, and they are running into problems with the `terra` package.  

* installing *source* package ‘terra’ ...
** package ‘terra’ successfully unpacked and MD5 sums checked
** using staged installation
configure: CC: clang
configure: CXX: clang++ -std=gnu++11
checking for gdal-config... no
no
configure: error: gdal-config not found or not executable.
ERROR: configuration failed for package ‘terra’
* removing ‘/opt/homebrew/Cellar/r/4.1.2/lib/R/library/terra’
Warning in install.packages :
  installation of package ‘terra’ had non-zero exit status
ERROR: dependency ‘terra’ is not available for package ‘raster’
* removing ‘/opt/homebrew/Cellar/r/4.1.2/lib/R/library/raster’
Warning in install.packages :
  installation of package ‘raster’ had non-zero exit status
ERROR: dependency ‘raster’ is not available for package ‘leaflet’
* removing ‘/opt/homebrew/Cellar/r/4.1.2/lib/R/library/leaflet’
Warning in install.packages :
  installation of package ‘leaflet’ had non-zero exit status
ERROR: dependency ‘leaflet’ is not available for package ‘mosaic’
* removing ‘/opt/homebrew/Cellar/r/4.1.2/lib/R/library/mosaic’
Warning in install.packages :
  installation of package ‘mosaic’ had non-zero exit status

i'm not entirely sure if it is a problem on our end, but i thought i'd bring it up, just in case this is a bigger problem affecting others.

thanks!

**Comment by rpruim** [comment]
@hardin47 , did you get this resolved?

**Comment by hardin47** [comment]
no, but we didn't keep trying.  for that class i'm not using mosaic a lot.  and i think the student was able to do the assignment on the college server.

**Comment by rpruim** [comment]
I'm just coming up for air after a busy start to the semester.  

It's hard to know exactly how the student landed here, but my usual advice includes:

* install packages nearer to the problem first and work out from there
* try update.packages() to make sure that all packages are up-to-date and built with the current version of R.

The mention of brew makes me wonder a bit how the student installed R and R packages.  That might also be part of the problem.

**Comment by rpruim** [comment]
@hardin47 : one other thing to recommend to students is that they restart R before installing packages and again afterwards.  This is especially true if they have lots of packages loaded in their current session.

I'm going to close this on the assumption that there is nothing we need to implement in the mosaic package that will help here.
