### ISSUE TITLE
scatterString not found error? 

### ISSUE THREAD

**Issue by beanumber** [ProjectMOSAIC/mosaic#798]
```
> mplot(penguins)
Choose a plot type. 

1: 1-variable (histogram, density plot, etc.)
2: 2-variable (scatter, boxplot, etc.)
3: map

Selection: 2
Error in .scatterString(vals, system, variables = variables) : 
  could not find function ".scatterString"
```

In lab right now and everyone is having this problem. I haven't had time to investigate. Is there a quick fix?

**Comment by beanumber** [comment]
Also, 

```
> mosaic:::.scatterString
NULL
```

**Comment by rpruim** [comment]
@beanumber, this should be fixed on github and will be making its way to CRAN.  Sorry for the unexpected hassle.  Looks like I did a "paste before" when it should have been a "paste after" when adding a `check_installed()` to reduce dependencies that are not needed for all users.

**Comment by beanumber** [comment]
Thanks @rpruim !
