### ISSUE TITLE
maptools archived

### ISSUE THREAD

**Issue by rsbivand** [ProjectMOSAIC/mosaic#801]
@rpruim maptools was archived yesterday, so please do move to submit an updated version of mosaic as soon as possible. See https://github.com/r-spatial/evolution https://r-spatial.github.io/evolution/ for details.

**Comment by nicholasjhorton** [comment]
Thanks for the pull request @olivroy.

We are working to address the issues with the deprecated features here and in `ggformula`, see https://github.com/ProjectMOSAIC/ggformula/issues/168#issuecomment-1775141663

**Comment by rsbivand** [comment]
Thanks for your cooperation!
