### ISSUE TITLE
Odd right-tail behavior in `xpt`

### ISSUE THREAD

**Issue by math-mcshane** [ProjectMOSAIC/mosaic#802]
## Three examples that demonstrate issue (`gf_refine` to emphasize issue; plot just crops on RHS o/w)
Right tail appears to cut off around 3. 

``` r
mosaic::xpt(q = c(-1, 1), df = 7, refinements = list(gf_refine(xlim(c(-5, 5)))))
#> Registered S3 method overwritten by 'mosaic':
#>   method                           from   
#>   fortify.SpatialPolygonsDataFrame ggplot2
```

![](https://i.imgur.com/RRTUJU7.png)

    #> [1] 0.1753083 0.8246917
    mosaic::xpt(q = c(-3, 3), df = 7, refinements = list(gf_refine(xlim(c(-5, 5)))))

![](https://i.imgur.com/AMAKROP.png)

    #> [1] 0.009971063 0.990028937
    mosaic::xpt(q = 3, df = 7, refinements = list(gf_refine(xlim(c(-5, 5)))))

![](https://i.imgur.com/z4uG9Hm.png)

## One plot that works as usual

    #> [1] 0.9900289
    mosaic::xpt(q = c(-3, 3), df = 20, refinements = list(gf_refine(xlim(c(-5, 5)))))

![](https://i.imgur.com/ChCmZMG.png)

    #> [1] 0.003537949 0.996462051

<sup>Created on 2023-12-04 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by rpruim** [comment]
@math-mcshane , thanks for reporting this.

I think I've found the source of the bug.  I'll do a bit more testing, but here is what I'm seeing after my fix.

``` r
mosaic::xpt(q = c(-1, 1), df = 7)
#> Registered S3 method overwritten by 'mosaic':
#>   method                           from   
#>   fortify.SpatialPolygonsDataFrame ggplot2
```

![](https://i.imgur.com/QF6MrtX.png)

    #> [1] 0.1753083 0.8246917

<sup>Created on 2024-02-17 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by math-mcshane** [comment]
Cool cool cool

**Comment by rpruim** [comment]
Hope to have this on CRAN soon.

**Comment by rpruim** [comment]
Closing.  This is on CRAN now.

**Comment by math-mcshane** [comment]
Updated package. Looks great! Thanks @rpruim
