### ISSUE TITLE
qdata() and the ~ notation in aggregating statistics

### ISSUE THREAD

**Issue by dtkaplan** [ProjectMOSAIC/mosaic#92]
Here's an example from the resampling vignette (which I am editing)
> trials <- do(1000) * mean(~Price, data=resample(mustangs))

This works nicely
> qdata( c(.05,.95), result, data=trials)
    5%    95% 
12.517 19.528 

But this doesn't.
> qdata( c(.05,.95), ~result, data=trials)
Error in if (as.character(ans[[1L]])[1L] == "~") { : 
  missing value where TRUE/FALSE needed
In addition: Warning messages:
1: In is.na(x) :
  is.na() applied to non-(list or vector) of type 'language'
2: In is.na(x) :
  is.na() applied to non-(list or vector) of type 'language'

I like the fact that qdata() works in the first case, and I'd like to see that functionality extended more generally --- something we've talked about without yet coming to consensus.  But whichever way we resolve the requirement for ~, qdata() should work with the ~ when it is given.

**Comment by rpruim** [comment]
```r
qdata( c(.05,.95), ~age, data=HELPrct)
##     quantile    p
## 5%        24 0.05
## 95%       49 0.95
qdata( c(.05,.95), age, data=HELPrct)
##     quantile    p
## 5%        24 0.05
## 95%       49 0.95
```

**Comment by nicholasjhorton** [comment]
Note that per our agreement, any *advertised* usage is of the first form, never the latter!

Nick

> On Oct 7, 2015, at 2:25 PM, Randall Pruim <notifications@github.com> wrote:
> 
> qdata( c(.05,.95), ~age, data=HELPrct)
> 
> 
> ##     quantile    p
> ## 5%        24 0.05
> ## 95%       49 0.95
> 
> qdata( c(.
> 05,.95), age, data=HELPrct)
> 
> 
> ##     quantile    p
> ## 5%        24 0.05
> ## 95%       49 0.95
> —
> Reply to this email directly or view it on GitHub.
> 

Nicholas Horton 
Professor of Statistics
Department of Mathematics and Statistics, Amherst College
Box 2239, 31 Quadrangle Dr
Amherst, MA 01002-5000
https://www.amherst.edu/people/facstaff/nhorton

**Comment by rpruim** [comment]
Absolutely.  But this issue was about *adding* the formula interface to a function that didn't originally have it.
